// Banque « LA MATIERE » (Questionner le monde, CE2, cycle 2). Sous-matiere,
// domaine dedie `matiere` :
//   QM.MATIERE.ETATS     solide / liquide / gaz (reconnaitre, trier) ;
//   QM.MATIERE.EAU       etats de l'eau et changements d'etat (fusion,
//                        solidification, evaporation, condensation) ;
//   QM.MATIERE.MELANGES  melanges et solutions simples (se dissout ou non,
//                        separer, filtration) ;
//   QM.MATIERE.AIR       l'air existe (prend de la place, le vent).
//
// Progression : N1 QCM ; N2/N3 QCM, TRI ou ORDRE ; N4 reponse LIBRE (texte) ou
// manipulation. Contenus originaux, scientifiquement exacts, rediges pour l'oral.

import { type QmItem, ordre, tri } from "./types";

export const BANQUE_MATIERE: QmItem[] = [
  // =======================================================================
  // QM.MATIERE.ETATS — solide / liquide / gaz
  // =======================================================================
  { cle: "qm-mat-eta-n1-a", competence: "QM.MATIERE.ETATS", niveau: 1, format: "qcm",
    consigne: "L'eau dans un verre, c'est un solide, un liquide ou un gaz ?",
    options: ["un liquide", "un solide", "un gaz"], attendu: "un liquide",
    explication: "L'eau coule et prend la forme du verre : c'est un liquide." },
  { cle: "qm-mat-eta-n1-b", competence: "QM.MATIERE.ETATS", niveau: 1, format: "qcm",
    consigne: "Un glaçon, qu'est-ce que c'est ?",
    options: ["un solide", "un liquide", "un gaz"], attendu: "un solide",
    explication: "Un glaçon est dur et garde sa forme : c'est un solide." },
  { cle: "qm-mat-eta-n2-a", competence: "QM.MATIERE.ETATS", niveau: 2, format: "tri",
    consigne: "Classe chaque chose : solide ou liquide.",
    ...tri(["solide", "liquide"], [["un caillou", "solide"], ["le lait", "liquide"], ["un crayon", "solide"], ["le jus", "liquide"]]),
    explication: "Un caillou et un crayon gardent leur forme : ce sont des solides. Le lait et le jus coulent : ce sont des liquides." },
  { cle: "qm-mat-eta-n2-b", competence: "QM.MATIERE.ETATS", niveau: 2, format: "qcm",
    consigne: "Qu'est-ce qui garde toujours sa forme ?",
    options: ["un solide", "un liquide", "un gaz"], attendu: "un solide",
    explication: "Un solide, comme une bille, garde sa forme. Un liquide prend la forme de son récipient." },
  { cle: "qm-mat-eta-n3-a", competence: "QM.MATIERE.ETATS", niveau: 3, format: "tri",
    consigne: "Classe chaque chose : solide, liquide ou gaz.",
    ...tri(["solide", "liquide", "gaz"], [["le bois", "solide"], ["l'eau", "liquide"], ["l'air", "gaz"]]),
    explication: "Le bois est solide, l'eau est liquide, l'air est un gaz." },
  { cle: "qm-mat-eta-n3-b", competence: "QM.MATIERE.ETATS", niveau: 3, format: "qcm",
    consigne: "Un liquide versé dans une bouteille, que fait-il ?",
    options: ["il prend la forme de la bouteille", "il garde sa forme", "il disparaît"], attendu: "il prend la forme de la bouteille",
    explication: "Un liquide prend la forme du récipient qui le contient." },
  { cle: "qm-mat-eta-n4-a", competence: "QM.MATIERE.ETATS", niveau: 4, format: "texte",
    consigne: "Un gaz qu'on respire et qui est partout autour de nous, c'est l'... Écris le mot.",
    attendu: "air",
    explication: "L'air est un gaz invisible, présent partout autour de nous." },
  { cle: "qm-mat-eta-n4-b", competence: "QM.MATIERE.ETATS", niveau: 4, format: "texte",
    consigne: "La vapeur et la fumée n'ont pas de forme fixe. Elles sont à l'état... Écris le mot : solide, liquide ou gaz.",
    attendu: "gaz",
    explication: "La vapeur et la fumée sont des gaz : elles n'ont pas de forme fixe." },

  // =======================================================================
  // QM.MATIERE.EAU — etats de l'eau et changements d'etat
  // =======================================================================
  { cle: "qm-mat-eau-n1-a", competence: "QM.MATIERE.EAU", niveau: 1, format: "qcm",
    consigne: "Quand l'eau devient très froide, en quoi se transforme-t-elle ?",
    options: ["en glace", "en vapeur", "en sable"], attendu: "en glace",
    explication: "Quand l'eau gèle, elle devient de la glace, qui est un solide." },
  { cle: "qm-mat-eau-n1-b", competence: "QM.MATIERE.EAU", niveau: 1, format: "qcm",
    consigne: "Quand on chauffe de l'eau très fort, en quoi se transforme-t-elle ?",
    options: ["en vapeur", "en glace", "en bois"], attendu: "en vapeur",
    explication: "L'eau chauffée se transforme en vapeur, qui est un gaz." },
  { cle: "qm-mat-eau-n2-a", competence: "QM.MATIERE.EAU", niveau: 2, format: "qcm",
    consigne: "La glace qui chauffe et redevient de l'eau liquide : comment s'appelle ce changement ?",
    options: ["la fusion", "la solidification", "l'évaporation"], attendu: "la fusion",
    explication: "Quand un solide fond et devient liquide, c'est la fusion. La glace fond et devient de l'eau." },
  { cle: "qm-mat-eau-n2-b", competence: "QM.MATIERE.EAU", niveau: 2, format: "qcm",
    consigne: "L'eau liquide qui gèle et devient de la glace : comment s'appelle ce changement ?",
    options: ["la solidification", "la fusion", "l'évaporation"], attendu: "la solidification",
    explication: "Quand un liquide gèle et devient solide, c'est la solidification." },
  { cle: "qm-mat-eau-n3-a", competence: "QM.MATIERE.EAU", niveau: 3, format: "qcm",
    consigne: "L'eau d'une flaque qui disparaît au soleil : comment s'appelle ce changement ?",
    options: ["l'évaporation", "la fusion", "la solidification"], attendu: "l'évaporation",
    explication: "L'eau liquide chauffée part dans l'air sous forme de vapeur : c'est l'évaporation." },
  { cle: "qm-mat-eau-n3-b", competence: "QM.MATIERE.EAU", niveau: 3, format: "tri",
    consigne: "Range chaque changement avec son résultat.",
    ...tri(["devient solide", "devient liquide", "devient gaz"], [["la solidification", "devient solide"], ["la fusion", "devient liquide"], ["l'évaporation", "devient gaz"]]),
    explication: "La solidification donne un solide, la fusion donne un liquide, l'évaporation donne un gaz." },
  { cle: "qm-mat-eau-n4-a", competence: "QM.MATIERE.EAU", niveau: 4, format: "texte",
    consigne: "La vapeur qui se refroidit et redevient des gouttes d'eau, comme la buée sur une vitre : ce changement s'appelle la... Écris le mot.",
    attendu: "condensation",
    explication: "Quand la vapeur se refroidit et redevient liquide, c'est la condensation, comme la buée sur une vitre froide." },
  { cle: "qm-mat-eau-n4-b", competence: "QM.MATIERE.EAU", niveau: 4, format: "ordre",
    consigne: "Range l'eau du plus froid au plus chaud.",
    ...ordre(["la glace", "l'eau liquide", "la vapeur"]),
    explication: "Très froid : la glace. Normal : l'eau liquide. Très chaud : la vapeur." },

  // =======================================================================
  // QM.MATIERE.MELANGES — melanges et solutions simples
  // =======================================================================
  { cle: "qm-mat-mel-n1-a", competence: "QM.MATIERE.MELANGES", niveau: 1, format: "qcm",
    consigne: "Tu mets du sucre dans l'eau et tu remues. Que se passe-t-il ?",
    options: ["le sucre disparaît dans l'eau", "le sucre reste entier", "l'eau devient dure"], attendu: "le sucre disparaît dans l'eau",
    explication: "Le sucre se mélange à l'eau et on ne le voit plus : il se dissout. On a fait une solution." },
  { cle: "qm-mat-mel-n1-b", competence: "QM.MATIERE.MELANGES", niveau: 1, format: "qcm",
    consigne: "Tu mets du sable dans l'eau. Que fait le sable ?",
    options: ["il tombe au fond", "il disparaît", "il devient sucre"], attendu: "il tombe au fond",
    explication: "Le sable ne se dissout pas : il tombe au fond du verre." },
  { cle: "qm-mat-mel-n2-a", competence: "QM.MATIERE.MELANGES", niveau: 2, format: "tri",
    consigne: "Classe : est-ce que ça se dissout dans l'eau ?",
    ...tri(["se dissout", "ne se dissout pas"], [["le sucre", "se dissout"], ["le sel", "se dissout"], ["le sable", "ne se dissout pas"], ["l'huile", "ne se dissout pas"]]),
    explication: "Le sucre et le sel se dissolvent dans l'eau. Le sable et l'huile ne se dissolvent pas." },
  { cle: "qm-mat-mel-n2-b", competence: "QM.MATIERE.MELANGES", niveau: 2, format: "qcm",
    consigne: "Un mélange où on ne voit plus ce qu'on a ajouté s'appelle...",
    options: ["une solution", "un solide", "un glaçon"], attendu: "une solution",
    explication: "Quand le sucre a disparu dans l'eau, on obtient une solution." },
  { cle: "qm-mat-mel-n3-a", competence: "QM.MATIERE.MELANGES", niveau: 3, format: "qcm",
    consigne: "Comment séparer le sable de l'eau ?",
    options: ["avec un filtre", "en chauffant le verre", "en remuant"], attendu: "avec un filtre",
    explication: "On verse dans un filtre : l'eau passe à travers, le sable reste. C'est la filtration." },
  { cle: "qm-mat-mel-n3-b", competence: "QM.MATIERE.MELANGES", niveau: 3, format: "qcm",
    consigne: "Quand on mélange de l'eau et de l'huile, que se passe-t-il ?",
    options: ["elles ne se mélangent pas", "elles se mélangent bien", "elles deviennent du sucre"], attendu: "elles ne se mélangent pas",
    explication: "L'huile reste au-dessus de l'eau : l'eau et l'huile ne se mélangent pas." },
  { cle: "qm-mat-mel-n4-a", competence: "QM.MATIERE.MELANGES", niveau: 4, format: "texte",
    consigne: "Quand le sucre se mélange complètement à l'eau et disparaît, on dit qu'il se... Écris le mot.",
    attendu: "dissout",
    explication: "Le sucre se dissout dans l'eau et forme une solution." },
  { cle: "qm-mat-mel-n4-b", competence: "QM.MATIERE.MELANGES", niveau: 4, format: "texte",
    consigne: "Pour séparer le sable de l'eau, on verse le mélange dans un... Écris le mot.",
    attendu: "filtre",
    explication: "Le filtre laisse passer l'eau et retient le sable." },

  // =======================================================================
  // QM.MATIERE.AIR — l'air existe
  // =======================================================================
  { cle: "qm-mat-air-n1-a", competence: "QM.MATIERE.AIR", niveau: 1, format: "qcm",
    consigne: "Qu'y a-t-il dans un ballon de baudruche gonflé ?",
    options: ["de l'air", "de l'eau", "du sable"], attendu: "de l'air",
    explication: "Le ballon est gonflé d'air. L'air prend de la place, même si on ne le voit pas." },
  { cle: "qm-mat-air-n1-b", competence: "QM.MATIERE.AIR", niveau: 1, format: "qcm",
    consigne: "L'air, quand est-ce qu'on le sent ?",
    options: ["quand le vent souffle", "quand on le mange", "quand on le voit"], attendu: "quand le vent souffle",
    explication: "On ne voit pas l'air, mais on le sent quand le vent souffle sur le visage." },
  { cle: "qm-mat-air-n2-a", competence: "QM.MATIERE.AIR", niveau: 2, format: "qcm",
    consigne: "Quand tu souffles dans l'eau avec une paille, que vois-tu ?",
    options: ["des bulles d'air", "des cailloux", "des glaçons"], attendu: "des bulles d'air",
    explication: "Les bulles montrent que l'air sort de la paille : l'air existe bel et bien." },
  { cle: "qm-mat-air-n2-b", competence: "QM.MATIERE.AIR", niveau: 2, format: "qcm",
    consigne: "Est-ce que l'air prend de la place ?",
    options: ["oui", "non", "seulement la nuit"], attendu: "oui",
    explication: "L'air prend de la place : il gonfle un ballon, un pneu ou une bouée." },
  { cle: "qm-mat-air-n3-a", competence: "QM.MATIERE.AIR", niveau: 3, format: "qcm",
    consigne: "Un sac en plastique gonflé puis fermé est...",
    options: ["rempli d'air", "vide", "plein d'eau"], attendu: "rempli d'air",
    explication: "Le sac gonflé est rempli d'air : l'air occupe tout l'espace à l'intérieur." },
  { cle: "qm-mat-air-n3-b", competence: "QM.MATIERE.AIR", niveau: 3, format: "qcm",
    consigne: "Le vent, qu'est-ce que c'est ?",
    options: ["de l'air qui bouge", "de l'eau", "du feu"], attendu: "de l'air qui bouge",
    explication: "Le vent, c'est de l'air en mouvement." },
  { cle: "qm-mat-air-n4-a", competence: "QM.MATIERE.AIR", niveau: 4, format: "texte",
    consigne: "On ne le voit pas, il est partout autour de nous et on le respire : c'est l'... Écris le mot.",
    attendu: "air",
    explication: "L'air est partout autour de nous ; on le respire pour vivre." },
  { cle: "qm-mat-air-n4-b", competence: "QM.MATIERE.AIR", niveau: 4, format: "texte",
    consigne: "Quand l'air bouge dehors, on l'appelle le... Écris le mot.",
    attendu: "vent",
    explication: "Le vent, c'est de l'air qui se déplace." },
];

export const COMPETENCES_MATIERE = [
  "QM.MATIERE.ETATS",
  "QM.MATIERE.EAU",
  "QM.MATIERE.MELANGES",
  "QM.MATIERE.AIR",
] as const;
