// Banque « LE VIVANT » (Questionner le monde, CE2, cycle 2). Sous-matiere,
// domaine dedie `vivant` :
//   QM.VIVANT.CARACTERISTIQUES  caracteristiques du vivant (naitre, grandir, se
//                               nourrir, se reproduire, mourir ; vivant / non vivant) ;
//   QM.VIVANT.CYCLES            cycles de vie (grenouille, papillon, poule, plante
//                               a graine) : RANGER les etapes ;
//   QM.VIVANT.CHAINES           regimes alimentaires (herbivore/carnivore/omnivore)
//                               et chaines alimentaires simples (qui mange qui) ;
//   QM.VIVANT.PLANTES           besoins des plantes (eau, lumiere, air, terre) ;
//   QM.VIVANT.CORPS             corps humain (squelette, muscles, articulations,
//                               les 5 sens) ;
//   QM.VIVANT.HYGIENE           hygiene de vie (alimentation, sommeil, dents, sport).
//
// Progression des formats : N1 QCM (rappel leger) ; N2/N3 QCM, TRI ou ORDRE
// (coeur CE2) ; N4 reponse LIBRE (texte) ou manipulation exigeante (ordre a 4-5
// etapes). Consignes redigees POUR L'ORAL, avec un exemple concret. Contenus
// originaux et scientifiquement exacts.

import { type QmItem, ordre, tri } from "./types";

export const BANQUE_VIVANT: QmItem[] = [
  // =======================================================================
  // QM.VIVANT.CARACTERISTIQUES — vivant / non vivant, les 5 signes du vivant
  // =======================================================================
  { cle: "qm-viv-car-n1-a", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 1, format: "qcm",
    consigne: "Parmi ces choses, laquelle est vivante ?",
    options: ["un chat", "un caillou", "un vélo"], attendu: "un chat",
    explication: "Un chat est vivant : il naît, il grandit, il mange et il aura des petits. Un caillou ne grandit pas." },
  { cle: "qm-viv-car-n1-b", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 1, format: "qcm",
    consigne: "Qu'est-ce qui n'est pas vivant ?",
    options: ["une fleur", "un ballon", "un oiseau"], attendu: "un ballon",
    explication: "Un ballon n'est pas vivant : il ne mange pas et ne grandit pas. Une fleur et un oiseau, eux, sont vivants." },
  { cle: "qm-viv-car-n2-a", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 2, format: "qcm",
    consigne: "Tous les êtres vivants font une même chose en grandissant. Laquelle ?",
    options: ["ils grandissent", "ils sont en métal", "ils ont des roues"], attendu: "ils grandissent",
    explication: "Tous les êtres vivants grandissent, comme toi qui deviens plus grand chaque année." },
  { cle: "qm-viv-car-n2-b", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 2, format: "tri",
    consigne: "Classe chaque chose : vivante ou non vivante.",
    ...tri(["vivant", "non vivant"], [["un arbre", "vivant"], ["une voiture", "non vivant"], ["un poisson", "vivant"], ["un caillou", "non vivant"]]),
    explication: "Un arbre et un poisson sont vivants : ils grandissent et se nourrissent. Une voiture et un caillou ne sont pas vivants." },
  { cle: "qm-viv-car-n3-a", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 3, format: "tri",
    consigne: "Range chaque chose au bon endroit : vivante ou non vivante.",
    ...tri(["vivant", "non vivant"], [["un champignon", "vivant"], ["un nuage", "non vivant"], ["une abeille", "vivant"], ["une table", "non vivant"]]),
    explication: "Un champignon et une abeille sont vivants. Un nuage et une table ne le sont pas." },
  { cle: "qm-viv-car-n3-b", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 3, format: "qcm",
    consigne: "Que font les êtres vivants pour avoir des petits ?",
    options: ["ils se reproduisent", "ils se cassent", "ils rouillent"], attendu: "ils se reproduisent",
    explication: "Les êtres vivants se reproduisent : ils ont des petits, comme la chatte qui a des chatons." },
  { cle: "qm-viv-car-n4-a", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 4, format: "texte",
    consigne: "Un être vivant naît, grandit, se nourrit, se reproduit, puis à la fin de sa vie il... Écris le mot.",
    attendu: "meurt",
    explication: "À la fin de sa vie, un être vivant meurt. C'est la dernière étape de la vie." },
  { cle: "qm-viv-car-n4-b", competence: "QM.VIVANT.CARACTERISTIQUES", niveau: 4, format: "texte",
    consigne: "Un lapin mange de l'herbe. Quand un animal mange, on dit qu'il se... Écris le mot.",
    attendu: "nourrit",
    explication: "Quand un animal mange, il se nourrit. Se nourrir, c'est un signe du vivant." },

  // =======================================================================
  // QM.VIVANT.CYCLES — ranger les etapes d'un cycle de vie
  // =======================================================================
  { cle: "qm-viv-cyc-n1-a", competence: "QM.VIVANT.CYCLES", niveau: 1, format: "qcm",
    consigne: "Qu'y a-t-il tout au début de la vie d'une poule ?",
    options: ["un œuf", "un poussin", "une poule"], attendu: "un œuf",
    explication: "La vie de la poule commence par un œuf. Ensuite, le poussin en sort." },
  { cle: "qm-viv-cyc-n1-b", competence: "QM.VIVANT.CYCLES", niveau: 1, format: "qcm",
    consigne: "Où grandit le têtard, le bébé de la grenouille ?",
    options: ["dans l'eau", "dans le sable", "dans le feu"], attendu: "dans l'eau",
    explication: "Le têtard grandit dans l'eau, puis il devient une grenouille." },
  { cle: "qm-viv-cyc-n2-a", competence: "QM.VIVANT.CYCLES", niveau: 2, format: "ordre",
    consigne: "Range dans l'ordre la vie de la poule, du début à la fin.",
    ...ordre(["l'œuf", "le poussin", "la poule"]),
    explication: "D'abord l'œuf, puis le poussin qui en sort, puis la poule qui a grandi." },
  { cle: "qm-viv-cyc-n2-b", competence: "QM.VIVANT.CYCLES", niveau: 2, format: "ordre",
    consigne: "Range dans l'ordre la vie de la grenouille.",
    ...ordre(["l'œuf", "le têtard", "la grenouille"]),
    explication: "D'abord l'œuf dans l'eau, puis le têtard, puis la grenouille." },
  { cle: "qm-viv-cyc-n3-a", competence: "QM.VIVANT.CYCLES", niveau: 3, format: "ordre",
    consigne: "Range dans l'ordre la vie du papillon.",
    ...ordre(["l'œuf", "la chenille", "la chrysalide", "le papillon"]),
    explication: "L'œuf donne une chenille, la chenille se transforme dans une chrysalide, puis le papillon en sort." },
  { cle: "qm-viv-cyc-n3-b", competence: "QM.VIVANT.CYCLES", niveau: 3, format: "ordre",
    consigne: "Range dans l'ordre la vie d'une plante, de la graine à la fleur.",
    ...ordre(["la graine", "la pousse", "la plante", "la fleur"]),
    explication: "La graine germe et donne une pousse, qui grandit en plante, puis fait une fleur." },
  { cle: "qm-viv-cyc-n4-a", competence: "QM.VIVANT.CYCLES", niveau: 4, format: "ordre",
    consigne: "Range dans l'ordre toutes les étapes de la vie de la grenouille.",
    ...ordre(["l'œuf", "le têtard", "le têtard à pattes", "la grenouille"]),
    explication: "L'œuf, puis le têtard, puis le têtard qui a des pattes, puis la grenouille adulte." },
  { cle: "qm-viv-cyc-n4-b", competence: "QM.VIVANT.CYCLES", niveau: 4, format: "ordre",
    consigne: "Range dans l'ordre la vie d'une plante, de la graine au fruit.",
    ...ordre(["la graine", "la pousse", "la plante", "la fleur", "le fruit"]),
    explication: "La graine, la pousse, la plante, la fleur, et enfin le fruit qui contient de nouvelles graines." },

  // =======================================================================
  // QM.VIVANT.CHAINES — regimes alimentaires et chaines alimentaires
  // =======================================================================
  { cle: "qm-viv-cha-n1-a", competence: "QM.VIVANT.CHAINES", niveau: 1, format: "qcm",
    consigne: "Le lapin mange de l'herbe et des carottes. Que mange-t-il ?",
    options: ["des plantes", "de la viande", "des cailloux"], attendu: "des plantes",
    explication: "Le lapin mange des plantes : c'est un herbivore." },
  { cle: "qm-viv-cha-n1-b", competence: "QM.VIVANT.CHAINES", niveau: 1, format: "qcm",
    consigne: "Le lion mange d'autres animaux. Que mange-t-il ?",
    options: ["de la viande", "des plantes", "du sable"], attendu: "de la viande",
    explication: "Le lion mange de la viande : c'est un carnivore." },
  { cle: "qm-viv-cha-n2-a", competence: "QM.VIVANT.CHAINES", niveau: 2, format: "tri",
    consigne: "Classe chaque animal : herbivore mange des plantes, carnivore mange de la viande.",
    ...tri(["herbivore", "carnivore"], [["la vache", "herbivore"], ["le loup", "carnivore"], ["le lapin", "herbivore"], ["le renard", "carnivore"]]),
    explication: "La vache et le lapin mangent des plantes. Le loup et le renard mangent de la viande." },
  { cle: "qm-viv-cha-n2-b", competence: "QM.VIVANT.CHAINES", niveau: 2, format: "qcm",
    consigne: "Un animal qui mange des plantes et de la viande, comment s'appelle-t-il ?",
    options: ["omnivore", "herbivore", "carnivore"], attendu: "omnivore",
    explication: "L'ours mange des plantes et des animaux : il est omnivore. Toi aussi, tu es omnivore." },
  { cle: "qm-viv-cha-n3-a", competence: "QM.VIVANT.CHAINES", niveau: 3, format: "ordre",
    consigne: "Range la chaîne alimentaire : qui est mangé par qui. Commence par la plante.",
    ...ordre(["l'herbe", "le lapin", "le renard"]),
    explication: "L'herbe est mangée par le lapin, et le lapin est mangé par le renard." },
  { cle: "qm-viv-cha-n3-b", competence: "QM.VIVANT.CHAINES", niveau: 3, format: "ordre",
    consigne: "Range la chaîne alimentaire. Commence par la plante.",
    ...ordre(["la feuille", "la chenille", "l'oiseau"]),
    explication: "La feuille est mangée par la chenille, et la chenille est mangée par l'oiseau." },
  { cle: "qm-viv-cha-n4-a", competence: "QM.VIVANT.CHAINES", niveau: 4, format: "texte",
    consigne: "Au tout début d'une chaîne alimentaire, il y a toujours une... Écris le mot.",
    attendu: "plante",
    explication: "Au début d'une chaîne alimentaire, il y a toujours une plante, car elle fabrique sa propre nourriture." },
  { cle: "qm-viv-cha-n4-b", competence: "QM.VIVANT.CHAINES", niveau: 4, format: "ordre",
    consigne: "Range la chaîne alimentaire, du début à la fin.",
    ...ordre(["les graines", "la souris", "le serpent", "l'aigle"]),
    explication: "Les graines sont mangées par la souris, la souris par le serpent, et le serpent par l'aigle." },

  // =======================================================================
  // QM.VIVANT.PLANTES — besoins des plantes
  // =======================================================================
  { cle: "qm-viv-pla-n1-a", competence: "QM.VIVANT.PLANTES", niveau: 1, format: "qcm",
    consigne: "De quoi une plante a-t-elle besoin pour vivre ?",
    options: ["de l'eau", "du chocolat", "du bruit"], attendu: "de l'eau",
    explication: "Une plante a besoin d'eau. Sans eau, elle se dessèche." },
  { cle: "qm-viv-pla-n1-b", competence: "QM.VIVANT.PLANTES", niveau: 1, format: "qcm",
    consigne: "Qu'est-ce qui aide la plante à grandir ?",
    options: ["la lumière", "le noir", "le froid"], attendu: "la lumière",
    explication: "La plante a besoin de lumière. C'est le soleil qui l'aide à grandir." },
  { cle: "qm-viv-pla-n2-a", competence: "QM.VIVANT.PLANTES", niveau: 2, format: "tri",
    consigne: "Classe : de quoi la plante a besoin, ou pas besoin, pour vivre.",
    ...tri(["besoin", "pas besoin"], [["l'eau", "besoin"], ["la lumière", "besoin"], ["le chocolat", "pas besoin"], ["la télévision", "pas besoin"]]),
    explication: "La plante a besoin d'eau et de lumière. Elle n'a pas besoin de chocolat ni de télévision." },
  { cle: "qm-viv-pla-n2-b", competence: "QM.VIVANT.PLANTES", niveau: 2, format: "qcm",
    consigne: "Par où la plante boit-elle l'eau de la terre ?",
    options: ["par ses racines", "par ses fleurs", "par ses graines"], attendu: "par ses racines",
    explication: "Les racines boivent l'eau dans la terre et la font monter dans toute la plante." },
  { cle: "qm-viv-pla-n3-a", competence: "QM.VIVANT.PLANTES", niveau: 3, format: "qcm",
    consigne: "Que se passe-t-il pour une plante laissée sans eau et sans lumière ?",
    options: ["elle meurt", "elle grandit mieux", "elle vole"], attendu: "elle meurt",
    explication: "Sans eau ni lumière, la plante se fane et meurt. Elle a besoin des deux pour vivre." },
  { cle: "qm-viv-pla-n3-b", competence: "QM.VIVANT.PLANTES", niveau: 3, format: "tri",
    consigne: "Classe : de quoi une plante a besoin, ou pas besoin.",
    ...tri(["besoin", "pas besoin"], [["l'air", "besoin"], ["la terre", "besoin"], ["la neige", "pas besoin"], ["la musique", "pas besoin"]]),
    explication: "La plante a besoin d'air et de terre. Elle n'a pas besoin de neige ni de musique." },
  { cle: "qm-viv-pla-n4-a", competence: "QM.VIVANT.PLANTES", niveau: 4, format: "texte",
    consigne: "Une plante fabrique sa nourriture grâce à la lumière du... Écris le mot.",
    attendu: "soleil",
    explication: "Grâce à la lumière du soleil, la plante fabrique sa nourriture dans ses feuilles." },
  { cle: "qm-viv-pla-n4-b", competence: "QM.VIVANT.PLANTES", niveau: 4, format: "texte",
    consigne: "La partie de la plante qui boit l'eau dans la terre s'appelle les... Écris le mot.",
    attendu: "racines",
    explication: "Les racines s'enfoncent dans la terre et boivent l'eau pour toute la plante." },

  // =======================================================================
  // QM.VIVANT.CORPS — squelette, muscles, articulations, 5 sens
  // =======================================================================
  { cle: "qm-viv-cor-n1-a", competence: "QM.VIVANT.CORPS", niveau: 1, format: "qcm",
    consigne: "Avec quoi vois-tu les choses ?",
    options: ["les yeux", "les oreilles", "le nez"], attendu: "les yeux",
    explication: "Tu vois avec tes yeux. C'est le sens de la vue." },
  { cle: "qm-viv-cor-n1-b", competence: "QM.VIVANT.CORPS", niveau: 1, format: "qcm",
    consigne: "Avec quoi entends-tu les sons ?",
    options: ["les oreilles", "la langue", "les mains"], attendu: "les oreilles",
    explication: "Tu entends avec tes oreilles. C'est le sens de l'ouïe." },
  { cle: "qm-viv-cor-n2-a", competence: "QM.VIVANT.CORPS", niveau: 2, format: "tri",
    consigne: "Range chaque partie du corps avec ce qu'elle sert à faire.",
    ...tri(["voir", "entendre", "sentir"], [["les yeux", "voir"], ["les oreilles", "entendre"], ["le nez", "sentir"]]),
    explication: "Les yeux servent à voir, les oreilles à entendre, le nez à sentir les odeurs." },
  { cle: "qm-viv-cor-n2-b", competence: "QM.VIVANT.CORPS", niveau: 2, format: "qcm",
    consigne: "Qu'est-ce qui soutient ton corps et te tient debout ?",
    options: ["le squelette", "les cheveux", "la peau"], attendu: "le squelette",
    explication: "Le squelette, c'est tous tes os ensemble. Il soutient ton corps comme les piliers d'une maison." },
  { cle: "qm-viv-cor-n3-a", competence: "QM.VIVANT.CORPS", niveau: 3, format: "qcm",
    consigne: "Qu'est-ce qui te permet de bouger et de plier ton bras ?",
    options: ["les muscles", "les ongles", "les dents"], attendu: "les muscles",
    explication: "Les muscles se contractent et tirent sur les os pour te faire bouger." },
  { cle: "qm-viv-cor-n3-b", competence: "QM.VIVANT.CORPS", niveau: 3, format: "qcm",
    consigne: "L'endroit où l'os se plie, comme le coude ou le genou, s'appelle...",
    options: ["une articulation", "un cheveu", "une narine"], attendu: "une articulation",
    explication: "Le coude et le genou sont des articulations : c'est là que les os se plient." },
  { cle: "qm-viv-cor-n4-a", competence: "QM.VIVANT.CORPS", niveau: 4, format: "texte",
    consigne: "Le sens qui te sert à sentir les odeurs avec ton nez s'appelle l'... Écris le mot.",
    attendu: "odorat",
    explication: "Avec le nez, tu sens les odeurs : c'est le sens de l'odorat." },
  { cle: "qm-viv-cor-n4-b", competence: "QM.VIVANT.CORPS", niveau: 4, format: "texte",
    consigne: "Tous tes os ensemble forment ton... Écris le mot.",
    attendu: "squelette",
    explication: "Tous tes os ensemble forment ton squelette, qui tient ton corps debout." },

  // =======================================================================
  // QM.VIVANT.HYGIENE — alimentation, sommeil, dents, activite physique
  // =======================================================================
  { cle: "qm-viv-hyg-n1-a", competence: "QM.VIVANT.HYGIENE", niveau: 1, format: "qcm",
    consigne: "Que faut-il faire pour garder des dents en bonne santé ?",
    options: ["se brosser les dents", "manger des bonbons", "ne rien faire"], attendu: "se brosser les dents",
    explication: "On se brosse les dents matin et soir pour enlever les microbes et garder des dents saines." },
  { cle: "qm-viv-hyg-n1-b", competence: "QM.VIVANT.HYGIENE", niveau: 1, format: "qcm",
    consigne: "De quoi ton corps a-t-il besoin la nuit pour se reposer ?",
    options: ["de dormir", "de courir", "de manger"], attendu: "de dormir",
    explication: "La nuit, ton corps a besoin de dormir pour se reposer et grandir." },
  { cle: "qm-viv-hyg-n2-a", competence: "QM.VIVANT.HYGIENE", niveau: 2, format: "tri",
    consigne: "Classe chaque habitude : bonne ou pas bonne pour la santé.",
    ...tri(["bon pour la santé", "pas bon pour la santé"], [["manger des légumes", "bon pour la santé"], ["faire du sport", "bon pour la santé"], ["manger trop de bonbons", "pas bon pour la santé"], ["rester toujours assis", "pas bon pour la santé"]]),
    explication: "Manger des légumes et bouger sont bons pour la santé. Trop de bonbons et rester assis ne le sont pas." },
  { cle: "qm-viv-hyg-n2-b", competence: "QM.VIVANT.HYGIENE", niveau: 2, format: "qcm",
    consigne: "Combien de fois par jour faut-il se brosser les dents ?",
    options: ["deux fois", "jamais", "une fois par semaine"], attendu: "deux fois",
    explication: "On se brosse les dents deux fois par jour, le matin et le soir." },
  { cle: "qm-viv-hyg-n3-a", competence: "QM.VIVANT.HYGIENE", niveau: 3, format: "qcm",
    consigne: "Pour être en forme, que faut-il faire chaque jour ?",
    options: ["bouger son corps", "regarder la télé toute la journée", "sauter les repas"], attendu: "bouger son corps",
    explication: "Bouger chaque jour, comme marcher ou jouer dehors, garde ton corps en forme." },
  { cle: "qm-viv-hyg-n3-b", competence: "QM.VIVANT.HYGIENE", niveau: 3, format: "tri",
    consigne: "Classe chaque habitude : bonne ou pas bonne pour la santé.",
    ...tri(["bon pour la santé", "pas bon pour la santé"], [["boire de l'eau", "bon pour la santé"], ["dormir assez", "bon pour la santé"], ["manger très salé", "pas bon pour la santé"], ["se coucher très tard", "pas bon pour la santé"]]),
    explication: "Boire de l'eau et bien dormir aident ton corps. Manger trop salé ou se coucher très tard le fatiguent." },
  { cle: "qm-viv-hyg-n4-a", competence: "QM.VIVANT.HYGIENE", niveau: 4, format: "texte",
    consigne: "Un repas équilibré contient surtout des fruits et des... Écris le mot.",
    attendu: "légumes",
    explication: "Un repas équilibré a des fruits et des légumes, qui donnent des vitamines à ton corps." },
  { cle: "qm-viv-hyg-n4-b", competence: "QM.VIVANT.HYGIENE", niveau: 4, format: "texte",
    consigne: "La nuit, un enfant de 8 ans a besoin de beaucoup de... pour grandir. Écris le mot.",
    attendu: "sommeil",
    explication: "Un enfant a besoin de beaucoup de sommeil, environ dix heures par nuit, pour grandir et être en forme." },
];

export const COMPETENCES_VIVANT = [
  "QM.VIVANT.CARACTERISTIQUES",
  "QM.VIVANT.CYCLES",
  "QM.VIVANT.CHAINES",
  "QM.VIVANT.PLANTES",
  "QM.VIVANT.CORPS",
  "QM.VIVANT.HYGIENE",
] as const;
