// Banque « VIVRE ENSEMBLE / EMC » - complement CM1 (cycle 3). S'AJOUTE a la
// banque EMC (CE2, 0058) dans la MEME matiere EMC, meme op serveur 'qm', meme
// table qm_item, meme verif_qm, meme <QuestionnerLeMonde>. Six sous-matieres
// CM1 (un domaine chacune, classe_min CM1) :
//   EMC.DROITS      droits_enfant       Convention des droits de l'enfant, droits/devoirs ;
//   EMC.SYMBOLES    symboles_republique drapeau, Marianne, devise, Marseillaise, 14 juillet ;
//   EMC.COOPERATION cooperation         s'entraider, ecouter, partager ;
//   EMC.EGALITE     egalite             egalite filles-garcons ;
//   EMC.PRUDENCE    prudence_ecrans     internet et ecrans : regles de prudence ;
//   EMC.ENGAGEMENT  engagement          delegues, associations, s'engager.
// Harcelement : TOUJOURS « en parler a un adulte de confiance ». Ton bienveillant,
// jamais moralisateur. Progression N1 (CM1) -> N4 (reponse libre).

import { type QmItem, tri } from "../qm/types";

export const BANQUE_EMC_CM1: QmItem[] = [
  // ===== EMC.DROITS =====
  { cle: "emc-dro-n1-a", competence: "EMC.DROITS", niveau: 1, format: "qcm",
    consigne: "Chaque enfant a des droits. As-tu le droit d'aller à...",
    options: ["l'école", "au travail à l'usine", "nulle part"], attendu: "l'école",
    explication: "Tous les enfants ont le droit d'aller à l'école pour apprendre." },
  { cle: "emc-dro-n1-b", competence: "EMC.DROITS", niveau: 1, format: "qcm",
    consigne: "Quel est un droit très important de chaque enfant ?",
    options: ["être protégé et aimé", "travailler toute la journée", "rester tout seul"], attendu: "être protégé et aimé",
    explication: "Chaque enfant a le droit d'être protégé, soigné et aimé." },
  { cle: "emc-dro-n2-a", competence: "EMC.DROITS", niveau: 2, format: "tri",
    consigne: "Range : est-ce un droit de l'enfant, ou pas ?",
    ...tri(["un droit de l'enfant", "pas un droit"], [["aller à l'école", "un droit de l'enfant"], ["être soigné quand on est malade", "un droit de l'enfant"], ["jouer et se reposer", "un droit de l'enfant"], ["faire tout ce qu'on veut sans règle", "pas un droit"]]),
    explication: "Aller à l'école, être soigné, jouer : ce sont des droits. Mais vivre sans aucune règle n'en est pas un." },
  { cle: "emc-dro-n2-b", competence: "EMC.DROITS", niveau: 2, format: "qcm",
    consigne: "Les droits de l'enfant sont écrits dans un grand texte signé par beaucoup de pays. C'est la...",
    options: ["Convention des droits de l'enfant", "liste des courses", "règle du foot"], attendu: "Convention des droits de l'enfant",
    explication: "La Convention des droits de l'enfant protège les enfants du monde entier." },
  { cle: "emc-dro-n3-a", competence: "EMC.DROITS", niveau: 3, format: "qcm",
    consigne: "Avoir des droits, c'est bien. Mais à l'école, il y a aussi des...",
    options: ["règles à respecter", "vacances tous les jours", "bonbons gratuits"], attendu: "règles à respecter",
    explication: "On a des droits et aussi des devoirs : respecter les règles et les autres." },
  { cle: "emc-dro-n3-b", competence: "EMC.DROITS", niveau: 3, format: "tri",
    consigne: "Range : est-ce plutôt un droit de l'enfant, ou un devoir de l'élève ?",
    ...tri(["un droit", "un devoir"], [["être soigné", "un droit"], ["aller à l'école", "un droit"], ["respecter les autres", "un devoir"], ["écouter en classe", "un devoir"]]),
    explication: "Être soigné et aller à l'école sont des droits. Respecter les autres et écouter sont des devoirs." },
  { cle: "emc-dro-n4-a", competence: "EMC.DROITS", niveau: 4, format: "texte",
    consigne: "Le grand texte qui protège tous les enfants du monde s'appelle la Convention des droits de l'... Écris le mot.",
    attendu: "enfant",
    explication: "La Convention des droits de l'enfant : elle protège chaque enfant." },
  { cle: "emc-dro-n4-b", competence: "EMC.DROITS", niveau: 4, format: "texte",
    consigne: "À l'école, chaque enfant a le droit d'apprendre et le devoir de respecter les... Écris le mot.",
    attendu: "autres",
    explication: "Respecter les autres, c'est un devoir qui permet de bien vivre ensemble." },
  // ===== EMC.SYMBOLES =====
  { cle: "emc-sym-n1-a", competence: "EMC.SYMBOLES", niveau: 1, format: "qcm",
    consigne: "De quelles couleurs est le drapeau de la France ?",
    options: ["bleu, blanc, rouge", "vert et jaune", "tout noir"], attendu: "bleu, blanc, rouge",
    explication: "Le drapeau français est bleu, blanc, rouge. On l'appelle le drapeau tricolore." },
  { cle: "emc-sym-n1-b", competence: "EMC.SYMBOLES", niveau: 1, format: "qcm",
    consigne: "Comment s'appelle la femme qui représente la République française ?",
    options: ["Marianne", "Cendrillon", "la fée Clochette"], attendu: "Marianne",
    explication: "Marianne, avec son bonnet, est un symbole de la République. On la voit dans les mairies." },
  { cle: "emc-sym-n2-a", competence: "EMC.SYMBOLES", niveau: 2, format: "qcm",
    consigne: "Quelle est la devise de la République française ?",
    options: ["Liberté, Égalité, Fraternité", "Toujours plus vite", "Chacun pour soi"], attendu: "Liberté, Égalité, Fraternité",
    explication: "La devise de la France est : Liberté, Égalité, Fraternité." },
  { cle: "emc-sym-n2-b", competence: "EMC.SYMBOLES", niveau: 2, format: "tri",
    consigne: "Range : est-ce un symbole de la République, ou pas ?",
    ...tri(["symbole de la République", "pas un symbole"], [["le drapeau tricolore", "symbole de la République"], ["Marianne", "symbole de la République"], ["la Marseillaise", "symbole de la République"], ["un ballon de foot", "pas un symbole"]]),
    explication: "Le drapeau, Marianne et la Marseillaise sont des symboles de la République. Le ballon, non." },
  { cle: "emc-sym-n3-a", competence: "EMC.SYMBOLES", niveau: 3, format: "qcm",
    consigne: "Comment s'appelle l'hymne, le chant de la France ?",
    options: ["la Marseillaise", "Au clair de la lune", "Joyeux anniversaire"], attendu: "la Marseillaise",
    explication: "La Marseillaise est l'hymne national, le chant de la France." },
  { cle: "emc-sym-n3-b", competence: "EMC.SYMBOLES", niveau: 3, format: "qcm",
    consigne: "Quel jour fête-t-on la fête nationale en France ?",
    options: ["le 14 juillet", "le 25 décembre", "le 1er avril"], attendu: "le 14 juillet",
    explication: "Le 14 juillet est la fête nationale française. Il y a souvent des feux d'artifice." },
  { cle: "emc-sym-n4-a", competence: "EMC.SYMBOLES", niveau: 4, format: "texte",
    consigne: "La devise de la France est : Liberté, Égalité et... Écris le mot.",
    attendu: "Fraternité",
    explication: "Liberté, Égalité, Fraternité : la fraternité, c'est s'entraider comme dans une famille." },
  { cle: "emc-sym-n4-b", competence: "EMC.SYMBOLES", niveau: 4, format: "texte",
    consigne: "Le chant officiel de la France, son hymne, s'appelle la... Écris le mot.",
    attendu: "Marseillaise",
    explication: "La Marseillaise : l'hymne national français." },
  // ===== EMC.COOPERATION =====
  { cle: "emc-coo-n1-a", competence: "EMC.COOPERATION", niveau: 1, format: "qcm",
    consigne: "Pour réussir un travail en groupe, le mieux est de...",
    options: ["s'entraider", "tout faire seul", "se disputer"], attendu: "s'entraider",
    explication: "En s'entraidant, on réussit mieux et on passe un bon moment ensemble." },
  { cle: "emc-coo-n1-b", competence: "EMC.COOPERATION", niveau: 1, format: "qcm",
    consigne: "Un camarade n'a pas compris l'exercice. Que peux-tu faire de gentil ?",
    options: ["lui expliquer calmement", "te moquer de lui", "partir en courant"], attendu: "lui expliquer calmement",
    explication: "Expliquer calmement à un camarade, c'est l'aider et être un bon copain." },
  { cle: "emc-coo-n2-a", competence: "EMC.COOPERATION", niveau: 2, format: "tri",
    consigne: "Range : est-ce que ça aide à bien coopérer, ou pas ?",
    ...tri(["ça aide", "ça n'aide pas"], [["écouter les idées des autres", "ça aide"], ["partager le matériel", "ça aide"], ["couper la parole", "ça n'aide pas"], ["vouloir tout décider seul", "ça n'aide pas"]]),
    explication: "Écouter et partager aident à coopérer. Couper la parole ou tout décider seul, non." },
  { cle: "emc-coo-n2-b", competence: "EMC.COOPERATION", niveau: 2, format: "qcm",
    consigne: "Dans un jeu d'équipe, quand on gagne tous ensemble, c'est grâce à la...",
    options: ["coopération", "chance seulement", "triche"], attendu: "coopération",
    explication: "La coopération, c'est unir ses efforts pour réussir ensemble." },
  { cle: "emc-coo-n3-a", competence: "EMC.COOPERATION", niveau: 3, format: "qcm",
    consigne: "Un camarade est tout seul dans la cour et semble triste. Tu peux...",
    options: ["l'inviter à jouer avec vous", "faire comme si tu ne voyais rien", "lui dire de partir"], attendu: "l'inviter à jouer avec vous",
    explication: "Inviter un camarade seul à jouer, c'est gentil et ça fait plaisir à tout le monde." },
  { cle: "emc-coo-n3-b", competence: "EMC.COOPERATION", niveau: 3, format: "qcm",
    consigne: "Si quelqu'un t'embête souvent à l'école, le plus important est d'...",
    options: ["en parler à un adulte de confiance", "garder ça pour toi tout seul", "te venger"], attendu: "en parler à un adulte de confiance",
    explication: "Quand quelqu'un t'embête, tu en parles à un adulte de confiance : il est là pour t'aider." },
  { cle: "emc-coo-n4-a", competence: "EMC.COOPERATION", niveau: 4, format: "texte",
    consigne: "Travailler ensemble en s'aidant les uns les autres, cela s'appelle la... Écris le mot.",
    attendu: "coopération",
    explication: "La coopération rend le travail plus facile et plus agréable." },
  { cle: "emc-coo-n4-b", competence: "EMC.COOPERATION", niveau: 4, format: "texte",
    consigne: "Si quelqu'un t'embête, tu en parles à un adulte de... Écris le mot.",
    attendu: "confiance",
    explication: "Un adulte de confiance, c'est un parent, un maître ou une maîtresse qui t'écoute et t'aide." },
  // ===== EMC.EGALITE =====
  { cle: "emc-ega-n1-a", competence: "EMC.EGALITE", niveau: 1, format: "qcm",
    consigne: "À l'école, les filles et les garçons ont...",
    options: ["les mêmes droits", "des droits différents", "aucun droit"], attendu: "les mêmes droits",
    explication: "Filles et garçons ont exactement les mêmes droits." },
  { cle: "emc-ega-n1-b", competence: "EMC.EGALITE", niveau: 1, format: "qcm",
    consigne: "Le football, c'est un jeu pour...",
    options: ["les filles et les garçons", "les garçons seulement", "personne"], attendu: "les filles et les garçons",
    explication: "Le football, comme tous les jeux, est pour les filles et les garçons." },
  { cle: "emc-ega-n2-a", competence: "EMC.EGALITE", niveau: 2, format: "tri",
    consigne: "Range : vrai ou faux pour l'égalité entre les filles et les garçons ?",
    ...tri(["vrai", "faux"], [["une fille peut devenir pompière", "vrai"], ["un garçon peut faire de la danse", "vrai"], ["seuls les garçons sont bons en maths", "faux"], ["seules les filles peuvent cuisiner", "faux"]]),
    explication: "Filles et garçons peuvent faire les mêmes activités et les mêmes métiers." },
  { cle: "emc-ega-n2-b", competence: "EMC.EGALITE", niveau: 2, format: "qcm",
    consigne: "Un métier comme médecin peut être fait par...",
    options: ["une femme ou un homme", "seulement un homme", "seulement une femme"], attendu: "une femme ou un homme",
    explication: "Tous les métiers peuvent être faits aussi bien par une femme que par un homme." },
  { cle: "emc-ega-n3-a", competence: "EMC.EGALITE", niveau: 3, format: "qcm",
    consigne: "Dans la cour, un jeu peut être joué par...",
    options: ["les filles comme les garçons", "les garçons d'abord", "les filles d'abord"], attendu: "les filles comme les garçons",
    explication: "Les jeux de la cour sont pour tout le monde, filles comme garçons." },
  { cle: "emc-ega-n3-b", competence: "EMC.EGALITE", niveau: 3, format: "tri",
    consigne: "Range chaque métier : pour les filles, pour les garçons, ou pour les deux ?",
    ...tri(["les filles", "les garçons", "les deux"], [["pilote d'avion", "les deux"], ["infirmier ou infirmière", "les deux"], ["maître ou maîtresse", "les deux"]]),
    explication: "Tous ces métiers sont pour les deux : filles et garçons peuvent les choisir." },
  { cle: "emc-ega-n4-a", competence: "EMC.EGALITE", niveau: 4, format: "texte",
    consigne: "Filles et garçons ont les mêmes droits : on parle d'... entre les filles et les garçons. Écris le mot.",
    attendu: "égalité",
    explication: "L'égalité : filles et garçons ont les mêmes droits et les mêmes chances." },
  { cle: "emc-ega-n4-b", competence: "EMC.EGALITE", niveau: 4, format: "texte",
    consigne: "Une femme peut faire le même métier qu'un... Écris le mot.",
    attendu: "homme",
    explication: "Une femme peut exercer le même métier qu'un homme : les métiers n'ont pas de genre." },
  // ===== EMC.PRUDENCE =====
  { cle: "emc-pru-n1-a", competence: "EMC.PRUDENCE", niveau: 1, format: "qcm",
    consigne: "Sur Internet, faut-il donner son adresse et son nom à un inconnu ?",
    options: ["non, jamais", "oui, toujours", "oui, s'il demande gentiment"], attendu: "non, jamais",
    explication: "On ne donne jamais ses informations personnelles à un inconnu sur Internet." },
  { cle: "emc-pru-n1-b", competence: "EMC.PRUDENCE", niveau: 1, format: "qcm",
    consigne: "Avant d'installer un jeu ou de cliquer sur un lien, le mieux est de...",
    options: ["demander à un adulte", "cliquer partout très vite", "donner son mot de passe"], attendu: "demander à un adulte",
    explication: "Demander à un adulte avant de cliquer, c'est le bon réflexe pour rester prudent." },
  { cle: "emc-pru-n2-a", competence: "EMC.PRUDENCE", niveau: 2, format: "tri",
    consigne: "Range : on garde pour soi, ou on peut partager en ligne ?",
    ...tri(["on garde pour soi", "on peut partager"], [["mon mot de passe", "on garde pour soi"], ["mon adresse", "on garde pour soi"], ["mon dessin préféré", "on peut partager"], ["mon jeu préféré", "on peut partager"]]),
    explication: "Le mot de passe et l'adresse restent secrets. On peut parler de ses goûts sans danger." },
  { cle: "emc-pru-n2-b", competence: "EMC.PRUDENCE", niveau: 2, format: "qcm",
    consigne: "Si on passe beaucoup de temps devant les écrans, c'est mieux de...",
    options: ["faire des pauses", "continuer toute la nuit", "ne jamais sortir"], attendu: "faire des pauses",
    explication: "Faire des pauses et bouger, c'est bon pour les yeux et pour le corps." },
  { cle: "emc-pru-n3-a", competence: "EMC.PRUDENCE", niveau: 3, format: "qcm",
    consigne: "Sur Internet, tout ce qui est écrit est-il toujours vrai ?",
    options: ["non, il faut vérifier", "oui, toujours", "oui, si c'est en couleur"], attendu: "non, il faut vérifier",
    explication: "Sur Internet, tout n'est pas vrai. On vérifie avec un adulte avant de croire." },
  { cle: "emc-pru-n3-b", competence: "EMC.PRUDENCE", niveau: 3, format: "qcm",
    consigne: "Si quelqu'un t'écrit des choses méchantes en ligne, tu dois...",
    options: ["en parler à un adulte de confiance", "répondre méchamment", "garder ça secret"], attendu: "en parler à un adulte de confiance",
    explication: "Face à des messages méchants, on en parle à un adulte de confiance qui pourra aider." },
  { cle: "emc-pru-n4-a", competence: "EMC.PRUDENCE", niveau: 4, format: "texte",
    consigne: "Sur Internet, on ne donne jamais son mot de... à un inconnu. Écris le mot.",
    attendu: "passe",
    explication: "Le mot de passe reste secret : c'est la clé de tes comptes." },
  { cle: "emc-pru-n4-b", competence: "EMC.PRUDENCE", niveau: 4, format: "texte",
    consigne: "Si quelqu'un t'embête en ligne, tu en parles à un adulte de... Écris le mot.",
    attendu: "confiance",
    explication: "Un adulte de confiance t'écoute et t'aide, même pour les soucis sur Internet." },
  // ===== EMC.ENGAGEMENT =====
  { cle: "emc-eng-n1-a", competence: "EMC.ENGAGEMENT", niveau: 1, format: "qcm",
    consigne: "Dans la classe, pour représenter les élèves, on choisit un...",
    options: ["délégué", "roi", "chef pour toujours"], attendu: "délégué",
    explication: "Le délégué représente les élèves de la classe et porte leurs idées." },
  { cle: "emc-eng-n1-b", competence: "EMC.ENGAGEMENT", niveau: 1, format: "qcm",
    consigne: "Comment choisit-on le délégué de la classe ?",
    options: ["on vote", "on prend le plus grand", "on prend le plus rapide"], attendu: "on vote",
    explication: "On vote : chaque élève donne sa voix pour choisir son délégué." },
  { cle: "emc-eng-n2-a", competence: "EMC.ENGAGEMENT", niveau: 2, format: "qcm",
    consigne: "Une association, c'est un groupe de personnes qui se réunissent pour...",
    options: ["aider ou faire une activité ensemble", "se disputer", "rester toutes seules"], attendu: "aider ou faire une activité ensemble",
    explication: "Dans une association, les gens se rassemblent pour aider ou partager une activité." },
  { cle: "emc-eng-n2-b", competence: "EMC.ENGAGEMENT", niveau: 2, format: "tri",
    consigne: "Range : est-ce s'engager pour les autres, ou pas ?",
    ...tri(["s'engager pour les autres", "non"], [["ramasser les déchets dans la cour", "s'engager pour les autres"], ["aider un camarade", "s'engager pour les autres"], ["ne penser qu'à soi", "non"], ["bousculer les autres", "non"]]),
    explication: "Ramasser les déchets ou aider un camarade, c'est s'engager. Ne penser qu'à soi, non." },
  { cle: "emc-eng-n3-a", competence: "EMC.ENGAGEMENT", niveau: 3, format: "qcm",
    consigne: "À quoi sert le délégué de classe ?",
    options: ["porter la voix des élèves", "commander tout le monde", "faire les devoirs des autres"], attendu: "porter la voix des élèves",
    explication: "Le délégué écoute les élèves et porte leurs idées auprès des adultes." },
  { cle: "emc-eng-n3-b", competence: "EMC.ENGAGEMENT", niveau: 3, format: "qcm",
    consigne: "Participer à une association qui aide les gens, c'est...",
    options: ["s'engager", "s'ennuyer", "se cacher"], attendu: "s'engager",
    explication: "S'engager, c'est donner un peu de son temps pour aider les autres." },
  { cle: "emc-eng-n4-a", competence: "EMC.ENGAGEMENT", niveau: 4, format: "texte",
    consigne: "L'élève élu pour représenter sa classe s'appelle le... Écris le mot.",
    attendu: "délégué",
    explication: "Le délégué de classe représente ses camarades." },
  { cle: "emc-eng-n4-b", competence: "EMC.ENGAGEMENT", niveau: 4, format: "texte",
    consigne: "Pour choisir le délégué, chaque élève donne sa voix : on... Écris le verbe (on ...).",
    attendu: "vote",
    explication: "On vote : c'est ainsi qu'on choisit ses représentants, comme les grands." },
];

export const COMPETENCES_EMC_CM1 = [
  "EMC.DROITS",
  "EMC.SYMBOLES",
  "EMC.COOPERATION",
  "EMC.EGALITE",
  "EMC.PRUDENCE",
  "EMC.ENGAGEMENT",
] as const;
