// Banque « BIEN UTILISER LES ECRANS ET INTERNET » (Vivre ensemble / EMC, CE2,
// cycle 2). Sous-matiere, domaine dedie `ecrans` :
//   EMC.ECRANS.TEMPS          le temps d'ecran (ne pas rester trop longtemps) ;
//   EMC.ECRANS.DONNEES        ne pas donner ses informations personnelles,
//                             demander a un adulte ;
//   EMC.ECRANS.POLITESSE      etre poli en ligne (comme dans la vraie vie) ;
//   EMC.ECRANS.ESPRITCRITIQUE ne pas croire tout ce qu'on voit.
//
// FORMAT : petites SITUATIONS concretes du quotidien avec les ecrans. Ton
// bienveillant : les ecrans ne sont pas « mauvais », on apprend a bien les
// utiliser et a demander a un adulte en cas de doute. Le SERVEUR (verif_qm, op
// 'qm') reste seul juge via la cle.

import { type QmItem, tri } from "../qm/types";

export const BANQUE_ECRANS: QmItem[] = [
  // =======================================================================
  // EMC.ECRANS.TEMPS — le temps d'ecran
  // =======================================================================
  { cle: "emc-ecr-tps-n1-a", competence: "EMC.ECRANS.TEMPS", niveau: 1, format: "qcm",
    consigne: "Tu as joué très longtemps à la tablette et tu as mal aux yeux. Que fais-tu ?",
    options: ["je fais une pause", "je continue encore des heures"], attendu: "je fais une pause",
    explication: "On fait une pause quand les yeux fatiguent. Les écrans, c'est bien, mais pas trop longtemps." },
  { cle: "emc-ecr-tps-n1-b", competence: "EMC.ECRANS.TEMPS", niveau: 1, format: "qcm",
    consigne: "Le soir, juste avant de dormir, qu'est-ce qui est mieux ?",
    options: ["éteindre les écrans", "regarder un écran dans le noir"], attendu: "éteindre les écrans",
    explication: "On éteint les écrans avant de dormir : on s'endort mieux et on est en forme le lendemain." },
  { cle: "emc-ecr-tps-n2-a", competence: "EMC.ECRANS.TEMPS", niveau: 2, format: "qcm",
    consigne: "Il fait beau dehors et tes amis t'appellent pour jouer. Que choisis-tu ?",
    options: ["aller jouer dehors", "rester toute la journée devant l'écran", "refuser de bouger"],
    attendu: "aller jouer dehors",
    explication: "Jouer dehors fait du bien au corps. L'écran peut attendre un autre moment." },
  { cle: "emc-ecr-tps-n2-b", competence: "EMC.ECRANS.TEMPS", niveau: 2, format: "tri",
    consigne: "Classe chaque activité : avec un écran, ou sans écran ?",
    ...tri(["avec écran", "sans écran"], [
      ["regarder un dessin animé", "avec écran"],
      ["jouer à un jeu vidéo", "avec écran"],
      ["faire du vélo", "sans écran"],
      ["lire un livre", "sans écran"],
    ]),
    explication: "Il y a des activités avec écran et beaucoup sans écran. C'est bien de varier." },
  { cle: "emc-ecr-tps-n3-a", competence: "EMC.ECRANS.TEMPS", niveau: 3, format: "qcm",
    consigne: "Pourquoi vaut-il mieux ne pas passer trop de temps devant les écrans ?",
    options: ["pour bouger, dormir et voir ses amis aussi", "parce que c'est interdit partout", "pour s'ennuyer"],
    attendu: "pour bouger, dormir et voir ses amis aussi",
    explication: "Trop d'écran laisse moins de temps pour bouger, dormir et voir ses amis. On équilibre." },
  { cle: "emc-ecr-tps-n3-b", competence: "EMC.ECRANS.TEMPS", niveau: 3, format: "qcm",
    consigne: "Qui peut t'aider à décider combien de temps tu passes devant l'écran ?",
    options: ["un adulte, un parent", "personne, je décide seul", "l'écran lui-même"],
    attendu: "un adulte, un parent",
    explication: "Un adulte t'aide à choisir un bon temps d'écran. On peut en parler ensemble." },
  { cle: "emc-ecr-tps-n4-a", competence: "EMC.ECRANS.TEMPS", niveau: 4, format: "texte",
    consigne: "Quand les yeux fatiguent devant l'écran, on fait une... Écris le mot (pause).",
    attendu: "pause",
    explication: "On fait une pause pour reposer les yeux et le corps." },
  { cle: "emc-ecr-tps-n4-b", competence: "EMC.ECRANS.TEMPS", niveau: 4, format: "texte",
    consigne: "Le soir, avant de dormir, on doit... les écrans. Écris le mot (éteindre).",
    attendu: "éteindre",
    explication: "On éteint les écrans avant de dormir pour bien se reposer." },

  // =======================================================================
  // EMC.ECRANS.DONNEES — proteger ses informations, demander a un adulte
  // =======================================================================
  { cle: "emc-ecr-don-n1-a", competence: "EMC.ECRANS.DONNEES", niveau: 1, format: "qcm",
    consigne: "Sur Internet, un jeu te demande ton adresse et ton école. Que fais-tu ?",
    options: ["je ne donne pas et je préviens un adulte", "je donne tout de suite"],
    attendu: "je ne donne pas et je préviens un adulte",
    explication: "On ne donne pas ses informations personnelles. On prévient un adulte en cas de doute." },
  { cle: "emc-ecr-don-n1-b", competence: "EMC.ECRANS.DONNEES", niveau: 1, format: "qcm",
    consigne: "Un mot de passe, est-ce qu'on le donne à n'importe qui ?",
    options: ["non, c'est un secret", "oui, à tout le monde"], attendu: "non, c'est un secret",
    explication: "Un mot de passe reste secret. On le garde pour soi, comme la clé de la maison." },
  { cle: "emc-ecr-don-n2-a", competence: "EMC.ECRANS.DONNEES", niveau: 2, format: "tri",
    consigne: "Classe : est-ce qu'on peut donner cette information sur Internet, ou pas ?",
    ...tri(["on garde pour soi", "on peut dire"], [
      ["mon adresse", "on garde pour soi"],
      ["mon mot de passe", "on garde pour soi"],
      ["mon dessin animé préféré", "on peut dire"],
      ["ma couleur préférée", "on peut dire"],
    ]),
    explication: "On garde pour soi l'adresse et le mot de passe. On peut parler de ses goûts sans danger." },
  { cle: "emc-ecr-don-n2-b", competence: "EMC.ECRANS.DONNEES", niveau: 2, format: "qcm",
    consigne: "Une personne inconnue t'écrit sur un jeu et veut te rencontrer. Que fais-tu ?",
    options: ["je préviens tout de suite un adulte", "j'accepte le rendez-vous", "je donne mon adresse"],
    attendu: "je préviens tout de suite un adulte",
    explication: "On prévient un adulte quand un inconnu insiste. Un adulte de confiance saura quoi faire." },
  { cle: "emc-ecr-don-n3-a", competence: "EMC.ECRANS.DONNEES", niveau: 3, format: "qcm",
    consigne: "Pourquoi ne faut-il pas donner son adresse à un inconnu sur Internet ?",
    options: ["pour rester en sécurité", "parce que c'est rigolo", "pour gagner un cadeau"],
    attendu: "pour rester en sécurité",
    explication: "On protège ses informations pour rester en sécurité. En cas de doute, on demande à un adulte." },
  { cle: "emc-ecr-don-n3-b", competence: "EMC.ECRANS.DONNEES", niveau: 3, format: "qcm",
    consigne: "Tu vois quelque chose qui te gêne sur un écran. Que fais-tu ?",
    options: ["j'en parle à un adulte de confiance", "je garde ça pour moi", "je clique partout"],
    attendu: "j'en parle à un adulte de confiance",
    explication: "Quand quelque chose te gêne sur un écran, tu en parles à un adulte de confiance. Il t'aidera." },
  { cle: "emc-ecr-don-n4-a", competence: "EMC.ECRANS.DONNEES", niveau: 4, format: "texte",
    consigne: "Sur Internet, en cas de doute, on demande toujours à un... Écris le mot (adulte).",
    attendu: "adulte",
    explication: "En cas de doute sur Internet, on demande à un adulte de confiance." },
  { cle: "emc-ecr-don-n4-b", competence: "EMC.ECRANS.DONNEES", niveau: 4, format: "texte",
    consigne: "On ne donne jamais son mot de passe : il reste... Écris le mot (secret).",
    attendu: "secret",
    explication: "Le mot de passe reste secret : on le garde pour soi." },

  // =======================================================================
  // EMC.ECRANS.POLITESSE — etre poli en ligne
  // =======================================================================
  { cle: "emc-ecr-pol-n1-a", competence: "EMC.ECRANS.POLITESSE", niveau: 1, format: "qcm",
    consigne: "Quand tu écris un message à un ami, comment lui parles-tu ?",
    options: ["gentiment, comme en vrai", "méchamment"], attendu: "gentiment, comme en vrai",
    explication: "On reste poli et gentil dans les messages, exactement comme quand on se parle en vrai." },
  { cle: "emc-ecr-pol-n1-b", competence: "EMC.ECRANS.POLITESSE", niveau: 1, format: "qcm",
    consigne: "Écrire en MAJUSCULES et avec des gros mots, qu'est-ce que ça fait ?",
    options: ["ça fait de la peine", "ça fait plaisir"], attendu: "ça fait de la peine",
    explication: "Écrire méchamment fait de la peine. Même derrière un écran, on reste poli." },
  { cle: "emc-ecr-pol-n2-a", competence: "EMC.ECRANS.POLITESSE", niveau: 2, format: "qcm",
    consigne: "Dans un jeu en ligne, quelqu'un insulte un autre joueur. Que fais-tu ?",
    options: ["je reste poli et je préviens un adulte", "j'insulte encore plus", "je ris et je continue"],
    attendu: "je reste poli et je préviens un adulte",
    explication: "On ne participe pas aux insultes : on reste poli et on prévient un adulte si ça continue." },
  { cle: "emc-ecr-pol-n2-b", competence: "EMC.ECRANS.POLITESSE", niveau: 2, format: "tri",
    consigne: "Classe chaque message : poli, ou pas poli ?",
    ...tri(["message poli", "pas poli"], [
      ["bonjour, tu veux jouer avec moi ?", "message poli"],
      ["merci beaucoup pour ton aide", "message poli"],
      ["tu es nul, va-t'en", "pas poli"],
      ["tais-toi espèce de bête", "pas poli"],
    ]),
    explication: "On écrit des messages gentils. Les insultes font de la peine, même par écran." },
  { cle: "emc-ecr-pol-n3-a", competence: "EMC.ECRANS.POLITESSE", niveau: 3, format: "qcm",
    consigne: "Pourquoi faut-il être poli dans les messages, comme dans la vraie vie ?",
    options: ["parce qu'une vraie personne les lit", "parce que personne ne les lit", "pour gagner des points"],
    attendu: "parce qu'une vraie personne les lit",
    explication: "Derrière l'écran, il y a une vraie personne qui a des émotions. On reste poli avec elle." },
  { cle: "emc-ecr-pol-n3-b", competence: "EMC.ECRANS.POLITESSE", niveau: 3, format: "qcm",
    consigne: "Un camarade reçoit des messages méchants. On appelle ça...",
    options: ["du harcèlement, il faut en parler à un adulte", "une blague à continuer", "un jeu normal"],
    attendu: "du harcèlement, il faut en parler à un adulte",
    explication: "Des messages méchants qui se répètent, c'est du harcèlement. On en parle à un adulte de confiance." },
  { cle: "emc-ecr-pol-n4-a", competence: "EMC.ECRANS.POLITESSE", niveau: 4, format: "texte",
    consigne: "Derrière chaque message, il y a une vraie... qui a des émotions. Écris le mot (personne).",
    attendu: "personne",
    explication: "Derrière l'écran, il y a une vraie personne : on reste poli avec elle." },
  { cle: "emc-ecr-pol-n4-b", competence: "EMC.ECRANS.POLITESSE", niveau: 4, format: "texte",
    consigne: "Même sur un écran, pour bien écrire aux autres, on reste... Écris le mot (poli).",
    attendu: "poli",
    explication: "On reste poli en ligne, comme dans la vraie vie." },

  // =======================================================================
  // EMC.ECRANS.ESPRITCRITIQUE — ne pas croire tout ce qu'on voit
  // =======================================================================
  { cle: "emc-ecr-cri-n1-a", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 1, format: "qcm",
    consigne: "Sur Internet, tout ce qu'on voit est-il toujours vrai ?",
    options: ["non, pas toujours", "oui, tout est vrai"], attendu: "non, pas toujours",
    explication: "Sur Internet, tout n'est pas vrai. On réfléchit avant de croire ce qu'on voit." },
  { cle: "emc-ecr-cri-n1-b", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 1, format: "qcm",
    consigne: "Une vidéo dit une chose bizarre et tu ne sais pas si c'est vrai. Que fais-tu ?",
    options: ["je demande à un adulte", "je crois tout de suite"], attendu: "je demande à un adulte",
    explication: "Quand on doute, on demande à un adulte. Il aide à savoir si c'est vrai." },
  { cle: "emc-ecr-cri-n2-a", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 2, format: "qcm",
    consigne: "Une image montre un chat aussi grand qu'une maison. Qu'en penses-tu ?",
    options: ["c'est sûrement truqué", "c'est forcément vrai", "les chats sont géants"],
    attendu: "c'est sûrement truqué",
    explication: "Une image peut être truquée avec un ordinateur. Un chat géant, ça n'existe pas pour de vrai." },
  { cle: "emc-ecr-cri-n2-b", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 2, format: "tri",
    consigne: "Classe : c'est possible pour de vrai, ou c'est sûrement truqué ?",
    ...tri(["possible", "sûrement truqué"], [
      ["un chien qui court dans un jardin", "possible"],
      ["un enfant qui mange une glace", "possible"],
      ["une voiture qui vole dans le ciel", "sûrement truqué"],
      ["une personne plus grande qu'un immeuble", "sûrement truqué"],
    ]),
    explication: "Certaines images sont possibles, d'autres sont truquées. On réfléchit avant de croire." },
  { cle: "emc-ecr-cri-n3-a", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 3, format: "qcm",
    consigne: "Comment savoir si une information vue sur Internet est vraie ?",
    options: ["en vérifiant avec un adulte ou un livre sérieux", "en la croyant tout de suite", "en la partageant vite"],
    attendu: "en vérifiant avec un adulte ou un livre sérieux",
    explication: "On vérifie une information avec un adulte ou une source sérieuse avant de la croire." },
  { cle: "emc-ecr-cri-n3-b", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 3, format: "qcm",
    consigne: "Un message dit « partage vite ou il t'arrivera malheur ». Que fais-tu ?",
    options: ["je ne le crois pas et j'en parle à un adulte", "je le partage à tout le monde", "j'ai très peur et j'obéis"],
    attendu: "je ne le crois pas et j'en parle à un adulte",
    explication: "Ces messages qui font peur sont faux. On ne les partage pas et on en parle à un adulte." },
  { cle: "emc-ecr-cri-n4-a", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 4, format: "texte",
    consigne: "Sur Internet, il ne faut pas tout... ce qu'on voit. Écris le mot (croire).",
    attendu: "croire",
    explication: "On ne croit pas tout sur Internet : on réfléchit et on vérifie." },
  { cle: "emc-ecr-cri-n4-b", competence: "EMC.ECRANS.ESPRITCRITIQUE", niveau: 4, format: "texte",
    consigne: "Avant de croire une information, il vaut mieux la... Écris le mot (vérifier).",
    attendu: "vérifier",
    explication: "On vérifie une information avant de la croire, avec un adulte ou un livre sérieux." },
];

export const COMPETENCES_ECRANS = [
  "EMC.ECRANS.TEMPS",
  "EMC.ECRANS.DONNEES",
  "EMC.ECRANS.POLITESSE",
  "EMC.ECRANS.ESPRITCRITIQUE",
] as const;
