// Banque « DROITS ET DEVOIRS, LA REPUBLIQUE » (Vivre ensemble / EMC, CE2,
// cycle 2). Sous-matiere, domaine dedie `republique` :
//   EMC.REPUBLIQUE.DROITS    droits de l'enfant (simplement) et devoirs a l'ecole ;
//   EMC.REPUBLIQUE.SYMBOLES  symboles de la Republique (drapeau, Marianne,
//                            devise, hymne, 14 juillet) ;
//   EMC.REPUBLIQUE.COMMUNE   la commune et le maire ;
//   EMC.REPUBLIQUE.VOTER     voter pour choisir (election de delegues).
//
// CONTENUS NEUTRES politiquement : uniquement les institutions et les valeurs
// OFFICIELLES du programme. Ton bienveillant, jamais militant. Le SERVEUR
// (verif_qm, op 'qm') reste seul juge via la cle.

import { type QmItem, ordre, tri } from "../qm/types";

export const BANQUE_REPUBLIQUE: QmItem[] = [
  // =======================================================================
  // EMC.REPUBLIQUE.DROITS — droits de l'enfant et devoirs a l'ecole
  // =======================================================================
  { cle: "emc-rep-dro-n1-a", competence: "EMC.REPUBLIQUE.DROITS", niveau: 1, format: "qcm",
    consigne: "Tous les enfants ont le droit d'aller à...",
    options: ["l'école", "la guerre"], attendu: "l'école",
    explication: "Tous les enfants ont le droit d'aller à l'école pour apprendre." },
  { cle: "emc-rep-dro-n1-b", competence: "EMC.REPUBLIQUE.DROITS", niveau: 1, format: "qcm",
    consigne: "À l'école, c'est un devoir de...",
    options: ["respecter les autres", "embêter les autres"], attendu: "respecter les autres",
    explication: "Respecter les autres est un devoir : cela permet à chacun d'être bien à l'école." },
  { cle: "emc-rep-dro-n2-a", competence: "EMC.REPUBLIQUE.DROITS", niveau: 2, format: "tri",
    consigne: "Classe chaque phrase : c'est un droit de l'enfant, ou un devoir à l'école ?",
    ...tri(["un droit", "un devoir"], [
      ["être soigné quand on est malade", "un droit"],
      ["jouer et se reposer", "un droit"],
      ["écouter et faire son travail", "un devoir"],
      ["respecter le matériel", "un devoir"],
    ]),
    explication: "On a des droits (être soigné, jouer) et des devoirs (travailler, respecter le matériel)." },
  { cle: "emc-rep-dro-n2-b", competence: "EMC.REPUBLIQUE.DROITS", niveau: 2, format: "qcm",
    consigne: "Un enfant a surtout besoin de quoi pour grandir ?",
    options: ["être protégé et aller à l'école", "travailler toute la journée", "rester seul"],
    attendu: "être protégé et aller à l'école",
    explication: "Les enfants ont le droit d'être protégés, soignés et d'aller à l'école." },
  { cle: "emc-rep-dro-n3-a", competence: "EMC.REPUBLIQUE.DROITS", niveau: 3, format: "qcm",
    consigne: "Tu as le droit de jouer. Mais en classe, quel est ton devoir ?",
    options: ["faire mon travail et écouter", "jouer tout le temps", "parler sans arrêt"],
    attendu: "faire mon travail et écouter",
    explication: "On a le droit de jouer à la récré, et le devoir de travailler en classe. Droits et devoirs vont ensemble." },
  { cle: "emc-rep-dro-n3-b", competence: "EMC.REPUBLIQUE.DROITS", niveau: 3, format: "qcm",
    consigne: "Pourquoi l'école est-elle importante pour les enfants ?",
    options: ["pour apprendre et grandir ensemble", "pour rester enfermé", "pour s'ennuyer"],
    attendu: "pour apprendre et grandir ensemble",
    explication: "L'école aide à apprendre, à comprendre le monde et à vivre avec les autres." },
  { cle: "emc-rep-dro-n4-a", competence: "EMC.REPUBLIQUE.DROITS", niveau: 4, format: "texte",
    consigne: "Tous les enfants ont le droit d'aller à l'... pour apprendre. Écris le mot.",
    attendu: "école",
    explication: "Aller à l'école est un droit pour tous les enfants." },
  { cle: "emc-rep-dro-n4-b", competence: "EMC.REPUBLIQUE.DROITS", niveau: 4, format: "texte",
    consigne: "En classe, faire son travail et respecter les autres, c'est un... Écris le mot (devoir).",
    attendu: "devoir",
    explication: "Faire son travail et respecter les autres sont des devoirs de l'élève." },

  // =======================================================================
  // EMC.REPUBLIQUE.SYMBOLES — drapeau, Marianne, devise, hymne, 14 juillet
  // =======================================================================
  { cle: "emc-rep-sym-n1-a", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 1, format: "qcm",
    consigne: "De quelles couleurs est le drapeau français ?",
    options: ["bleu, blanc, rouge", "vert, jaune, rouge"], attendu: "bleu, blanc, rouge",
    explication: "Le drapeau français est bleu, blanc et rouge. On le voit sur les mairies." },
  { cle: "emc-rep-sym-n1-b", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 1, format: "qcm",
    consigne: "Comment s'appelle l'hymne de la France, le chant de la République ?",
    options: ["la Marseillaise", "Au clair de la lune"], attendu: "la Marseillaise",
    explication: "L'hymne national s'appelle la Marseillaise. On l'entend lors des grandes occasions." },
  { cle: "emc-rep-sym-n2-a", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 2, format: "qcm",
    consigne: "Quelle est la devise de la République française ?",
    options: ["Liberté, Égalité, Fraternité", "Un pour tous, tous pour un", "Toujours plus haut"],
    attendu: "Liberté, Égalité, Fraternité",
    explication: "La devise de la France est : Liberté, Égalité, Fraternité. On la lit sur les mairies." },
  { cle: "emc-rep-sym-n2-b", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 2, format: "tri",
    consigne: "Classe : est-ce un symbole de la République, ou non ?",
    ...tri(["symbole de la République", "pas un symbole"], [
      ["le drapeau bleu blanc rouge", "symbole de la République"],
      ["Marianne", "symbole de la République"],
      ["la Marseillaise", "symbole de la République"],
      ["une paire de baskets", "pas un symbole"],
    ]),
    explication: "Le drapeau, Marianne et la Marseillaise sont des symboles de la République." },
  { cle: "emc-rep-sym-n3-a", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 3, format: "qcm",
    consigne: "Quelle est la grande fête nationale de la France ?",
    options: ["le 14 juillet", "le 25 décembre", "le 1er avril"], attendu: "le 14 juillet",
    explication: "Le 14 juillet est la fête nationale. Il y a souvent un défilé et des feux d'artifice." },
  { cle: "emc-rep-sym-n3-b", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 3, format: "qcm",
    consigne: "Marianne est un symbole de la République. Que représente-t-elle ?",
    options: ["la France et ses valeurs", "une chanteuse connue", "une marque de bonbons"],
    attendu: "la France et ses valeurs",
    explication: "Marianne représente la République française et ses valeurs. Son buste est souvent dans les mairies." },
  { cle: "emc-rep-sym-n4-a", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 4, format: "texte",
    consigne: "Le chant de la République française s'appelle la... Écris le mot (Marseillaise).",
    attendu: "Marseillaise",
    explication: "L'hymne national s'appelle la Marseillaise." },
  { cle: "emc-rep-sym-n4-b", competence: "EMC.REPUBLIQUE.SYMBOLES", niveau: 4, format: "texte",
    consigne: "Le premier mot de la devise « ..., Égalité, Fraternité ». Écris le mot (Liberté).",
    attendu: "Liberté",
    explication: "La devise de la France est : Liberté, Égalité, Fraternité." },

  // =======================================================================
  // EMC.REPUBLIQUE.COMMUNE — la commune et le maire
  // =======================================================================
  { cle: "emc-rep-com-n1-a", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 1, format: "qcm",
    consigne: "Comment s'appelle la personne qui dirige une commune, un village ou une ville ?",
    options: ["le maire", "le facteur"], attendu: "le maire",
    explication: "Le maire dirige la commune. Il travaille à la mairie." },
  { cle: "emc-rep-com-n1-b", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 1, format: "qcm",
    consigne: "Où travaille le maire ?",
    options: ["à la mairie", "à la piscine"], attendu: "à la mairie",
    explication: "Le maire travaille à la mairie, la maison commune du village ou de la ville." },
  { cle: "emc-rep-com-n2-a", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 2, format: "qcm",
    consigne: "Une commune, c'est...",
    options: ["un village ou une ville", "un pays entier", "une seule maison"],
    attendu: "un village ou une ville",
    explication: "Une commune est un village ou une ville. Chaque commune a un maire et une mairie." },
  { cle: "emc-rep-com-n2-b", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 2, format: "tri",
    consigne: "Classe : qui s'en occupe dans la commune, le maire, ou pas le maire ?",
    ...tri(["le maire s'en occupe", "pas le maire"], [
      ["construire une nouvelle école", "le maire s'en occupe"],
      ["organiser la fête du village", "le maire s'en occupe"],
      ["choisir tes vêtements", "pas le maire"],
      ["faire tes devoirs", "pas le maire"],
    ]),
    explication: "Le maire s'occupe de la commune : les écoles, les fêtes, les routes. Pas de ta vie à la maison." },
  { cle: "emc-rep-com-n3-a", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 3, format: "qcm",
    consigne: "À quoi sert la mairie de ta commune ?",
    options: ["s'occuper de l'école, des routes et des fêtes", "vendre des jouets", "garder les animaux"],
    attendu: "s'occuper de l'école, des routes et des fêtes",
    explication: "La mairie s'occupe de la vie de la commune : les écoles, les routes, les fêtes, l'état civil." },
  { cle: "emc-rep-com-n3-b", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 3, format: "qcm",
    consigne: "Comment devient-on maire d'une commune ?",
    options: ["on est élu par un vote", "on est le plus grand", "on paie pour l'être"],
    attendu: "on est élu par un vote",
    explication: "Le maire est élu grâce à un vote. Les habitants choisissent qui dirige la commune." },
  { cle: "emc-rep-com-n4-a", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 4, format: "texte",
    consigne: "La personne qui dirige la commune s'appelle le... Écris le mot (maire).",
    attendu: "maire",
    explication: "Le maire dirige la commune et travaille à la mairie." },
  { cle: "emc-rep-com-n4-b", competence: "EMC.REPUBLIQUE.COMMUNE", niveau: 4, format: "texte",
    consigne: "Le maire travaille dans un bâtiment qui s'appelle la... Écris le mot (mairie).",
    attendu: "mairie",
    explication: "La mairie est la maison commune où travaille le maire." },

  // =======================================================================
  // EMC.REPUBLIQUE.VOTER — voter pour choisir (election de delegues)
  // =======================================================================
  { cle: "emc-rep-vot-n1-a", competence: "EMC.REPUBLIQUE.VOTER", niveau: 1, format: "qcm",
    consigne: "La classe doit choisir un délégué. Comment fait-on, c'est le plus juste ?",
    options: ["on vote", "on se bagarre"], attendu: "on vote",
    explication: "On vote : chacun choisit. C'est la façon la plus juste de décider ensemble." },
  { cle: "emc-rep-vot-n1-b", competence: "EMC.REPUBLIQUE.VOTER", niveau: 1, format: "qcm",
    consigne: "Quand on vote, combien de voix a chaque enfant ?",
    options: ["une voix chacun", "dix voix pour le plus fort"], attendu: "une voix chacun",
    explication: "Chaque enfant a une seule voix : tout le monde est égal devant le vote." },
  { cle: "emc-rep-vot-n2-a", competence: "EMC.REPUBLIQUE.VOTER", niveau: 2, format: "qcm",
    consigne: "C'est l'élection du délégué. Qui est choisi ?",
    options: ["celui qui a le plus de voix", "celui qui crie le plus", "le plus grand de la classe"],
    attendu: "celui qui a le plus de voix",
    explication: "On compte les voix : celui qui en a le plus est élu délégué. Chacun a voté." },
  { cle: "emc-rep-vot-n2-b", competence: "EMC.REPUBLIQUE.VOTER", niveau: 2, format: "ordre",
    consigne: "Range dans l'ordre les étapes d'une élection de délégué.",
    ...ordre(["on présente les candidats", "chacun vote", "on compte les voix"]),
    explication: "D'abord les candidats se présentent, puis chacun vote, puis on compte les voix." },
  { cle: "emc-rep-vot-n3-a", competence: "EMC.REPUBLIQUE.VOTER", niveau: 3, format: "qcm",
    consigne: "À quoi sert le délégué de la classe ?",
    options: ["parler au nom des élèves", "commander tout le monde", "corriger les cahiers"],
    attendu: "parler au nom des élèves",
    explication: "Le délégué représente la classe : il parle au nom des élèves pour donner leurs idées." },
  { cle: "emc-rep-vot-n3-b", competence: "EMC.REPUBLIQUE.VOTER", niveau: 3, format: "qcm",
    consigne: "Pourquoi le vote est-il secret ?",
    options: ["pour que chacun choisisse librement", "pour cacher des choses", "pour tricher"],
    attendu: "pour que chacun choisisse librement",
    explication: "Le vote est secret pour que chacun choisisse en toute liberté, sans être influencé." },
  { cle: "emc-rep-vot-n4-a", competence: "EMC.REPUBLIQUE.VOTER", niveau: 4, format: "texte",
    consigne: "Pour choisir un délégué de façon juste, la classe doit... Écris le mot (voter).",
    attendu: "voter",
    explication: "On vote pour choisir : c'est la façon juste de décider ensemble." },
  { cle: "emc-rep-vot-n4-b", competence: "EMC.REPUBLIQUE.VOTER", niveau: 4, format: "texte",
    consigne: "L'élève élu qui parle au nom de la classe s'appelle le... Écris le mot (délégué).",
    attendu: "délégué",
    explication: "Le délégué est élu par la classe pour la représenter." },
];

export const COMPETENCES_REPUBLIQUE = [
  "EMC.REPUBLIQUE.DROITS",
  "EMC.REPUBLIQUE.SYMBOLES",
  "EMC.REPUBLIQUE.COMMUNE",
  "EMC.REPUBLIQUE.VOTER",
] as const;
