// Banque « GEOGRAPHIE » (CM1, cycle 3). Nouvelle MATIERE (GEO), rendue par
// <QuestionnerLeMonde> et jugee par le SERVEUR (op 'qm', qm_item, verif_qm).
// Six sous-matieres, alignees sur les 3 themes CM1 d'eduscol + reperes France :
//   GEO.REPERES    se reperer : plan, carte, legende, points cardinaux ;
//   GEO.HABITER    se loger : ville / campagne, metropole, Paris ;
//   GEO.ACTIVITES  travailler, se cultiver, loisirs et tourisme ;
//   GEO.CONSOMMER  eau, energie, alimentation (circuits, chateau d'eau) ;
//   GEO.FRANCE     fleuves, reliefs, mers et ocean de la France ;
//   GEO.PAYSAGES   reconnaitre des paysages (foret, mer, montagne, ville).
// Les « regions » (decoupage administratif) sont transversales au cycle 3, pas
// une lecon dediee de CM1 : on en reste a la localisation. Progression N1 (CM1
// d'emblee) -> N4 (reponse libre). Consignes pour l'oral, exemple concret.
// Carte interactive Natural Earth (clic) : evolution UI differee (cf. docs).

import { type QmItem, tri } from "../qm/types";

export const BANQUE_GEOGRAPHIE: QmItem[] = [
  // ===== GEO.REPERES =====
  { cle: "ge-rep-n1-a", competence: "GEO.REPERES", niveau: 1, format: "qcm",
    consigne: "Pour montrer où sont les rues d'une ville, on utilise un...",
    options: ["plan", "livre de cuisine", "dessin animé"], attendu: "plan",
    explication: "Un plan montre les rues et les bâtiments vus de dessus. Il aide à se repérer." },
  { cle: "ge-rep-n1-b", competence: "GEO.REPERES", niveau: 1, format: "qcm",
    consigne: "Sur une carte, le petit cadre qui explique les dessins et les couleurs s'appelle la...",
    options: ["légende", "télévision", "récré"], attendu: "légende",
    explication: "La légende explique ce que veulent dire les couleurs et les symboles de la carte." },
  { cle: "ge-rep-n2-a", competence: "GEO.REPERES", niveau: 2, format: "qcm",
    consigne: "Sur une carte, quel point cardinal est tout en haut, en général ?",
    options: ["le nord", "le sud", "l'ouest"], attendu: "le nord",
    explication: "Sur la plupart des cartes, le nord est placé en haut. La boussole aide à le trouver." },
  { cle: "ge-rep-n2-b", competence: "GEO.REPERES", niveau: 2, format: "qcm",
    consigne: "Si le nord est en haut d'une carte, qu'y a-t-il tout en bas ?",
    options: ["le sud", "l'est", "l'ouest"], attendu: "le sud",
    explication: "Si le nord est en haut, le sud est en bas, l'est à droite et l'ouest à gauche." },
  { cle: "ge-rep-n3-a", competence: "GEO.REPERES", niveau: 3, format: "tri",
    consigne: "Range chaque chose : élément d'une carte, ou pas ?",
    ...tri(["sur une carte", "pas sur une carte"], [["la légende", "sur une carte"], ["l'échelle", "sur une carte"], ["le titre", "sur une carte"], ["une recette de gâteau", "pas sur une carte"]]),
    explication: "Une carte a un titre, une orientation, une échelle et une légende. La recette n'a rien à y faire." },
  { cle: "ge-rep-n3-b", competence: "GEO.REPERES", niveau: 3, format: "qcm",
    consigne: "À quoi sert l'échelle d'une carte ?",
    options: ["à connaître les distances en vrai", "à choisir la couleur du ciel", "à compter les élèves"], attendu: "à connaître les distances en vrai",
    explication: "L'échelle permet de savoir combien font, en vrai, les distances mesurées sur la carte." },
  { cle: "ge-rep-n4-a", competence: "GEO.REPERES", niveau: 4, format: "texte",
    consigne: "Les quatre points cardinaux sont le nord, le sud, l'est et l'... Écris le mot.",
    attendu: "ouest",
    explication: "Les quatre points cardinaux : nord, sud, est, ouest. Ils aident à s'orienter." },
  { cle: "ge-rep-n4-b", competence: "GEO.REPERES", niveau: 4, format: "texte",
    consigne: "Sur une carte, le petit cadre qui explique les symboles et les couleurs s'appelle la... Écris le mot.",
    attendu: "légende",
    explication: "La légende : la clé qui explique la carte." },
  // ===== GEO.HABITER =====
  { cle: "ge-hab-n1-a", competence: "GEO.HABITER", niveau: 1, format: "qcm",
    consigne: "Un endroit avec beaucoup d'immeubles, de magasins et de voitures, c'est plutôt...",
    options: ["la ville", "la campagne", "le désert"], attendu: "la ville",
    explication: "En ville, il y a beaucoup d'immeubles, de magasins et de monde." },
  { cle: "ge-hab-n1-b", competence: "GEO.HABITER", niveau: 1, format: "qcm",
    consigne: "Un endroit avec des champs, des fermes et peu de maisons, c'est plutôt...",
    options: ["la campagne", "la ville", "la mer"], attendu: "la campagne",
    explication: "À la campagne, il y a des champs, des fermes et plus d'espace." },
  { cle: "ge-hab-n2-a", competence: "GEO.HABITER", niveau: 2, format: "tri",
    consigne: "Range : plutôt en ville, ou plutôt à la campagne ?",
    ...tri(["la ville", "la campagne"], [["un grand immeuble", "la ville"], ["beaucoup de magasins", "la ville"], ["un champ de blé", "la campagne"], ["une ferme", "la campagne"]]),
    explication: "Immeubles et magasins : la ville. Champs et fermes : la campagne." },
  { cle: "ge-hab-n2-b", competence: "GEO.HABITER", niveau: 2, format: "qcm",
    consigne: "Une très grande ville avec beaucoup d'habitants s'appelle une...",
    options: ["métropole", "cabane", "île"], attendu: "métropole",
    explication: "Une métropole est une très grande ville, avec de nombreux habitants et des transports." },
  { cle: "ge-hab-n3-a", competence: "GEO.HABITER", niveau: 3, format: "qcm",
    consigne: "Pour aller travailler dans une grande ville, beaucoup de gens prennent les...",
    options: ["transports en commun", "fusées", "sous-marins"], attendu: "transports en commun",
    explication: "Le bus, le métro et le tram sont des transports en commun : ils transportent beaucoup de gens à la fois." },
  { cle: "ge-hab-n3-b", competence: "GEO.HABITER", niveau: 3, format: "tri",
    consigne: "Range chaque lieu : pour habiter, ou pour travailler ?",
    ...tri(["pour habiter", "pour travailler"], [["une maison", "pour habiter"], ["un appartement", "pour habiter"], ["un bureau", "pour travailler"], ["une usine", "pour travailler"]]),
    explication: "On habite dans une maison ou un appartement. On travaille dans un bureau ou une usine." },
  { cle: "ge-hab-n4-a", competence: "GEO.HABITER", niveau: 4, format: "texte",
    consigne: "Une très grande ville avec beaucoup d'habitants s'appelle une... Écris le mot.",
    attendu: "métropole",
    explication: "Une métropole : une très grande ville. Paris est la plus grande métropole de France." },
  { cle: "ge-hab-n4-b", competence: "GEO.HABITER", niveau: 4, format: "texte",
    consigne: "La capitale de la France, sa plus grande ville, s'appelle... Écris son nom.",
    attendu: "Paris",
    explication: "Paris est la capitale de la France et sa plus grande ville." },
  // ===== GEO.ACTIVITES =====
  { cle: "ge-act-n1-a", competence: "GEO.ACTIVITES", niveau: 1, format: "qcm",
    consigne: "Où peut-on aller voir des tableaux et des statues ?",
    options: ["au musée", "à la piscine", "au garage"], attendu: "au musée",
    explication: "Au musée, on peut admirer des tableaux, des statues et des objets anciens." },
  { cle: "ge-act-n1-b", competence: "GEO.ACTIVITES", niveau: 1, format: "qcm",
    consigne: "Pour emprunter des livres, on va à la...",
    options: ["bibliothèque", "boulangerie", "gare"], attendu: "bibliothèque",
    explication: "À la bibliothèque, on peut lire et emprunter des livres." },
  { cle: "ge-act-n2-a", competence: "GEO.ACTIVITES", niveau: 2, format: "tri",
    consigne: "Range chaque lieu : pour le travail, les loisirs, ou la culture ?",
    ...tri(["travail", "loisir", "culture"], [["une usine", "travail"], ["un parc d'attractions", "loisir"], ["un musée", "culture"]]),
    explication: "On travaille à l'usine, on s'amuse au parc d'attractions, on découvre des œuvres au musée." },
  { cle: "ge-act-n2-b", competence: "GEO.ACTIVITES", niveau: 2, format: "qcm",
    consigne: "Au bord de la mer, en été, beaucoup de gens viennent pour les...",
    options: ["vacances", "réunions", "usines"], attendu: "vacances",
    explication: "Le bord de mer est un lieu de vacances et de tourisme très apprécié en été." },
  { cle: "ge-act-n3-a", competence: "GEO.ACTIVITES", niveau: 3, format: "qcm",
    consigne: "Un endroit où l'on fait du ski l'hiver se trouve à la...",
    options: ["montagne", "plage", "campagne"], attendu: "montagne",
    explication: "À la montagne, l'hiver, la neige permet de faire du ski et de la luge." },
  { cle: "ge-act-n3-b", competence: "GEO.ACTIVITES", niveau: 3, format: "tri",
    consigne: "Range : plutôt un lieu de loisir, ou un lieu de culture ?",
    ...tri(["loisir", "culture"], [["un stade", "loisir"], ["un parc", "loisir"], ["un théâtre", "culture"], ["un cinéma", "culture"]]),
    explication: "Le stade et le parc sont des lieux de loisir. Le théâtre et le cinéma sont des lieux de culture." },
  { cle: "ge-act-n4-a", competence: "GEO.ACTIVITES", niveau: 4, format: "texte",
    consigne: "Le lieu où l'on va pour emprunter et lire des livres s'appelle la... Écris le mot.",
    attendu: "bibliothèque",
    explication: "La bibliothèque : un lieu de culture où l'on lit et emprunte des livres." },
  { cle: "ge-act-n4-b", competence: "GEO.ACTIVITES", niveau: 4, format: "texte",
    consigne: "La montagne et le bord de mer sont des lieux de vacances et de... Écris le mot (pluriel).",
    attendu: "loisirs",
    explication: "Ce sont des lieux de loisirs : on y vient pour se détendre et s'amuser." },
  // ===== GEO.CONSOMMER =====
  { cle: "ge-con-n1-a", competence: "GEO.CONSOMMER", niveau: 1, format: "qcm",
    consigne: "D'où vient surtout l'eau qui coule au robinet de la maison ?",
    options: ["des rivières et des nappes d'eau", "du frigo", "des nuages directement"], attendu: "des rivières et des nappes d'eau",
    explication: "L'eau du robinet vient des rivières et des nappes sous la terre, puis elle est rendue propre." },
  { cle: "ge-con-n1-b", competence: "GEO.CONSOMMER", niveau: 1, format: "qcm",
    consigne: "Avant d'arriver au robinet, l'eau est d'abord rendue propre : on dit qu'elle est...",
    options: ["traitée", "peinte", "chauffée"], attendu: "traitée",
    explication: "L'eau est traitée, c'est-à-dire nettoyée, pour qu'on puisse la boire sans danger." },
  { cle: "ge-con-n2-a", competence: "GEO.CONSOMMER", niveau: 2, format: "qcm",
    consigne: "Qu'est-ce qui produit de l'électricité grâce au vent ?",
    options: ["l'éolienne", "le four", "la lampe"], attendu: "l'éolienne",
    explication: "L'éolienne transforme la force du vent en électricité." },
  { cle: "ge-con-n2-b", competence: "GEO.CONSOMMER", niveau: 2, format: "tri",
    consigne: "Range chaque aliment : vient plutôt du champ, ou de l'élevage ?",
    ...tri(["du champ", "de l'élevage"], [["le blé", "du champ"], ["les légumes", "du champ"], ["le lait", "de l'élevage"], ["les œufs", "de l'élevage"]]),
    explication: "Le blé et les légumes poussent dans les champs. Le lait et les œufs viennent des animaux d'élevage." },
  { cle: "ge-con-n3-a", competence: "GEO.CONSOMMER", niveau: 3, format: "qcm",
    consigne: "Des fruits et légumes vendus tout près de l'endroit où ils poussent font un...",
    options: ["circuit court", "voyage sur la Lune", "grand détour"], attendu: "circuit court",
    explication: "Un circuit court, c'est quand les aliments voyagent peu entre le producteur et nous." },
  { cle: "ge-con-n3-b", competence: "GEO.CONSOMMER", niveau: 3, format: "qcm",
    consigne: "Le grand réservoir en hauteur qui garde l'eau du village s'appelle le...",
    options: ["château d'eau", "château fort", "château de sable"], attendu: "château d'eau",
    explication: "Le château d'eau garde l'eau en hauteur pour qu'elle arrive jusqu'aux robinets." },
  { cle: "ge-con-n4-a", competence: "GEO.CONSOMMER", niveau: 4, format: "texte",
    consigne: "Avant d'arriver au robinet, l'eau est nettoyée : on dit qu'elle est... Écris le mot.",
    attendu: "traitée",
    explication: "L'eau traitée est propre et bonne à boire." },
  { cle: "ge-con-n4-b", competence: "GEO.CONSOMMER", niveau: 4, format: "texte",
    consigne: "Quand on achète des légumes cultivés tout près, on fait un circuit... Écris le mot.",
    attendu: "court",
    explication: "Un circuit court fait moins voyager les aliments : c'est souvent meilleur pour la planète." },
  // ===== GEO.FRANCE =====
  { cle: "ge-fra-n1-a", competence: "GEO.FRANCE", niveau: 1, format: "qcm",
    consigne: "Quel grand fleuve traverse Paris ?",
    options: ["la Seine", "la Loire", "le Rhône"], attendu: "la Seine",
    explication: "La Seine traverse Paris. C'est l'un des grands fleuves de France." },
  { cle: "ge-fra-n1-b", competence: "GEO.FRANCE", niveau: 1, format: "qcm",
    consigne: "Quelle est la plus haute chaîne de montagnes de France, avec le mont Blanc ?",
    options: ["les Alpes", "la plage", "les Vosges"], attendu: "les Alpes",
    explication: "Les Alpes sont les plus hautes montagnes de France. Le mont Blanc s'y trouve." },
  { cle: "ge-fra-n2-a", competence: "GEO.FRANCE", niveau: 2, format: "tri",
    consigne: "Range : est-ce un fleuve de France, ou une montagne ?",
    ...tri(["un fleuve", "une montagne"], [["la Loire", "un fleuve"], ["la Garonne", "un fleuve"], ["les Pyrénées", "une montagne"], ["le Massif central", "une montagne"]]),
    explication: "La Loire et la Garonne sont des fleuves. Les Pyrénées et le Massif central sont des reliefs." },
  { cle: "ge-fra-n2-b", competence: "GEO.FRANCE", niveau: 2, format: "qcm",
    consigne: "Quel grand océan borde la France à l'ouest ?",
    options: ["l'océan Atlantique", "l'océan Pacifique", "la mer Rouge"], attendu: "l'océan Atlantique",
    explication: "À l'ouest, la France est bordée par l'océan Atlantique." },
  { cle: "ge-fra-n3-a", competence: "GEO.FRANCE", niveau: 3, format: "qcm",
    consigne: "Quel est le plus long fleuve de France ?",
    options: ["la Loire", "la Seine", "le Rhin"], attendu: "la Loire",
    explication: "La Loire est le plus long fleuve de France." },
  { cle: "ge-fra-n3-b", competence: "GEO.FRANCE", niveau: 3, format: "tri",
    consigne: "Range chaque mer ou océan : plutôt au nord/à l'ouest, ou au sud de la France ?",
    ...tri(["au nord ou à l'ouest", "au sud"], [["l'océan Atlantique", "au nord ou à l'ouest"], ["la Manche", "au nord ou à l'ouest"], ["la mer Méditerranée", "au sud"]]),
    explication: "L'Atlantique et la Manche bordent la France au nord et à l'ouest. La Méditerranée est au sud." },
  { cle: "ge-fra-n4-a", competence: "GEO.FRANCE", niveau: 4, format: "texte",
    consigne: "Le fleuve qui traverse Paris s'appelle la... Écris le mot.",
    attendu: "Seine",
    explication: "La Seine traverse Paris avant de rejoindre la mer." },
  { cle: "ge-fra-n4-b", competence: "GEO.FRANCE", niveau: 4, format: "texte",
    consigne: "La haute chaîne de montagnes entre la France et l'Italie, avec le mont Blanc, s'appelle les... Écris le mot.",
    attendu: "Alpes",
    explication: "Les Alpes : les plus hautes montagnes de France." },
  // ===== GEO.PAYSAGES =====
  { cle: "ge-pay-n1-a", competence: "GEO.PAYSAGES", niveau: 1, format: "qcm",
    consigne: "Un paysage avec beaucoup d'arbres serrés les uns contre les autres, c'est une...",
    options: ["forêt", "plage", "rue"], attendu: "forêt",
    explication: "Une forêt est un paysage couvert de nombreux arbres." },
  { cle: "ge-pay-n1-b", competence: "GEO.PAYSAGES", niveau: 1, format: "qcm",
    consigne: "Un paysage avec du sable, des vagues et la mer, c'est le...",
    options: ["bord de mer", "centre-ville", "sommet de montagne"], attendu: "bord de mer",
    explication: "Le bord de mer, c'est la plage, le sable et les vagues." },
  { cle: "ge-pay-n2-a", competence: "GEO.PAYSAGES", niveau: 2, format: "tri",
    consigne: "Range chaque paysage : nature ou ville ?",
    ...tri(["paysage de nature", "paysage de ville"], [["une forêt", "paysage de nature"], ["une plage", "paysage de nature"], ["des immeubles", "paysage de ville"], ["une grande avenue", "paysage de ville"]]),
    explication: "La forêt et la plage sont des paysages de nature. Les immeubles et les avenues, des paysages de ville." },
  { cle: "ge-pay-n2-b", competence: "GEO.PAYSAGES", niveau: 2, format: "qcm",
    consigne: "Dans un paysage de montagne, que voit-on souvent l'hiver ?",
    options: ["de la neige", "du sable chaud", "des bateaux"], attendu: "de la neige",
    explication: "L'hiver, la neige recouvre souvent les sommets des montagnes." },
  { cle: "ge-pay-n3-a", competence: "GEO.PAYSAGES", niveau: 3, format: "tri",
    consigne: "Associe chaque activité au bon paysage.",
    ...tri(["à la montagne", "au bord de mer", "à la campagne"], [["faire du ski", "à la montagne"], ["se baigner dans la mer", "au bord de mer"], ["visiter une ferme", "à la campagne"]]),
    explication: "On skie à la montagne, on se baigne au bord de mer, on visite une ferme à la campagne." },
  { cle: "ge-pay-n3-b", competence: "GEO.PAYSAGES", niveau: 3, format: "qcm",
    consigne: "Une grande étendue d'eau salée, plus petite qu'un océan, s'appelle une...",
    options: ["mer", "rivière", "mare"], attendu: "mer",
    explication: "Une mer est une grande étendue d'eau salée, reliée à un océan." },
  { cle: "ge-pay-n4-a", competence: "GEO.PAYSAGES", niveau: 4, format: "texte",
    consigne: "Un paysage couvert de beaucoup d'arbres serrés s'appelle une... Écris le mot.",
    attendu: "forêt",
    explication: "La forêt : un paysage riche en arbres et en animaux." },
  { cle: "ge-pay-n4-b", competence: "GEO.PAYSAGES", niveau: 4, format: "texte",
    consigne: "L'eau salée qui borde les plages, plus petite qu'un océan, s'appelle la... Écris le mot.",
    attendu: "mer",
    explication: "La mer borde les côtes de France : Méditerranée au sud, Manche au nord." },
];

export const COMPETENCES_GEOGRAPHIE = [
  "GEO.REPERES",
  "GEO.HABITER",
  "GEO.ACTIVITES",
  "GEO.CONSOMMER",
  "GEO.FRANCE",
  "GEO.PAYSAGES",
] as const;
