// Banque « HISTOIRE » (CM1, cycle 3). Nouvelle MATIERE (HIST), rendue par
// <QuestionnerLeMonde> et jugee par le SERVEUR (op 'qm', table public.qm_item,
// verif_qm) comme Questionner le monde, EMC et Sciences. Six sous-matieres :
//   HIST.TRACES       les premieres traces (Prehistoire, grottes ornees) ;
//   HIST.GALLOROMAINS Gaulois et Romains : vie quotidienne, monuments ;
//   HIST.MOYENAGE     au Moyen Age : chateau, village, paysans, metiers ;
//   HIST.MONUMENTS    cathedrales, abbayes, vitraux, art gothique ;
//   HIST.ROIS         Clovis, Charlemagne, rois capetiens (reperes apaises) ;
//   HIST.FRISE        frise chronologique, siecles, chiffres romains.
// BIENVEILLANCE STRICTE : AUCUN recit de bataille, massacre, supplice, esclavage
// ni guerre. On traite les reperes (dates, personnages, vie quotidienne,
// inventions, monuments, frise) de facon factuelle et apaisee. Progression N1
// (CM1 d'emblee) -> N4 (reponse libre). Consignes pour l'oral, un exemple concret.

import { type QmItem, ordre, tri } from "../qm/types";

export const BANQUE_HISTOIRE: QmItem[] = [
  // ===== HIST.TRACES =====
  { cle: "hi-tra-n1-a", competence: "HIST.TRACES", niveau: 1, format: "qcm",
    consigne: "Il y a très longtemps, avant que l'écriture existe. Comment appelle-t-on cette période ?",
    options: ["la Préhistoire", "le Moyen Âge", "aujourd'hui"], attendu: "la Préhistoire",
    explication: "La Préhistoire, c'est la période très ancienne, avant l'invention de l'écriture." },
  { cle: "hi-tra-n1-b", competence: "HIST.TRACES", niveau: 1, format: "qcm",
    consigne: "Sur les parois des grottes, les premiers hommes ont laissé des...",
    options: ["peintures d'animaux", "photos", "affiches"], attendu: "peintures d'animaux",
    explication: "Les premiers hommes peignaient de beaux animaux sur les murs des grottes." },
  { cle: "hi-tra-n2-a", competence: "HIST.TRACES", niveau: 2, format: "qcm",
    consigne: "Quelle grotte, en France, est célèbre pour ses peintures d'animaux ?",
    options: ["Lascaux", "Versailles", "le Louvre"], attendu: "Lascaux",
    explication: "La grotte de Lascaux, en Dordogne, est connue dans le monde entier pour ses peintures." },
  { cle: "hi-tra-n2-b", competence: "HIST.TRACES", niveau: 2, format: "tri",
    consigne: "Range chaque chose : vient de la Préhistoire, ou d'aujourd'hui ?",
    ...tri(["Préhistoire", "aujourd'hui"], [["un silex taillé", "Préhistoire"], ["une peinture de bison", "Préhistoire"], ["une tablette tactile", "aujourd'hui"], ["une voiture", "aujourd'hui"]]),
    explication: "Le silex taillé et les peintures viennent de la Préhistoire. La tablette et la voiture sont d'aujourd'hui." },
  { cle: "hi-tra-n3-a", competence: "HIST.TRACES", niveau: 3, format: "qcm",
    consigne: "Qu'est-ce qui a beaucoup aidé les premiers hommes pour se réchauffer et cuire les aliments ?",
    options: ["la maîtrise du feu", "l'électricité", "le téléphone"], attendu: "la maîtrise du feu",
    explication: "En apprenant à faire du feu, les premiers hommes pouvaient se réchauffer et cuire leur nourriture." },
  { cle: "hi-tra-n3-b", competence: "HIST.TRACES", niveau: 3, format: "ordre",
    consigne: "Range ces grandes périodes, de la plus ancienne à la plus récente.",
    ...ordre(["la Préhistoire", "l'Antiquité", "le Moyen Âge"]),
    explication: "D'abord la Préhistoire, puis l'Antiquité, puis le Moyen Âge. La frise aide à ranger le temps." },
  { cle: "hi-tra-n4-a", competence: "HIST.TRACES", niveau: 4, format: "texte",
    consigne: "La grande période, avant l'invention de l'écriture, s'appelle la... Écris le mot.",
    attendu: "Préhistoire",
    explication: "C'est la Préhistoire. L'écriture marque ensuite le début de l'Antiquité." },
  { cle: "hi-tra-n4-b", competence: "HIST.TRACES", niveau: 4, format: "texte",
    consigne: "Les premiers hommes ont peint des animaux dans la grotte de... (en Dordogne). Écris son nom.",
    attendu: "Lascaux",
    explication: "La grotte de Lascaux garde de magnifiques peintures d'animaux." },
  // ===== HIST.GALLOROMAINS =====
  { cle: "hi-gal-n1-a", competence: "HIST.GALLOROMAINS", niveau: 1, format: "qcm",
    consigne: "Avant de s'appeler la France, notre pays s'appelait la...",
    options: ["Gaule", "Italie", "Égypte"], attendu: "Gaule",
    explication: "Autrefois, notre pays s'appelait la Gaule, et ses habitants étaient les Gaulois." },
  { cle: "hi-gal-n1-b", competence: "HIST.GALLOROMAINS", niveau: 1, format: "qcm",
    consigne: "Les habitants de la Gaule étaient les...",
    options: ["Gaulois", "chevaliers", "astronautes"], attendu: "Gaulois",
    explication: "Les Gaulois vivaient dans des villages, cultivaient la terre et étaient de bons artisans." },
  { cle: "hi-gal-n2-a", competence: "HIST.GALLOROMAINS", niveau: 2, format: "qcm",
    consigne: "Les Romains ont construit de grands ponts pour amener l'eau dans les villes. On les appelle des...",
    options: ["aqueducs", "igloos", "toboggans"], attendu: "aqueducs",
    explication: "Les aqueducs transportaient l'eau sur de longues distances. Le Pont du Gard en est un très beau." },
  { cle: "hi-gal-n2-b", competence: "HIST.GALLOROMAINS", niveau: 2, format: "tri",
    consigne: "Range : construit par les Romains, ou objet d'aujourd'hui ?",
    ...tri(["les Romains", "aujourd'hui"], [["les arènes de Nîmes", "les Romains"], ["le Pont du Gard", "les Romains"], ["un avion", "aujourd'hui"], ["un ordinateur", "aujourd'hui"]]),
    explication: "Les arènes de Nîmes et le Pont du Gard ont été construits par les Romains. L'avion et l'ordinateur sont d'aujourd'hui." },
  { cle: "hi-gal-n3-a", competence: "HIST.GALLOROMAINS", niveau: 3, format: "qcm",
    consigne: "Quelle grande ville gallo-romaine s'appelait autrefois Lugdunum ?",
    options: ["Lyon", "Paris", "Nice"], attendu: "Lyon",
    explication: "Lyon s'appelait Lugdunum à l'époque gallo-romaine. C'était une ville importante." },
  { cle: "hi-gal-n3-b", competence: "HIST.GALLOROMAINS", niveau: 3, format: "qcm",
    consigne: "Les Romains ont apporté en Gaule leur langue, le latin, et de belles...",
    options: ["routes pavées", "fusées", "télévisions"], attendu: "routes pavées",
    explication: "Les Romains ont construit des routes pavées très droites pour voyager dans toute la Gaule." },
  { cle: "hi-gal-n4-a", competence: "HIST.GALLOROMAINS", niveau: 4, format: "texte",
    consigne: "Le célèbre pont romain à trois étages, près de Nîmes, s'appelle le Pont du... Écris le mot.",
    attendu: "Gard",
    explication: "C'est le Pont du Gard, un aqueduc romain magnifique et toujours debout." },
  { cle: "hi-gal-n4-b", competence: "HIST.GALLOROMAINS", niveau: 4, format: "texte",
    consigne: "Avant d'être la France, le pays des Gaulois s'appelait la... Écris le mot.",
    attendu: "Gaule",
    explication: "La Gaule : c'est le nom ancien de notre pays, au temps des Gaulois et des Romains." },
  // ===== HIST.MOYENAGE =====
  { cle: "hi-moy-n1-a", competence: "HIST.MOYENAGE", niveau: 1, format: "qcm",
    consigne: "Au Moyen Âge, le grand bâtiment en pierre où habitait le seigneur était un...",
    options: ["château fort", "supermarché", "aéroport"], attendu: "château fort",
    explication: "Le château fort était la maison du seigneur. Ses gros murs servaient aussi à se protéger." },
  { cle: "hi-moy-n1-b", competence: "HIST.MOYENAGE", niveau: 1, format: "qcm",
    consigne: "Qui cultivait la terre autour du château, au Moyen Âge ?",
    options: ["les paysans", "les astronautes", "les pompiers"], attendu: "les paysans",
    explication: "Les paysans cultivaient les champs et élevaient les animaux autour du château." },
  { cle: "hi-moy-n2-a", competence: "HIST.MOYENAGE", niveau: 2, format: "tri",
    consigne: "Range : au Moyen Âge, ou aujourd'hui ?",
    ...tri(["Moyen Âge", "aujourd'hui"], [["un château fort", "Moyen Âge"], ["un chevalier", "Moyen Âge"], ["un téléphone", "aujourd'hui"], ["une trottinette", "aujourd'hui"]]),
    explication: "Le château fort et le chevalier sont du Moyen Âge. Le téléphone et la trottinette sont d'aujourd'hui." },
  { cle: "hi-moy-n2-b", competence: "HIST.MOYENAGE", niveau: 2, format: "qcm",
    consigne: "Au centre du village du Moyen Âge, on trouvait souvent une petite église et un...",
    options: ["marché", "cinéma", "stade"], attendu: "marché",
    explication: "Sur la place du village, le marché permettait d'échanger les légumes, le pain et les outils." },
  { cle: "hi-moy-n3-a", competence: "HIST.MOYENAGE", niveau: 3, format: "tri",
    consigne: "Associe chaque métier du village à son travail.",
    ...tri(["fabrique des outils en fer", "moud le grain", "fait le pain"], [["le forgeron", "fabrique des outils en fer"], ["le meunier", "moud le grain"], ["le boulanger", "fait le pain"]]),
    explication: "Le forgeron travaille le fer, le meunier moud le grain au moulin, le boulanger cuit le pain." },
  { cle: "hi-moy-n3-b", competence: "HIST.MOYENAGE", niveau: 3, format: "qcm",
    consigne: "Qui vivait dans le château et aidait à protéger le seigneur ?",
    options: ["les chevaliers", "les cosmonautes", "les pilotes"], attendu: "les chevaliers",
    explication: "Les chevaliers, à cheval, servaient le seigneur. On les reconnaissait à leur armure." },
  { cle: "hi-moy-n4-a", competence: "HIST.MOYENAGE", niveau: 4, format: "texte",
    consigne: "Au Moyen Âge, le seigneur habitait un château... (qui servait aussi à se protéger). Écris le mot qui suit château.",
    attendu: "fort",
    explication: "Un château fort : ses hautes murailles protégeaient ceux qui vivaient à l'intérieur." },
  { cle: "hi-moy-n4-b", competence: "HIST.MOYENAGE", niveau: 4, format: "texte",
    consigne: "Les hommes à cheval, en armure, qui servaient le seigneur au Moyen Âge, étaient des... Écris le mot.",
    attendu: "chevaliers",
    explication: "Les chevaliers accompagnaient le seigneur. Devenir chevalier demandait un long apprentissage." },
  // ===== HIST.MONUMENTS =====
  { cle: "hi-mon-n1-a", competence: "HIST.MONUMENTS", niveau: 1, format: "qcm",
    consigne: "Comment s'appelle la grande cathédrale de Paris, sur une île de la Seine ?",
    options: ["Notre-Dame", "la tour Eiffel", "le Louvre"], attendu: "Notre-Dame",
    explication: "La cathédrale Notre-Dame de Paris a été construite au Moyen Âge, il y a très longtemps." },
  { cle: "hi-mon-n1-b", competence: "HIST.MONUMENTS", niveau: 1, format: "qcm",
    consigne: "Dans les cathédrales, les belles fenêtres en verre coloré s'appellent des...",
    options: ["vitraux", "miroirs", "tableaux"], attendu: "vitraux",
    explication: "Les vitraux laissent entrer une lumière colorée dans les cathédrales." },
  { cle: "hi-mon-n2-a", competence: "HIST.MONUMENTS", niveau: 2, format: "qcm",
    consigne: "Les moines vivaient et priaient ensemble dans un grand bâtiment religieux : une...",
    options: ["abbaye", "usine", "gare"], attendu: "abbaye",
    explication: "Dans l'abbaye, les moines priaient, cultivaient un jardin et recopiaient des livres à la main." },
  { cle: "hi-mon-n2-b", competence: "HIST.MONUMENTS", niveau: 2, format: "tri",
    consigne: "Range chaque monument : du Moyen Âge, ou de l'époque des rois (plus tard) ?",
    ...tri(["Moyen Âge", "époque des rois"], [["une cathédrale gothique", "Moyen Âge"], ["une abbaye", "Moyen Âge"], ["le château de Versailles", "époque des rois"], ["le château de Chambord", "époque des rois"]]),
    explication: "Les cathédrales et abbayes datent du Moyen Âge. Versailles et Chambord ont été bâtis plus tard, au temps des grands rois." },
  { cle: "hi-mon-n3-a", competence: "HIST.MONUMENTS", niveau: 3, format: "qcm",
    consigne: "Les cathédrales du Moyen Âge, très hautes, avec des arcs pointus, sont de style...",
    options: ["gothique", "moderne", "spatial"], attendu: "gothique",
    explication: "L'art gothique rend les cathédrales très hautes et lumineuses, avec de grands vitraux." },
  { cle: "hi-mon-n3-b", competence: "HIST.MONUMENTS", niveau: 3, format: "qcm",
    consigne: "Construire une cathédrale demandait beaucoup de temps : parfois plus de...",
    options: ["cent ans", "un jour", "une heure"], attendu: "cent ans",
    explication: "Il fallait souvent plus de cent ans pour terminer une cathédrale : plusieurs générations y travaillaient." },
  { cle: "hi-mon-n4-a", competence: "HIST.MONUMENTS", niveau: 4, format: "texte",
    consigne: "Les fenêtres en verre coloré des cathédrales s'appellent des... Écris le mot.",
    attendu: "vitraux",
    explication: "Les vitraux racontent souvent des histoires avec leurs images colorées." },
  { cle: "hi-mon-n4-b", competence: "HIST.MONUMENTS", niveau: 4, format: "texte",
    consigne: "Le grand bâtiment religieux où vivaient les moines s'appelle une... Écris le mot.",
    attendu: "abbaye",
    explication: "Une abbaye : les moines y vivaient en priant et en travaillant." },
  // ===== HIST.ROIS =====
  { cle: "hi-roi-n1-a", competence: "HIST.ROIS", niveau: 1, format: "qcm",
    consigne: "Quel roi des Francs a été baptisé à Reims, il y a très longtemps ?",
    options: ["Clovis", "Napoléon", "Astérix"], attendu: "Clovis",
    explication: "Clovis, roi des Francs, a été baptisé à Reims. C'est l'un des tout premiers rois de notre histoire." },
  { cle: "hi-roi-n1-b", competence: "HIST.ROIS", niveau: 1, format: "qcm",
    consigne: "Quel empereur, couronné en l'an 800, aimait les livres et a aidé les écoles ?",
    options: ["Charlemagne", "Jules César", "Henri IV"], attendu: "Charlemagne",
    explication: "Charlemagne a encouragé les écoles pour que plus d'enfants apprennent à lire et à écrire." },
  { cle: "hi-roi-n2-a", competence: "HIST.ROIS", niveau: 2, format: "tri",
    consigne: "Associe chaque roi ou empereur à ce qu'on retient de lui.",
    ...tri(["baptisé à Reims", "a aidé les écoles", "rendait la justice"], [["Clovis", "baptisé à Reims"], ["Charlemagne", "a aidé les écoles"], ["Saint Louis", "rendait la justice"]]),
    explication: "Clovis fut baptisé à Reims, Charlemagne aida les écoles, et Saint Louis était connu pour rendre la justice." },
  { cle: "hi-roi-n2-b", competence: "HIST.ROIS", niveau: 2, format: "qcm",
    consigne: "En quelle année Charlemagne a-t-il été couronné empereur ?",
    options: ["en l'an 800", "en l'an 1800", "en l'an 2000"], attendu: "en l'an 800",
    explication: "Charlemagne est couronné empereur en l'an 800. C'est un repère important de la frise." },
  { cle: "hi-roi-n3-a", competence: "HIST.ROIS", niveau: 3, format: "qcm",
    consigne: "Le roi Saint Louis écoutait les gens sous un grand chêne. Il était connu pour rendre la...",
    options: ["justice", "cuisine", "musique"], attendu: "justice",
    explication: "Saint Louis aimait rendre la justice : il écoutait les gens pour trouver une solution juste." },
  { cle: "hi-roi-n3-b", competence: "HIST.ROIS", niveau: 3, format: "ordre",
    consigne: "Range ces rois et empereur du plus ancien au plus récent.",
    ...ordre(["Clovis", "Charlemagne", "Saint Louis"]),
    explication: "D'abord Clovis, puis Charlemagne, puis Saint Louis : la frise les range dans le temps." },
  { cle: "hi-roi-n4-a", competence: "HIST.ROIS", niveau: 4, format: "texte",
    consigne: "Le roi des Francs baptisé à Reims s'appelait... Écris son nom.",
    attendu: "Clovis",
    explication: "Clovis : l'un des premiers rois des Francs, baptisé à Reims." },
  { cle: "hi-roi-n4-b", competence: "HIST.ROIS", niveau: 4, format: "texte",
    consigne: "L'empereur couronné en l'an 800, qui aimait les écoles, s'appelait... Écris son nom.",
    attendu: "Charlemagne",
    explication: "Charlemagne : empereur en l'an 800, ami des écoles et des livres." },
  // ===== HIST.FRISE =====
  { cle: "hi-fri-n1-a", competence: "HIST.FRISE", niveau: 1, format: "qcm",
    consigne: "Pour ranger les événements dans le temps, on utilise une...",
    options: ["frise chronologique", "recette de cuisine", "carte au trésor"], attendu: "frise chronologique",
    explication: "La frise chronologique est une longue ligne du temps : on y range les événements dans l'ordre." },
  { cle: "hi-fri-n1-b", competence: "HIST.FRISE", niveau: 1, format: "qcm",
    consigne: "Sur la frise de l'Histoire, quelle grande période vient en premier ?",
    options: ["la Préhistoire", "le Moyen Âge", "aujourd'hui"], attendu: "la Préhistoire",
    explication: "La Préhistoire est la période la plus ancienne : elle se place tout au début de la frise." },
  { cle: "hi-fri-n2-a", competence: "HIST.FRISE", niveau: 2, format: "qcm",
    consigne: "Un siècle, c'est une durée de...",
    options: ["cent ans", "dix ans", "mille ans"], attendu: "cent ans",
    explication: "Un siècle dure cent ans. On compte souvent l'Histoire en siècles." },
  { cle: "hi-fri-n2-b", competence: "HIST.FRISE", niveau: 2, format: "ordre",
    consigne: "Range ces grandes périodes dans l'ordre du temps.",
    ...ordre(["la Préhistoire", "l'Antiquité", "le Moyen Âge", "les Temps modernes"]),
    explication: "Préhistoire, Antiquité, Moyen Âge, puis Temps modernes : c'est l'ordre des grandes périodes." },
  { cle: "hi-fri-n3-a", competence: "HIST.FRISE", niveau: 3, format: "qcm",
    consigne: "On écrit les siècles en chiffres romains. Comment écrit-on le 5e siècle ?",
    options: ["Ve", "5e", "V5"], attendu: "Ve",
    explication: "Le 5e siècle s'écrit Ve en chiffres romains. La lettre V vaut 5." },
  { cle: "hi-fri-n3-b", competence: "HIST.FRISE", niveau: 3, format: "qcm",
    consigne: "Comment écrit-on le 10e siècle en chiffres romains ?",
    options: ["Xe", "10e", "Ie"], attendu: "Xe",
    explication: "Le 10e siècle s'écrit Xe. La lettre X vaut 10 en chiffres romains." },
  { cle: "hi-fri-n4-a", competence: "HIST.FRISE", niveau: 4, format: "texte",
    consigne: "En chiffres romains, la lettre qui vaut cent (100) est la lettre... Écris la lettre.",
    attendu: "C",
    explication: "La lettre C vaut 100 en chiffres romains. V vaut 5, X vaut 10, C vaut 100." },
  { cle: "hi-fri-n4-b", competence: "HIST.FRISE", niveau: 4, format: "texte",
    consigne: "On range les événements de l'Histoire, dans l'ordre, sur une... chronologique. Écris le mot qui manque.",
    attendu: "frise",
    explication: "La frise chronologique : la ligne du temps qui range les événements." },
];

export const COMPETENCES_HISTOIRE = [
  "HIST.TRACES",
  "HIST.GALLOROMAINS",
  "HIST.MOYENAGE",
  "HIST.MONUMENTS",
  "HIST.ROIS",
  "HIST.FRISE",
] as const;
