// Banque « SCIENCES ET TECHNOLOGIE » (ST, CM1 - PROGRAMME 2026). Nouvelle
// MATIERE rendue par <QuestionnerLeMonde> et jugee par le SERVEUR (op 'qm',
// table public.qm_item, verif_qm) comme Questionner le monde, EMC, etc.
//
// Source officielle : arrete du 5 juin 2026, BO n° 24 du 11 juin 2026, programme
// de sciences et technologie du cycle 3 (annexe 2), EN VIGUEUR AU CM1 a la
// rentree 2026. Attendus « Cours moyen premiere annee » exacts, repartis selon
// les QUATRE THEMES du programme :
//
//   Theme « La matiere, les mouvements et les signaux » :
//     ST.MATIERE.ETATS    etats_matiere  masse (balance, tare), melanges
//                                        homogene/heterogene, tamisage,
//                                        decantation, filtration, dissolution,
//                                        saturation ;
//     ST.PHYSIQUE.LUMIERE lumiere        transparent/translucide/opaque, ombre
//                                        propre/portee, taille de l'ombre ;
//                                        mesurer distance et duree d'un trajet.
//   Theme « Les etres vivants dans leur environnement » :
//     ST.VIVANT.CLASSER     classification espece (interfeconds), groupes
//                                          emboites et parente, cle de
//                                          determination, cycle de vie
//                                          ovipare/vivipare ;
//     ST.VIVANT.ECOSYSTEMES ecosystemes    ecosysteme, cooperation/predation,
//                                          reseaux alimentaires, besoins des
//                                          vegetaux, action humaine.
//   Theme « Le corps humain et la sante » :
//     ST.CORPS.SANTE      corps_humain   le cerveau (fonctions, attention,
//                                        memoire), la puberte.
//   Theme « La Terre, une planete active » + signaux (Lune) :
//     ST.TERRE.CIEL       ciel_terre     meteorologie (thermometre, pluviometre,
//                                        anemometre), saisons ; phases de la Lune.
//   Theme « Les objets techniques au cœur de la societe » :
//     ST.OBJETS.TECHNIQUE objets_techniques  evolution d'un objet, fonctions et
//                                        composants, croquis legende,
//                                        programmation d'un objet (robot).
//
// BIENVEILLANCE STRICTE : les sciences restent sous la regle (seule l'histoire
// est exemptee). Predation dite avec douceur (« se nourrir », jamais « devore »).
// La puberte (attendu officiel CM1) est presentee calmement et sans jugement.
//
// L'ancienne sous-matiere « energie » (ancien programme) est desactivee
// (migration 0105, actif=false) sans perte de donnees.

import { type QmItem, ordre, tri } from "../qm/types";

export const BANQUE_SCIENCES: QmItem[] = [
  // ===== ST.MATIERE.ETATS - masse et melanges =====
  { cle: "st-mat-n1-a", competence: "ST.MATIERE.ETATS", niveau: 1, format: "qcm",
    consigne: "Avec quel instrument mesure-t-on la masse d'un objet ?",
    options: ["une balance", "une règle", "un thermomètre"], attendu: "une balance",
    explication: "La balance sert à mesurer la masse, en grammes ou en kilogrammes." },
  { cle: "st-mat-n1-b", competence: "ST.MATIERE.ETATS", niveau: 1, format: "qcm",
    consigne: "Quand on mélange du sucre dans l'eau et qu'il disparaît dans le liquide, on dit qu'il se...",
    options: ["dissout", "casse", "gèle"], attendu: "dissout",
    explication: "Le sucre se dissout dans l'eau : on ne le voit plus, mais il est toujours là (l'eau devient sucrée)." },
  { cle: "st-mat-n2-a", competence: "ST.MATIERE.ETATS", niveau: 2, format: "qcm",
    consigne: "Un mélange où l'on voit encore les différents morceaux, comme l'eau et le sable, est un mélange...",
    options: ["hétérogène", "homogène", "gelé"], attendu: "hétérogène",
    explication: "Dans un mélange hétérogène, on distingue les constituants (eau + sable). Dans un mélange homogène, non (eau sucrée)." },
  { cle: "st-mat-n2-b", competence: "ST.MATIERE.ETATS", niveau: 2, format: "tri",
    consigne: "Range chaque solide : se dissout dans l'eau, ou ne se dissout pas ?",
    ...tri(["se dissout", "ne se dissout pas"], [["le sel", "se dissout"], ["le sucre", "se dissout"], ["le sable", "ne se dissout pas"], ["les cailloux", "ne se dissout pas"]]),
    explication: "Le sel et le sucre se dissolvent dans l'eau ; le sable et les cailloux, non : on peut les récupérer avec un filtre." },
  { cle: "st-mat-n3-a", competence: "ST.MATIERE.ETATS", niveau: 3, format: "qcm",
    consigne: "Pour séparer le sable et l'eau, on verse le mélange dans un papier filtre. Comment s'appelle cette méthode ?",
    options: ["la filtration", "la cuisson", "la congélation"], attendu: "la filtration",
    explication: "La filtration retient les solides (sable) et laisse passer le liquide (eau)." },
  { cle: "st-mat-n3-b", competence: "ST.MATIERE.ETATS", niveau: 3, format: "tri",
    consigne: "Associe chaque méthode de séparation à ce qu'elle fait.",
    ...tri(["le tamisage", "la filtration", "la décantation"], [["séparer des cailloux et du sable avec des tamis", "le tamisage"], ["retenir le sable avec un papier filtre", "la filtration"], ["laisser la terre se déposer au fond de l'eau", "la décantation"]]),
    explication: "Tamisage (tamis), filtration (filtre), décantation (on laisse se déposer) : trois façons de séparer un mélange." },
  { cle: "st-mat-n4-a", competence: "ST.MATIERE.ETATS", niveau: 4, format: "texte",
    consigne: "Un mélange transparent où l'on ne voit plus les morceaux, comme l'eau sucrée, est un mélange... Écris le mot.",
    attendu: "homogène",
    explication: "Un mélange homogène a le même aspect partout : on ne distingue plus les constituants." },
  { cle: "st-mat-n4-b", competence: "ST.MATIERE.ETATS", niveau: 4, format: "texte",
    consigne: "Avant de peser un liquide dans un pot, on règle la balance à zéro avec le pot vide : on fait la... Écris le mot.",
    attendu: "tare",
    explication: "Faire la tare, c'est remettre la balance à zéro pour ne peser que le contenu, pas le récipient." },

  // ===== ST.PHYSIQUE.LUMIERE - lumiere, ombres et mouvement =====
  { cle: "st-lum-n1-a", competence: "ST.PHYSIQUE.LUMIERE", niveau: 1, format: "qcm",
    consigne: "Un objet à travers lequel on voit parfaitement, comme une vitre propre, est...",
    options: ["transparent", "opaque", "mou"], attendu: "transparent",
    explication: "Un objet transparent laisse passer la lumière et on voit nettement au travers." },
  { cle: "st-lum-n1-b", competence: "ST.PHYSIQUE.LUMIERE", niveau: 1, format: "qcm",
    consigne: "Quand un objet arrête la lumière, qu'est-ce qui apparaît derrière lui ?",
    options: ["une ombre", "une musique", "une odeur"], attendu: "une ombre",
    explication: "Un objet qui arrête la lumière crée une ombre, là où la lumière ne passe plus." },
  { cle: "st-lum-n2-a", competence: "ST.PHYSIQUE.LUMIERE", niveau: 2, format: "tri",
    consigne: "Range chaque objet : transparent, translucide ou opaque ?",
    ...tri(["transparent", "translucide", "opaque"], [["une vitre propre", "transparent"], ["du papier calque", "translucide"], ["un mur en pierre", "opaque"], ["un livre fermé", "opaque"]]),
    explication: "Transparent : on voit au travers. Translucide : la lumière passe un peu. Opaque : la lumière ne passe pas." },
  { cle: "st-lum-n2-b", competence: "ST.PHYSIQUE.LUMIERE", niveau: 2, format: "qcm",
    consigne: "Pour obtenir une ombre, il faut une source de lumière et un objet...",
    options: ["opaque", "transparent", "liquide"], attendu: "opaque",
    explication: "Seul un objet opaque, qui arrête la lumière, peut former une ombre bien nette." },
  { cle: "st-lum-n3-a", competence: "ST.PHYSIQUE.LUMIERE", niveau: 3, format: "qcm",
    consigne: "Si on rapproche la lampe de l'objet, son ombre sur le mur devient...",
    options: ["plus grande", "plus petite", "invisible"], attendu: "plus grande",
    explication: "Plus la source de lumière est proche de l'objet, plus l'ombre portée est grande." },
  { cle: "st-lum-n3-b", competence: "ST.PHYSIQUE.LUMIERE", niveau: 3, format: "qcm",
    consigne: "Pour mesurer la longueur du trajet d'une petite voiture, du départ à l'arrivée, on utilise un...",
    options: ["mètre", "thermomètre", "entonnoir"], attendu: "mètre",
    explication: "On mesure une distance (en mètres ou centimètres) avec un mètre, une règle ou un gabarit." },
  { cle: "st-lum-n4-a", competence: "ST.PHYSIQUE.LUMIERE", niveau: 4, format: "texte",
    consigne: "Un objet qui laisse passer un peu de lumière mais qu'on ne voit pas nettement au travers (papier calque) est... Écris le mot.",
    attendu: "translucide",
    explication: "Translucide : entre transparent et opaque, la lumière passe mais l'image n'est pas nette." },
  { cle: "st-lum-n4-b", competence: "ST.PHYSIQUE.LUMIERE", niveau: 4, format: "texte",
    consigne: "Pour mesurer la durée d'un déplacement, entre le départ et l'arrivée, on utilise un... Écris le mot.",
    attendu: "chronomètre",
    explication: "Le chronomètre mesure une durée, c'est-à-dire le temps entre deux instants." },

  // ===== ST.VIVANT.CLASSER - classer le vivant, cycle de vie =====
  { cle: "st-viv-n1-a", competence: "ST.VIVANT.CLASSER", niveau: 1, format: "qcm",
    consigne: "Un ensemble d'animaux qui peuvent avoir des petits ensemble forme une...",
    options: ["espèce", "ville", "équipe"], attendu: "espèce",
    explication: "Une espèce regroupe les individus capables de se reproduire entre eux, comme tous les chats." },
  { cle: "st-viv-n1-b", competence: "ST.VIVANT.CLASSER", niveau: 1, format: "qcm",
    consigne: "Un animal qui pond des œufs est un animal...",
    options: ["ovipare", "vivipare", "minéral"], attendu: "ovipare",
    explication: "Ovipare veut dire « qui pond des œufs », comme la poule ou la grenouille." },
  { cle: "st-viv-n2-a", competence: "ST.VIVANT.CLASSER", niveau: 2, format: "qcm",
    consigne: "Un animal dont les petits naissent déjà formés, comme le chat ou la vache, est un animal...",
    options: ["vivipare", "ovipare", "végétal"], attendu: "vivipare",
    explication: "Vivipare veut dire que les petits se développent dans le ventre de la mère avant de naître." },
  { cle: "st-viv-n2-b", competence: "ST.VIVANT.CLASSER", niveau: 2, format: "tri",
    consigne: "Range chaque animal : pond des œufs (ovipare), ou met au monde des petits (vivipare) ?",
    ...tri(["ovipare", "vivipare"], [["la poule", "ovipare"], ["la grenouille", "ovipare"], ["le chat", "vivipare"], ["la vache", "vivipare"]]),
    explication: "La poule et la grenouille pondent des œufs (ovipares) ; le chat et la vache ont des petits formés (vivipares)." },
  { cle: "st-viv-n3-a", competence: "ST.VIVANT.CLASSER", niveau: 3, format: "qcm",
    consigne: "Pour reconnaître le nom d'un animal ou d'une plante en répondant à des questions (a-t-il des ailes ? des poils ?), on utilise une...",
    options: ["clé de détermination", "carte au trésor", "recette de cuisine"], attendu: "clé de détermination",
    explication: "Une clé de détermination pose des questions, étape par étape, pour trouver le nom d'une espèce." },
  { cle: "st-viv-n3-b", competence: "ST.VIVANT.CLASSER", niveau: 3, format: "ordre",
    consigne: "Range les étapes du développement d'un poussin, dans l'ordre.",
    ...ordre(["la fécondation", "le développement dans l'œuf", "l'éclosion"]),
    explication: "Après la fécondation, le poussin se développe dans l'œuf, puis l'œuf éclôt : c'est l'éclosion." },
  { cle: "st-viv-n4-a", competence: "ST.VIVANT.CLASSER", niveau: 4, format: "texte",
    consigne: "Un ensemble d'individus qui peuvent se reproduire entre eux s'appelle une... Écris le mot.",
    attendu: "espèce",
    explication: "L'espèce est la base pour classer les êtres vivants et comprendre leurs liens de parenté." },
  { cle: "st-viv-n4-b", competence: "ST.VIVANT.CLASSER", niveau: 4, format: "texte",
    consigne: "Un animal qui pond des œufs est dit... Écris le mot.",
    attendu: "ovipare",
    explication: "Ovipare : qui se reproduit en pondant des œufs. Le contraire est vivipare." },

  // ===== ST.VIVANT.ECOSYSTEMES - ecosystemes et chaines alimentaires =====
  { cle: "st-eco-n1-a", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 1, format: "qcm",
    consigne: "Un ensemble d'êtres vivants, leur milieu de vie et leurs relations s'appelle un...",
    options: ["écosystème", "ordinateur", "immeuble"], attendu: "écosystème",
    explication: "Un écosystème, c'est par exemple une forêt : des plantes, des animaux et leur milieu qui vivent ensemble." },
  { cle: "st-eco-n1-b", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 1, format: "qcm",
    consigne: "De quoi une plante verte a-t-elle besoin pour grandir ?",
    options: ["de lumière et d'eau", "de bonbons", "de musique"], attendu: "de lumière et d'eau",
    explication: "Les plantes vertes ont besoin de lumière, d'eau et d'air pour fabriquer leur propre matière." },
  { cle: "st-eco-n2-a", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 2, format: "qcm",
    consigne: "Dans une chaîne alimentaire, la flèche va de l'être vivant mangé vers celui qui...",
    options: ["le mange", "dort", "chante"], attendu: "le mange",
    explication: "La flèche montre le transfert de nourriture : elle va du mangé vers le mangeur." },
  { cle: "st-eco-n2-b", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 2, format: "ordre",
    consigne: "Range cette chaîne alimentaire, du premier mangé au dernier mangeur.",
    ...ordre(["l'herbe", "le lapin", "le renard"]),
    explication: "L'herbe nourrit le lapin, qui nourrit le renard. Chacun se nourrit pour vivre et grandir." },
  { cle: "st-eco-n3-a", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 3, format: "qcm",
    consigne: "Si une espèce devient très rare dans un milieu, cela dérange tout le...",
    options: ["réseau alimentaire", "dessin animé", "emploi du temps"], attendu: "réseau alimentaire",
    explication: "Les êtres vivants sont reliés dans un réseau alimentaire : si l'un change, les autres sont touchés. L'action humaine peut déranger cet équilibre." },
  { cle: "st-eco-n3-b", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 3, format: "tri",
    consigne: "Range chaque relation entre êtres vivants : coopération, ou prédation ?",
    ...tri(["coopération", "prédation"], [["l'abeille butine la fleur et la pollinise", "coopération"], ["le poisson-clown et l'anémone se protègent", "coopération"], ["le renard chasse le lapin pour se nourrir", "prédation"], ["la coccinelle se nourrit de pucerons", "prédation"]]),
    explication: "Coopération : les deux s'entraident. Prédation : l'un se nourrit de l'autre. Les deux existent dans la nature." },
  { cle: "st-eco-n4-a", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 4, format: "texte",
    consigne: "Un ensemble d'êtres vivants, leur milieu et leurs relations s'appelle un... Écris le mot.",
    attendu: "écosystème",
    explication: "L'écosystème relie les êtres vivants entre eux et avec leur milieu de vie." },
  { cle: "st-eco-n4-b", competence: "ST.VIVANT.ECOSYSTEMES", niveau: 4, format: "texte",
    consigne: "La fabrication de matière par les plantes vertes, grâce à la lumière, l'eau et l'air, s'appelle la... Écris le mot.",
    attendu: "photosynthèse",
    explication: "La photosynthèse : grâce à la lumière, les plantes vertes fabriquent leur nourriture et rejettent de l'oxygène." },

  // ===== ST.CORPS.SANTE - le cerveau et la puberte =====
  { cle: "st-cor-n1-a", competence: "ST.CORPS.SANTE", niveau: 1, format: "qcm",
    consigne: "Quel organe commande nos mouvements, notre mémoire et nos émotions ?",
    options: ["le cerveau", "l'estomac", "le genou"], attendu: "le cerveau",
    explication: "Le cerveau, dans la tête, commande le corps, pense, se souvient et ressent les émotions." },
  { cle: "st-cor-n1-b", competence: "ST.CORPS.SANTE", niveau: 1, format: "qcm",
    consigne: "La période où le corps d'un enfant se transforme peu à peu pour devenir adulte s'appelle la...",
    options: ["puberté", "sieste", "récréation"], attendu: "puberté",
    explication: "La puberté est une étape normale où le corps grandit et change, vers 10 à 14 ans environ." },
  { cle: "st-cor-n2-a", competence: "ST.CORPS.SANTE", niveau: 2, format: "qcm",
    consigne: "Quand tu apprends une poésie et que tu t'en souviens, quelle fonction du cerveau utilises-tu ?",
    options: ["la mémoire", "la digestion", "la respiration"], attendu: "la mémoire",
    explication: "La mémoire est une grande fonction du cerveau : elle garde les informations que l'on a apprises." },
  { cle: "st-cor-n2-b", competence: "ST.CORPS.SANTE", niveau: 2, format: "qcm",
    consigne: "Pendant la puberté, la taille et la masse du corps...",
    options: ["augmentent", "disparaissent", "restent pareilles"], attendu: "augmentent",
    explication: "À la puberté, on grandit vite : la taille et la masse du corps augmentent nettement." },
  { cle: "st-cor-n3-a", competence: "ST.CORPS.SANTE", niveau: 3, format: "qcm",
    consigne: "Pour bien mémoriser une leçon, qu'est-ce qui aide le cerveau ?",
    options: ["s'entraîner et faire attention", "regarder ailleurs", "aller vite sans comprendre"], attendu: "s'entraîner et faire attention",
    explication: "Le cerveau retient mieux quand on fait attention, qu'on comprend et qu'on s'entraîne plusieurs fois." },
  { cle: "st-cor-n3-b", competence: "ST.CORPS.SANTE", niveau: 3, format: "qcm",
    consigne: "La puberté n'arrive pas au même âge pour tout le monde. Ces différences sont...",
    options: ["tout à fait normales", "inquiétantes", "interdites"], attendu: "tout à fait normales",
    explication: "Chacun grandit à son rythme : la puberté arrive à des âges différents, et c'est tout à fait normal." },
  { cle: "st-cor-n4-a", competence: "ST.CORPS.SANTE", niveau: 4, format: "texte",
    consigne: "L'organe qui commande le mouvement, le langage, la mémoire et les émotions est le... Écris le mot.",
    attendu: "cerveau",
    explication: "Le cerveau est le chef d'orchestre du corps : il a de nombreuses fonctions." },
  { cle: "st-cor-n4-b", competence: "ST.CORPS.SANTE", niveau: 4, format: "texte",
    consigne: "La période où le corps se transforme pour devenir adulte s'appelle la... Écris le mot.",
    attendu: "puberté",
    explication: "La puberté : une étape normale de la vie, qui se produit à des âges différents selon les personnes." },

  // ===== ST.TERRE.CIEL - meteorologie et phases de la Lune =====
  { cle: "st-ter-n1-a", competence: "ST.TERRE.CIEL", niveau: 1, format: "qcm",
    consigne: "Avec quel instrument mesure-t-on la température de l'air ?",
    options: ["un thermomètre", "une règle", "une balance"], attendu: "un thermomètre",
    explication: "Le thermomètre mesure la température, en degrés. Il sert à suivre la météo." },
  { cle: "st-ter-n1-b", competence: "ST.TERRE.CIEL", niveau: 1, format: "qcm",
    consigne: "La Lune change de forme au fil des jours : on parle des... de la Lune.",
    options: ["phases", "couleurs", "bruits"], attendu: "phases",
    explication: "Les phases de la Lune (nouvelle Lune, pleine Lune...) reviennent dans un cycle d'environ un mois." },
  { cle: "st-ter-n2-a", competence: "ST.TERRE.CIEL", niveau: 2, format: "tri",
    consigne: "Associe chaque instrument de météo à ce qu'il mesure.",
    ...tri(["la température", "la pluie", "le vent"], [["le thermomètre", "la température"], ["le pluviomètre", "la pluie"], ["l'anémomètre", "le vent"]]),
    explication: "Thermomètre (température), pluviomètre (pluie), anémomètre (vent) : les instruments de la météo." },
  { cle: "st-ter-n2-b", competence: "ST.TERRE.CIEL", niveau: 2, format: "qcm",
    consigne: "Quand la Lune apparaît toute ronde et bien éclairée, on l'appelle la...",
    options: ["pleine Lune", "nouvelle Lune", "demi-Lune"], attendu: "pleine Lune",
    explication: "À la pleine Lune, on voit toute la face éclairée. À la nouvelle Lune, on ne la voit presque pas." },
  { cle: "st-ter-n3-a", competence: "ST.TERRE.CIEL", niveau: 3, format: "qcm",
    consigne: "La météo change selon les saisons. En hiver, les températures sont souvent...",
    options: ["plus basses", "plus hautes", "toujours les mêmes"], attendu: "plus basses",
    explication: "Les mesures de température changent avec les saisons : plus basses en hiver, plus hautes en été." },
  { cle: "st-ter-n3-b", competence: "ST.TERRE.CIEL", niveau: 3, format: "ordre",
    consigne: "Range les saisons dans l'ordre, en partant du printemps.",
    ...ordre(["le printemps", "l'été", "l'automne", "l'hiver"]),
    explication: "Printemps, été, automne, hiver : les quatre saisons se suivent et reviennent chaque année." },
  { cle: "st-ter-n4-a", competence: "ST.TERRE.CIEL", niveau: 4, format: "texte",
    consigne: "L'instrument qui mesure la quantité de pluie tombée s'appelle un... Écris le mot.",
    attendu: "pluviomètre",
    explication: "Le pluviomètre recueille la pluie pour mesurer combien il est tombé d'eau." },
  { cle: "st-ter-n4-b", competence: "ST.TERRE.CIEL", niveau: 4, format: "texte",
    consigne: "Le mouvement de la Terre qui tourne sur elle-même en un jour, et qui explique le jour et la nuit, s'appelle la... Écris le mot.",
    attendu: "rotation",
    explication: "La rotation de la Terre sur elle-même dure 24 heures : c'est elle qui fait l'alternance du jour et de la nuit." },

  // ===== ST.OBJETS.TECHNIQUE - objets techniques et programmation =====
  { cle: "st-obj-n1-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 1, format: "qcm",
    consigne: "À quoi sert principalement un casque de vélo ?",
    options: ["à protéger la tête", "à écouter de la musique", "à voir la nuit"], attendu: "à protéger la tête",
    explication: "Chaque objet technique répond à un besoin. Le casque de vélo sert à protéger la tête." },
  { cle: "st-obj-n1-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 1, format: "qcm",
    consigne: "Une suite d'instructions qui dit à un robot ce qu'il doit faire s'appelle un...",
    options: ["programme", "gâteau", "paysage"], attendu: "programme",
    explication: "Un programme est une suite d'instructions qui commande le robot, dans l'ordre." },
  { cle: "st-obj-n2-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 2, format: "qcm",
    consigne: "Sur un stylo à bille, à quoi sert le bouchon ?",
    options: ["à protéger la pointe", "à écrire", "à effacer"], attendu: "à protéger la pointe",
    explication: "Chaque partie d'un objet a une fonction : le bouchon du stylo protège la pointe et évite les taches." },
  { cle: "st-obj-n2-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 2, format: "tri",
    consigne: "Range chaque objet selon le besoin auquel il répond : se déplacer, ou s'hydrater ?",
    ...tri(["se déplacer", "s'hydrater"], [["le vélo", "se déplacer"], ["le bus", "se déplacer"], ["la gourde", "s'hydrater"], ["la carafe", "s'hydrater"]]),
    explication: "Un même besoin peut avoir plusieurs objets : pour boire, la gourde à l'école, la carafe au repas." },
  { cle: "st-obj-n3-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 3, format: "qcm",
    consigne: "Le train a beaucoup changé depuis son invention. On dit qu'il a...",
    options: ["évolué", "disparu", "rétréci"], attendu: "évolué",
    explication: "Les objets techniques évoluent avec le temps : le train est devenu plus rapide et plus confortable." },
  { cle: "st-obj-n3-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 3, format: "qcm",
    consigne: "Pour qu'un robot avance puis tourne, il faut écrire les instructions dans le bon...",
    options: ["ordre", "dessin", "goûter"], attendu: "ordre",
    explication: "Un programme fonctionne dans l'ordre : si on change l'ordre des instructions, le robot ne fait plus la même chose." },
  { cle: "st-obj-n4-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 4, format: "texte",
    consigne: "Le dessin à main levée, légendé, qui décrit un objet technique et ses parties s'appelle un... Écris le mot.",
    attendu: "croquis",
    explication: "Le croquis légendé aide à décrire un objet technique et à expliquer comment il fonctionne." },
  { cle: "st-obj-n4-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 4, format: "texte",
    consigne: "La suite d'instructions qui commande un robot s'appelle un... Écris le mot.",
    attendu: "programme",
    explication: "Le programme commande le robot : chaque instruction agit sur son comportement." },
];

export const COMPETENCES_SCIENCES = [
  "ST.MATIERE.ETATS",
  "ST.PHYSIQUE.LUMIERE",
  "ST.VIVANT.CLASSER",
  "ST.VIVANT.ECOSYSTEMES",
  "ST.CORPS.SANTE",
  "ST.TERRE.CIEL",
  "ST.OBJETS.TECHNIQUE",
] as const;
