// Banque « SCIENCES ET TECHNOLOGIE » (CM1, cycle 3). Nouvelle MATIERE (ST),
// rendue par <QuestionnerLeMonde> et jugee par le SERVEUR (op 'qm', table
// public.qm_item, verif_qm) comme « Questionner le monde » et EMC. Six
// sous-matieres (un domaine chacune), alignees sur les reperes CM1 d'eduscol :
//   ST.MATIERE.ETATS     etats de l'eau, changements d'etat, melanges et solutions, air ;
//   ST.VIVANT.CLASSER    classer le vivant, besoins des vegetaux, chaines alimentaires ;
//   ST.CORPS.SANTE       alimentation equilibree, hygiene de vie, trajet de la digestion ;
//   ST.ENERGIE.SOURCES   sources d'energie, renouvelables, economies a la maison ;
//   ST.OBJETS.TECHNIQUE  fonction d'usage, evolution d'un objet, circuits electriques simples ;
//   ST.TERRE.CIEL        systeme solaire, alternance jour/nuit, saisons.
// Progression N1 (CM1 d'emblee) -> N4 (reponse libre exigeante). Consignes pour
// l'oral, un exemple concret, ton bienveillant. Chaines alimentaires : « est
// mange par » (jamais « tue / devore »). Contenus originaux, exacts.

import { type QmItem, ordre, tri } from "../qm/types";

export const BANQUE_SCIENCES: QmItem[] = [
  // ===== ST.MATIERE.ETATS =====
  { cle: "st-mat-n1-a", competence: "ST.MATIERE.ETATS", niveau: 1, format: "qcm",
    consigne: "L'eau peut avoir plusieurs états. Sous quel état est l'eau d'une rivière ?",
    options: ["liquide", "solide", "gazeux"], attendu: "liquide",
    explication: "L'eau de la rivière coule : elle est liquide. L'eau peut aussi être solide (la glace) ou gazeuse (la vapeur)." },
  { cle: "st-mat-n1-b", competence: "ST.MATIERE.ETATS", niveau: 1, format: "qcm",
    consigne: "Quand l'eau devient très froide, elle gèle. Que devient-elle ?",
    options: ["de la glace", "de la vapeur", "du sable"], attendu: "de la glace",
    explication: "Quand l'eau gèle, elle devient de la glace, un solide. Cela arrive quand il fait très froid." },
  { cle: "st-mat-n2-a", competence: "ST.MATIERE.ETATS", niveau: 2, format: "tri",
    consigne: "Range chaque chose selon son état.",
    ...tri(["solide", "liquide", "gaz"], [["un glaçon", "solide"], ["le jus d'orange", "liquide"], ["l'air du ballon", "gaz"]]),
    explication: "Un glaçon garde sa forme : solide. Le jus coule : liquide. L'air remplit tout le ballon : c'est un gaz." },
  { cle: "st-mat-n2-b", competence: "ST.MATIERE.ETATS", niveau: 2, format: "qcm",
    consigne: "On chauffe une casserole d'eau. L'eau se transforme en vapeur. Comment s'appelle ce changement ?",
    options: ["l'évaporation", "la fonte", "le gel"], attendu: "l'évaporation",
    explication: "Quand l'eau chauffe et part dans l'air en vapeur, c'est l'évaporation. C'est pour cela qu'une flaque sèche au soleil." },
  { cle: "st-mat-n3-a", competence: "ST.MATIERE.ETATS", niveau: 3, format: "tri",
    consigne: "On mélange chaque chose avec de l'eau. Est-ce que ça se dissout ?",
    ...tri(["se dissout", "ne se dissout pas"], [["le sucre", "se dissout"], ["le sel", "se dissout"], ["le sable", "ne se dissout pas"], ["l'huile", "ne se dissout pas"]]),
    explication: "Le sucre et le sel disparaissent dans l'eau : ils se dissolvent. Le sable tombe au fond et l'huile flotte : ils ne se dissolvent pas." },
  { cle: "st-mat-n3-b", competence: "ST.MATIERE.ETATS", niveau: 3, format: "qcm",
    consigne: "Quand on mélange du sucre dans l'eau et qu'on ne voit plus le sucre, on obtient...",
    options: ["une solution", "un solide", "un glaçon"], attendu: "une solution",
    explication: "Quand le sucre se dissout complètement dans l'eau, on obtient une solution. L'eau sucrée est bien mélangée partout." },
  { cle: "st-mat-n4-a", competence: "ST.MATIERE.ETATS", niveau: 4, format: "texte",
    consigne: "La glace qui chauffe devient de l'eau liquide. Ce changement s'appelle la... Écris le mot.",
    attendu: "fonte",
    explication: "Quand la glace chauffe, elle fond : c'est la fonte. On dit aussi la fusion." },
  { cle: "st-mat-n4-b", competence: "ST.MATIERE.ETATS", niveau: 4, format: "texte",
    consigne: "L'air est partout autour de nous. Quand l'air se déplace dehors, cela fait du... Écris le mot.",
    attendu: "vent",
    explication: "L'air qui se déplace, c'est le vent. L'air est bien de la matière, même si on ne le voit pas." },
  // ===== ST.VIVANT.CLASSER =====
  { cle: "st-viv-n1-a", competence: "ST.VIVANT.CLASSER", niveau: 1, format: "qcm",
    consigne: "Dans quel groupe ranges-tu une truite et un requin ?",
    options: ["les poissons", "les oiseaux", "les plantes"], attendu: "les poissons",
    explication: "La truite et le requin vivent dans l'eau et ont des nageoires : ce sont des poissons." },
  { cle: "st-viv-n1-b", competence: "ST.VIVANT.CLASSER", niveau: 1, format: "qcm",
    consigne: "Un animal qui a des plumes et deux ailes, c'est un...",
    options: ["oiseau", "mammifère", "insecte"], attendu: "oiseau",
    explication: "Les plumes, c'est le signe des oiseaux. La mésange et l'aigle sont des oiseaux." },
  { cle: "st-viv-n2-a", competence: "ST.VIVANT.CLASSER", niveau: 2, format: "tri",
    consigne: "Classe chaque animal dans son groupe.",
    ...tri(["oiseau", "insecte"], [["la coccinelle", "insecte"], ["le moineau", "oiseau"], ["la fourmi", "insecte"], ["la mésange", "oiseau"]]),
    explication: "Les insectes (coccinelle, fourmi) ont six pattes. Les oiseaux (moineau, mésange) ont des plumes et un bec." },
  { cle: "st-viv-n2-b", competence: "ST.VIVANT.CLASSER", niveau: 2, format: "qcm",
    consigne: "Pour grandir, une plante a besoin d'eau, de lumière et de...",
    options: ["sels minéraux du sol", "bonbons", "piles"], attendu: "sels minéraux du sol",
    explication: "La plante boit l'eau et prend des sels minéraux dans le sol par ses racines. Elle a aussi besoin de lumière et d'air." },
  { cle: "st-viv-n3-a", competence: "ST.VIVANT.CLASSER", niveau: 3, format: "tri",
    consigne: "Une plante a-t-elle besoin de ces choses pour vivre ?",
    ...tri(["besoin", "pas besoin"], [["l'eau", "besoin"], ["la lumière", "besoin"], ["la musique", "pas besoin"], ["le chocolat", "pas besoin"]]),
    explication: "Une plante a besoin d'eau et de lumière pour grandir. La musique et le chocolat ne lui servent à rien." },
  { cle: "st-viv-n3-b", competence: "ST.VIVANT.CLASSER", niveau: 3, format: "ordre",
    consigne: "Range cette chaîne alimentaire : qui est mangé par qui ? Commence par la plante.",
    ...ordre(["l'herbe", "la sauterelle", "la grenouille"]),
    explication: "L'herbe est mangée par la sauterelle, qui est mangée par la grenouille. La plante est toujours au début de la chaîne." },
  { cle: "st-viv-n4-a", competence: "ST.VIVANT.CLASSER", niveau: 4, format: "texte",
    consigne: "Dans une chaîne alimentaire, l'être vivant qui est toujours au début et qui fabrique sa nourriture grâce au soleil, c'est la... Écris le mot.",
    attendu: "plante",
    explication: "La plante est au début de la chaîne : elle fabrique sa nourriture avec la lumière du soleil. On l'appelle un producteur." },
  { cle: "st-viv-n4-b", competence: "ST.VIVANT.CLASSER", niveau: 4, format: "texte",
    consigne: "Un animal qui mange seulement des plantes est un herbivore. Un animal qui mange seulement de la viande est un... Écris le mot.",
    attendu: "carnivore",
    explication: "Un carnivore mange de la viande. Un herbivore mange des plantes, et un omnivore mange des deux." },
  // ===== ST.CORPS.SANTE =====
  { cle: "st-cor-n1-a", competence: "ST.CORPS.SANTE", niveau: 1, format: "qcm",
    consigne: "Pour être en forme, combien de repas par jour est-ce bien de prendre ?",
    options: ["trois ou quatre repas", "un seul repas", "dix repas"], attendu: "trois ou quatre repas",
    explication: "Prendre trois ou quatre repas réguliers par jour aide le corps à avoir de l'énergie toute la journée." },
  { cle: "st-cor-n1-b", competence: "ST.CORPS.SANTE", niveau: 1, format: "qcm",
    consigne: "Quelle boisson est la meilleure pour la santé quand on a soif ?",
    options: ["l'eau", "le soda", "le sirop"], attendu: "l'eau",
    explication: "L'eau est la meilleure boisson : elle désaltère sans sucre. Les sodas contiennent beaucoup de sucre." },
  { cle: "st-cor-n2-a", competence: "ST.CORPS.SANTE", niveau: 2, format: "tri",
    consigne: "Range ces habitudes : bonnes ou moins bonnes pour la santé.",
    ...tri(["bon pour la santé", "moins bon"], [["manger des légumes", "bon pour la santé"], ["bien dormir", "bon pour la santé"], ["manger trop de bonbons", "moins bon"], ["rester assis toute la journée", "moins bon"]]),
    explication: "Manger des légumes et bien dormir aident à être en forme. Trop de bonbons et rester toujours assis, c'est moins bon." },
  { cle: "st-cor-n2-b", competence: "ST.CORPS.SANTE", niveau: 2, format: "qcm",
    consigne: "Par où commence le trajet des aliments quand tu manges ?",
    options: ["la bouche", "l'estomac", "le pied"], attendu: "la bouche",
    explication: "Le trajet des aliments commence par la bouche, où les dents coupent et écrasent la nourriture." },
  { cle: "st-cor-n3-a", competence: "ST.CORPS.SANTE", niveau: 3, format: "ordre",
    consigne: "Range le trajet des aliments dans le corps, du début à la fin.",
    ...ordre(["la bouche", "l'estomac", "l'intestin"]),
    explication: "Les aliments passent par la bouche, puis l'estomac, puis l'intestin. C'est le trajet de la digestion." },
  { cle: "st-cor-n3-b", competence: "ST.CORPS.SANTE", niveau: 3, format: "qcm",
    consigne: "Dans l'estomac, les aliments sont écrasés et mélangés. À quoi sert la digestion ?",
    options: ["donner de l'énergie au corps", "faire grandir les cheveux seulement", "rien du tout"], attendu: "donner de l'énergie au corps",
    explication: "La digestion transforme les aliments pour donner de l'énergie et des matériaux au corps pour grandir et bouger." },
  { cle: "st-cor-n4-a", competence: "ST.CORPS.SANTE", niveau: 4, format: "texte",
    consigne: "Transformer les aliments dans le corps pour en tirer de l'énergie, cela s'appelle la... Écris le mot.",
    attendu: "digestion",
    explication: "C'est la digestion. Elle commence dans la bouche et continue dans l'estomac et l'intestin." },
  { cle: "st-cor-n4-b", competence: "ST.CORPS.SANTE", niveau: 4, format: "texte",
    consigne: "Le soir, pour que le corps se repose et récupère, il faut bien... Écris le mot.",
    attendu: "dormir",
    explication: "Bien dormir aide le corps à récupérer. Un enfant a besoin de beaucoup de sommeil pour être en forme." },
  // ===== ST.ENERGIE.SOURCES =====
  { cle: "st-ene-n1-a", competence: "ST.ENERGIE.SOURCES", niveau: 1, format: "qcm",
    consigne: "Qu'est-ce qui donne de la lumière et de la chaleur à la Terre tous les jours ?",
    options: ["le Soleil", "la lune", "une chaise"], attendu: "le Soleil",
    explication: "Le Soleil donne de la lumière et de la chaleur. C'est une grande source d'énergie pour la Terre." },
  { cle: "st-ene-n1-b", competence: "ST.ENERGIE.SOURCES", niveau: 1, format: "qcm",
    consigne: "Qu'est-ce qui fait tourner les pales d'une éolienne ?",
    options: ["le vent", "l'eau du robinet", "le chocolat"], attendu: "le vent",
    explication: "Le vent fait tourner l'éolienne, qui fabrique de l'électricité. Le vent est une source d'énergie." },
  { cle: "st-ene-n2-a", competence: "ST.ENERGIE.SOURCES", niveau: 2, format: "tri",
    consigne: "Range chaque source d'énergie : vient de la nature sans s'épuiser, ou s'épuise un jour.",
    ...tri(["renouvelable", "s'épuise"], [["le soleil", "renouvelable"], ["le vent", "renouvelable"], ["le pétrole", "s'épuise"], ["le charbon", "s'épuise"]]),
    explication: "Le soleil et le vent reviennent toujours : ils sont renouvelables. Le pétrole et le charbon finiront par manquer." },
  { cle: "st-ene-n2-b", competence: "ST.ENERGIE.SOURCES", niveau: 2, format: "qcm",
    consigne: "Pour faire des économies d'énergie à la maison, que faut-il faire en sortant d'une pièce ?",
    options: ["éteindre la lumière", "allumer la télé", "ouvrir le frigo"], attendu: "éteindre la lumière",
    explication: "Éteindre la lumière quand on quitte une pièce fait des économies d'énergie. C'est un bon geste pour la planète." },
  { cle: "st-ene-n3-a", competence: "ST.ENERGIE.SOURCES", niveau: 3, format: "tri",
    consigne: "Est-ce un geste qui économise l'énergie à la maison ?",
    ...tri(["économise", "gaspille"], [["mettre un pull plutôt que monter le chauffage", "économise"], ["éteindre l'écran la nuit", "économise"], ["laisser l'eau chaude couler pour rien", "gaspille"], ["chauffer avec la fenêtre ouverte", "gaspille"]]),
    explication: "Mettre un pull et éteindre les écrans économise l'énergie. Laisser couler l'eau chaude ou chauffer fenêtre ouverte gaspille." },
  { cle: "st-ene-n3-b", competence: "ST.ENERGIE.SOURCES", niveau: 3, format: "qcm",
    consigne: "Dans une lampe de poche, qu'est-ce qui stocke l'énergie pour allumer l'ampoule ?",
    options: ["la pile", "le verre", "le plastique"], attendu: "la pile",
    explication: "La pile stocke de l'énergie. Elle la donne à l'ampoule pour faire de la lumière." },
  { cle: "st-ene-n4-a", competence: "ST.ENERGIE.SOURCES", niveau: 4, format: "texte",
    consigne: "L'énergie que les éoliennes et les barrages transforment pour allumer nos maisons s'appelle l'... Écris le mot.",
    attendu: "électricité",
    explication: "Les éoliennes et les barrages fabriquent de l'électricité. On s'en sert pour la lumière et les appareils." },
  { cle: "st-ene-n4-b", competence: "ST.ENERGIE.SOURCES", niveau: 4, format: "texte",
    consigne: "Le soleil, le vent et l'eau sont des sources d'énergie qui ne s'épuisent pas : on dit qu'elles sont... Écris le mot.",
    attendu: "renouvelables",
    explication: "Ces énergies sont renouvelables : elles reviennent sans cesse, contrairement au pétrole qui s'épuise." },
  // ===== ST.OBJETS.TECHNIQUE =====
  { cle: "st-obj-n1-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 1, format: "qcm",
    consigne: "À quoi sert un parapluie ? C'est sa fonction d'usage.",
    options: ["se protéger de la pluie", "écrire", "manger"], attendu: "se protéger de la pluie",
    explication: "La fonction d'un parapluie, c'est de nous protéger de la pluie. Chaque objet est fait pour un besoin." },
  { cle: "st-obj-n1-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 1, format: "qcm",
    consigne: "Dans une lampe, quelle partie s'allume et fait de la lumière ?",
    options: ["l'ampoule", "le fil", "l'interrupteur"], attendu: "l'ampoule",
    explication: "L'ampoule fait de la lumière. L'interrupteur sert à allumer, et les fils transportent l'électricité." },
  { cle: "st-obj-n2-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 2, format: "tri",
    consigne: "Associe chaque objet à sa fonction : à quoi il sert.",
    ...tri(["pour écrire", "pour couper", "pour mesurer"], [["le stylo", "pour écrire"], ["les ciseaux", "pour couper"], ["la règle", "pour mesurer"]]),
    explication: "Le stylo sert à écrire, les ciseaux à couper, la règle à mesurer. Chaque objet a une fonction." },
  { cle: "st-obj-n2-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 2, format: "qcm",
    consigne: "Dans un circuit électrique, à quoi sert l'interrupteur ?",
    options: ["ouvrir ou fermer le circuit", "faire du bruit", "donner à boire"], attendu: "ouvrir ou fermer le circuit",
    explication: "L'interrupteur ouvre ou ferme le circuit. Fermé, le courant passe et l'ampoule s'allume ; ouvert, elle s'éteint." },
  { cle: "st-obj-n3-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 3, format: "ordre",
    consigne: "Range ces objets pour éclairer, du plus ancien au plus récent.",
    ...ordre(["la bougie", "la lampe à huile", "l'ampoule électrique"]),
    explication: "D'abord la bougie, puis la lampe à huile, puis l'ampoule électrique. Les objets techniques évoluent avec le temps." },
  { cle: "st-obj-n3-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 3, format: "qcm",
    consigne: "Pour que l'ampoule brille, il faut une pile, des fils et une ampoule. Que faut-il pour que le courant passe ?",
    options: ["que le circuit soit fermé", "que le circuit soit ouvert", "qu'il fasse nuit"], attendu: "que le circuit soit fermé",
    explication: "Le courant passe seulement si le circuit est fermé, c'est-à-dire si tout est relié en boucle de la pile à l'ampoule." },
  { cle: "st-obj-n4-a", competence: "ST.OBJETS.TECHNIQUE", niveau: 4, format: "texte",
    consigne: "Le petit bouton qui permet d'allumer ou d'éteindre une lampe s'appelle l'... Écris le mot.",
    attendu: "interrupteur",
    explication: "C'est l'interrupteur. Il ouvre ou ferme le circuit pour allumer ou éteindre." },
  { cle: "st-obj-n4-b", competence: "ST.OBJETS.TECHNIQUE", niveau: 4, format: "texte",
    consigne: "Le métal laisse passer le courant électrique : on dit qu'il est un... Écris le mot.",
    attendu: "conducteur",
    explication: "Le métal est conducteur : le courant passe. Le plastique, lui, est isolant : le courant ne passe pas." },
  // ===== ST.TERRE.CIEL =====
  { cle: "st-ter-n1-a", competence: "ST.TERRE.CIEL", niveau: 1, format: "qcm",
    consigne: "Sur quelle planète vivons-nous ?",
    options: ["la Terre", "Mars", "le Soleil"], attendu: "la Terre",
    explication: "Nous vivons sur la Terre. C'est une planète qui tourne autour du Soleil." },
  { cle: "st-ter-n1-b", competence: "ST.TERRE.CIEL", niveau: 1, format: "qcm",
    consigne: "Le Soleil est au centre. La Terre et les autres planètes tournent autour. Comment appelle-t-on cet ensemble ?",
    options: ["le système solaire", "la forêt", "la ville"], attendu: "le système solaire",
    explication: "Le Soleil et les planètes qui tournent autour forment le système solaire." },
  { cle: "st-ter-n2-a", competence: "ST.TERRE.CIEL", niveau: 2, format: "qcm",
    consigne: "Pourquoi fait-il jour puis nuit, encore et encore ?",
    options: ["la Terre tourne sur elle-même", "le Soleil s'éteint", "la lune mange le Soleil"], attendu: "la Terre tourne sur elle-même",
    explication: "La Terre tourne sur elle-même en un jour. Le côté face au Soleil a le jour, l'autre côté a la nuit." },
  { cle: "st-ter-n2-b", competence: "ST.TERRE.CIEL", niveau: 2, format: "tri",
    consigne: "Range : est-ce le jour ou la nuit quand on voit ces choses dans le ciel ?",
    ...tri(["le jour", "la nuit"], [["le Soleil brille", "le jour"], ["les étoiles brillent", "la nuit"], ["il fait clair dehors", "le jour"], ["la lune éclaire", "la nuit"]]),
    explication: "Le Soleil et la lumière du ciel, c'est le jour. Les étoiles et la lune, c'est la nuit." },
  { cle: "st-ter-n3-a", competence: "ST.TERRE.CIEL", niveau: 3, format: "ordre",
    consigne: "Range les saisons de l'année dans l'ordre, en commençant par le printemps.",
    ...ordre(["le printemps", "l'été", "l'automne", "l'hiver"]),
    explication: "Les saisons se suivent : printemps, été, automne, hiver, puis ça recommence. Elles reviennent chaque année." },
  { cle: "st-ter-n3-b", competence: "ST.TERRE.CIEL", niveau: 3, format: "qcm",
    consigne: "La Terre met un an à faire un grand tour autour du Soleil. Qu'est-ce que cela crée au fil de l'année ?",
    options: ["les saisons", "les nuages", "les voitures"], attendu: "les saisons",
    explication: "Le tour de la Terre autour du Soleil en un an donne les saisons : printemps, été, automne, hiver." },
  { cle: "st-ter-n4-a", competence: "ST.TERRE.CIEL", niveau: 4, format: "texte",
    consigne: "L'étoile qui donne sa lumière à la Terre et autour de laquelle on tourne s'appelle le... Écris le mot.",
    attendu: "Soleil",
    explication: "C'est le Soleil, une étoile. La Terre tourne autour de lui en un an." },
  { cle: "st-ter-n4-b", competence: "ST.TERRE.CIEL", niveau: 4, format: "texte",
    consigne: "C'est parce que la Terre tourne sur elle-même qu'il y a, l'un après l'autre, le jour et la... Écris le mot.",
    attendu: "nuit",
    explication: "La Terre tourne sur elle-même : d'un côté le jour, de l'autre la nuit. Un tour complet dure un jour entier." },
];

export const COMPETENCES_SCIENCES = [
  "ST.MATIERE.ETATS",
  "ST.VIVANT.CLASSER",
  "ST.CORPS.SANTE",
  "ST.ENERGIE.SOURCES",
  "ST.OBJETS.TECHNIQUE",
  "ST.TERRE.CIEL",
] as const;
