// FICHIER GÉNÉRÉ (ne pas éditer à la main). Source : bibliothèque domaine
// public vérifiée (kerskol-kits/bibliotheque-domaine-public). Ne contient que
// des textes cycle 2 (CE1/CE2), utilisable=oui, ton=garde, et dont le CORPS ne
// contient aucun mot interdit (garde-fou bienveillance). Chaque texte porte son
// auteur, son œuvre, sa source, son glossaire « mots difficiles » et un
// emplacement librivoxUrl pour la future voix (bouton « Écouter » désactivé).
//
// Lecture SILENCIEUSE uniquement (décision Manu) : aucun audio ici.

export interface BiblioGlose {
  mot: string;
  sens: string;
}

export interface BiblioTexte {
  id: string;
  classe: "CE1" | "CE2";
  titre: string;
  oeuvre: string;
  auteur: string;
  auteurDeces: string;
  url: string; // source de vérification (domaine public)
  librivoxUrl: string; // enregistrement LibriVox à venir (vide pour l'instant)
  theme: string;
  corps: string[]; // paragraphes/strophes ; les retours à la ligne (\n) sont des vers
  glossaire: BiblioGlose[];
}

export const BIBLIOTHEQUE: BiblioTexte[] = [
  {
    id: "c2-079",
    classe: "CE2",
    titre: "La curiosité dans la rue",
    oeuvre: "Le Livre de mon ami",
    auteur: "Anatole France",
    auteurDeces: "1924",
    url: "https://fr.wikisource.org/wiki/Page:Anatole_France_-_Le_Livre_de_mon_ami.djvu/165",
    librivoxUrl: "",
    theme: "curiosité, rue",
    corps: [
      "La curiosité y était bonne et c'est pour aimer que je voulais connaître. Tout ce que je voyais en chemin dans la rue, les hommes, les bêtes, les choses, contribuait, plus qu'on ne saurait croire, à me faire sentir la vie dans ce qu'elle a de simple et de fort.",
      "Rien ne vaut la rue pour faire comprendre à un enfant la machine sociale. Il faut qu'il ait vu, au matin, les laitières, les porteurs d'eau, les charbonniers ; il faut qu'il ait examiné les boutiques de l'épicier, du charcutier et du marchand de vin ; il faut qu'il ait vu passer les régiments, musique en tête ; il faut enfin qu'il ait humé l'air de la rue, pour sentir que la loi du travail est divine et qu'il faut que chacun fasse sa tâche en ce monde.",
    ],
    glossaire: [
      { mot: "la machine sociale", sens: "la façon dont tous les gens vivent et travaillent ensemble." },
      { mot: "les laitières", sens: "les femmes qui vendaient le lait autrefois." },
      { mot: "les porteurs d'eau", sens: "les hommes qui apportaient l'eau dans les maisons autrefois." },
      { mot: "les charbonniers", sens: "les marchands qui vendaient le charbon pour se chauffer." },
      { mot: "les régiments", sens: "de grands groupes de soldats qui marchent ensemble." },
      { mot: "humer", sens: "respirer doucement pour sentir une odeur." },
    ],
  },
  {
    id: "c2-080",
    classe: "CE2",
    titre: "Les images d'Épinal",
    oeuvre: "Le Livre de mon ami",
    auteur: "Anatole France",
    auteurDeces: "1924",
    url: "https://fr.wikisource.org/wiki/Page:Anatole_France_-_Le_Livre_de_mon_ami.djvu/166",
    librivoxUrl: "",
    theme: "images, imagination",
    corps: [
      "Je dois avouer, pourtant, que je n'avais pas pour tous une amitié égale. Les papetiers qui étalent à la devanture de leur boutique des images d'Épinal furent d'abord mes préférés. Que de fois, le nez collé contre la vitre, j'ai lu d'un bout à l'autre la légende de ces petits drames figurés !",
      "J'en connus beaucoup en peu de temps : il y en avait de fantastiques qui faisaient travailler mon imagination et développaient en moi cette faculté sans laquelle on ne trouve rien, même en matière d'expériences et dans le domaine des sciences exactes.",
    ],
    glossaire: [
      { mot: "les papetiers", sens: "les marchands qui vendent du papier, des cahiers et des images." },
      { mot: "la devanture", sens: "la vitrine, l'avant d'une boutique où l'on expose ce qui est à vendre." },
      { mot: "les images d'Épinal", sens: "de jolies images colorées qui racontent une histoire, fabriquées dans la ville d'Épinal." },
      { mot: "la légende", sens: "le petit texte écrit sous une image pour expliquer ce qu'on voit." },
      { mot: "des drames figurés", sens: "de petites histoires racontées en dessins." },
      { mot: "cette faculté", sens: "ici, une capacité, quelque chose que l'esprit sait faire." },
    ],
  },
  {
    id: "c2-017",
    classe: "CE1",
    titre: "Le Hareng saur",
    oeuvre: "Le Coffret de santal - Le Hareng saur",
    auteur: "Charles Cros",
    auteurDeces: "1888",
    url: "https://fr.wikisource.org/wiki/Le_Coffret_de_santal_(éd._1879)/Le_Hareng_saur",
    librivoxUrl: "",
    theme: "humour, objets",
    corps: [
      "Il était un grand mur blanc - nu, nu, nu,\nContre le mur une échelle - haute, haute, haute,\nEt, par terre, un hareng saur - sec, sec, sec.",
      "Il vient, tenant dans ses mains - sales, sales, sales,\nUn marteau lourd, un grand clou - pointu, pointu, pointu,\nUn peloton de ficelle - gros, gros, gros.",
      "Alors il monte à l'échelle - haute, haute, haute,\nEt plante le clou pointu - toc, toc, toc,\nTout en haut du grand mur nu - nu, nu, nu.",
      "Il laisse aller le marteau - qui tombe, qui tombe, qui tombe,\nAttache au clou la ficelle - longue, longue, longue,\nEt, au bout, le hareng saur - sec, sec, sec.",
      "Il redescend de l'échelle - haute, haute, haute,\nL'emporte avec le marteau - lourd, lourd, lourd ;\nEt puis, il s'en va ailleurs - loin, loin, loin.",
      "Et, depuis, le hareng saur - sec, sec, sec,\nAu bout de cette ficelle - longue, longue, longue,\nTrès lentement se balance - toujours, toujours, toujours.",
      "J'ai composé cette histoire - simple, simple, simple,\nPour mettre en fureur les gens - graves, graves, graves,\nEt amuser les enfants - petits, petits, petits.",
    ],
    glossaire: [
      { mot: "un hareng saur", sens: "un poisson séché et fumé pour pouvoir le garder longtemps." },
      { mot: "un peloton de ficelle", sens: "une boule de fil enroulé." },
      { mot: "se balancer", sens: "bouger doucement d'un côté puis de l'autre." },
      { mot: "en fureur", sens: "très en colère." },
      { mot: "grave", sens: "ici, une personne très sérieuse qui ne rit jamais." },
    ],
  },
  {
    id: "c2-046",
    classe: "CE2",
    titre: "La marraine de Cendrillon",
    oeuvre: "Cendrillon ou la Petite Pantoufle de verre",
    auteur: "Charles Perrault",
    auteurDeces: "1703",
    url: "https://fr.wikisource.org/wiki/Page:Charles_Perrault_-_Les_Contes_de_Perrault,_edition_Feron,_Casterman,_1902.djvu/32",
    librivoxUrl: "https://librivox.org/contes-du-temps-passe-avec-des-moralites-by-charles-perrault/",
    theme: "merveilleux, famille",
    corps: [
      "Lorsqu’elle ne les vit plus, elle se mit à pleurer. Sa marraine, qui la vit tout en pleurs, lui demanda ce qu’elle avait, « Je voudrais bien… je voudrais bien… » Elle pleurait si fort qu’elle ne put achever. Sa marraine, qui était fée, lui dit : « Tu voudrais bien aller au bal, n’est-ce pas ? — Hélas ! oui, dit Cendrillon en soupirant. — Eh bien ! seras-tu bonne fille ? dit sa marraine, je t’y ferai aller. » — Elle la mena dans sa chambre, et lui dit : Va dans le jardin, et apporte-moi une citrouille. »",
    ],
    glossaire: [
      { mot: "une marraine", sens: "la personne qui protège et accompagne un enfant ; ici, c’est une fée." },
      { mot: "tout en pleurs", sens: "en train de pleurer beaucoup." },
      { mot: "achever", sens: "finir, terminer ce qu’on a commencé." },
      { mot: "une fée", sens: "un personnage magique qui peut faire des choses merveilleuses." },
      { mot: "le bal", sens: "une grande fête où l’on danse." },
      { mot: "une citrouille", sens: "un gros légume rond et orange." },
    ],
  },
  {
    id: "c2-057",
    classe: "CE2",
    titre: "Toby-Chien prend le train",
    oeuvre: "Douze dialogues de bêtes - Le voyage",
    auteur: "Colette",
    auteurDeces: "1954",
    url: "https://fr.wikisource.org/wiki/Page:Colette_-_Douze_dialogues_de_b%C3%AAtes,_1964.djvu/45",
    librivoxUrl: "",
    theme: "animaux, voyage",
    corps: [
      "*Dans un compartiment de 1re classe, Kiki-la-Doucette, Toby-Chien, Elle et Lui ont pris place. Le train roule vers les lointaines montagnes, vers l’été libre. Toby-Chien, en laisse, lève vers la vitre un nez affairé.*",
      "**Toby-Chien.** — Comme cette voiture va vite ! Ce n’est pas le même cocher que d’habitude. Je n’ai pas vu les chevaux, mais ils sentent bien mauvais et fument noir. Arrivera-t-on bientôt, ô Toi qui rêves silencieuse et ne me regardes pas ?",
      "**Elle.** — Chut !…",
      "**Toby-Chien.** — Je n’ai presque rien dit. Arriverons-nous bientôt ?",
    ],
    glossaire: [
      { mot: "un cocher", sens: "la personne qui conduit une voiture tirée par des chevaux (le chien croit que le train en est une)." },
      { mot: "affairé", sens: "qui a l’air très occupé, pressé." },
      { mot: "fumer noir", sens: "rejeter une fumée noire, comme la locomotive du train." },
      { mot: "Chut !", sens: "petit mot que l’on dit pour demander à quelqu’un de se taire." },
      { mot: "rêver silencieuse", sens: "être perdue dans ses pensées, sans parler." },
    ],
  },
  {
    id: "c2-058",
    classe: "CE2",
    titre: "Le nourrisson de Musette",
    oeuvre: "La Maison de Claudine - Ma mère et les bêtes",
    auteur: "Colette",
    auteurDeces: "1954",
    url: "https://fr.wikisource.org/wiki/Page:Colette_-_La_maison_de_Claudine,_1922.djvu/87",
    librivoxUrl: "",
    theme: "animaux, tendresse",
    corps: [
      "— Va voir, Minet-Chéri, le nourrisson de Musette !",
      "Je m’en fus à la cuisine où Musette nourrissait, en effet, un monstre à robe cendrée, encore presque aveugle, presque aussi gros qu’elle, un fils de chien de chasse qui tirait comme un veau sur les tétines délicates, d’un rose de fraise dans le poil d’argent, et foulait rythmiquement, de ses pattes onglées, un ventre soyeux qu’il eût déchiré, si… si sa mère n’eût taillé et cousu pour lui, dans une ancienne paire de gants blancs, des mitaines de daim qui lui montaient jusqu’au coude. Je n’ai jamais vu un chiot de dix jours ressembler autant à un gendarme.",
    ],
    glossaire: [
      { mot: "un nourrisson", sens: "un tout petit qui est encore nourri de lait (ici, un bébé chien)." },
      { mot: "une robe (d’animal)", sens: "la couleur du poil d’un animal ; « cendrée » veut dire gris clair." },
      { mot: "des tétines", sens: "les endroits du ventre de la femelle par où le lait sort pour nourrir les petits." },
      { mot: "des mitaines de daim", sens: "de petits gants en cuir souple, qui recouvrent ici les pattes du chiot." },
      { mot: "ressembler à un gendarme", sens: "Colette trouve que le chiot, avec ses gants, a l’air déguisé en petit soldat." },
    ],
  },
  {
    id: "c2-077",
    classe: "CE2",
    titre: "Le premier feu",
    oeuvre: "Douze dialogues de bêtes",
    auteur: "Colette",
    auteurDeces: "1954",
    url: "https://fr.wikisource.org/wiki/Page:Colette_-_Douze_dialogues_de_b%C3%AAtes,_1964.djvu/95",
    librivoxUrl: "",
    theme: "chat, chien",
    corps: [
      "Parce qu’il pleut et que le vent d’octobre chasse dans l’air les feuilles trempées, Elle a allumé dans la cheminée le premier feu de la saison. En extase, Kiki-la-Doucette et Toby-Chien, couchés côte à côte au coin du marbre tiède, s’éblouissent à contempler la flamme et lui dédient des prières intérieures.",
      "Kiki-la-Doucette (pareil à un coussin, sans pattes apparentes). — Feu ! te voici revenu, plus beau que mon souvenir, plus cuisant et plus proche que le soleil ! Feu ! que tu es splendide ! Par pudeur, je cache ma joie de te revoir, je ferme à demi mes yeux où ta lumière amincit la prunelle, et rien ne paraît sur ma figure où est peinte l’image d’une pensée fauve et brune… Mon ronron discret se perd dans ton crépitement. [...]",
    ],
    glossaire: [
      { mot: "en extase", sens: "rempli d’admiration, émerveillé." },
      { mot: "contempler", sens: "regarder longtemps avec plaisir." },
      { mot: "par pudeur", sens: "par discrétion, pour ne pas trop montrer ses sentiments." },
      { mot: "la prunelle", sens: "le petit rond noir au centre de l’œil." },
      { mot: "fauve", sens: "ici, d’une couleur brun-jaune comme le pelage du lion." },
      { mot: "le crépitement", sens: "le petit bruit sec que fait le feu qui brûle." },
    ],
  },
  {
    id: "c2-078",
    classe: "CE2",
    titre: "Le jeune chat",
    oeuvre: "La Maison de Claudine",
    auteur: "Colette",
    auteurDeces: "1954",
    url: "https://fr.wikisource.org/wiki/Page:Colette_-_La_maison_de_Claudine,_1922.djvu/234",
    librivoxUrl: "",
    theme: "chaton, jeu",
    corps: [
      "Il sera donc beau, il est déjà ravissant, et nous essayons de le nommer Kamaralzaman — en vain, car la cuisinière et la femme de chambre, qui sont des personnes raisonnables, traduisent Kamaralzaman par Moumou. Il est un jeune chat, gracieux à toute heure. La boule de papier l’intéresse, l’odeur de la viande le change en dragon rugissant et minuscule, les passereaux volent trop vite pour qu’il puisse les suivre de l’œil, mais il devient cataleptique, derrière la vitre, quand ils picorent sur la fenêtre. Il fait beaucoup de bruit en tétant, parce que ses dents poussent…",
    ],
    glossaire: [
      { mot: "ravissant", sens: "très joli, très beau." },
      { mot: "gracieux", sens: "qui a des gestes doux et élégants." },
      { mot: "rugissant", sens: "qui pousse un cri puissant comme le lion." },
      { mot: "les passereaux", sens: "de petits oiseaux comme les moineaux." },
      { mot: "cataleptique", sens: "ici, figé, immobile comme une statue." },
      { mot: "téter", sens: "boire le lait de sa maman." },
    ],
  },
  {
    id: "c2-045",
    classe: "CE2",
    titre: "La famille de Gribouille",
    oeuvre: "Histoire du véritable Gribouille",
    auteur: "George Sand",
    auteurDeces: "1876",
    url: "https://fr.wikisource.org/wiki/Page:Sand_-_Histoire_du_veritable_Gribouille.djvu/15",
    librivoxUrl: "",
    theme: "famille, nature",
    corps: [
      "Il y avait une fois un père et une mère qui avaient un fils. Le fils s’appelait Gribouille, la mère s’appelait Brigoule et le père Bredouille. Le père et la mère avaient six autres enfants, trois garçons et trois filles, ce qui faisait sept, en comptant Gribouille qui était le plus petit.",
      "Le père Bredouille était garde-chasse du roi de ce pays-là, ce qui le mettait bien à son aise. Il avait une jolie maison au beau milieu de la forêt, avec un joli jardin dans une jolie clairière, au bord d’un joli ruisseau qui passait tout au travers du bois.",
    ],
    glossaire: [
      { mot: "un garde-chasse", sens: "la personne qui surveille une forêt et les animaux pour le propriétaire." },
      { mot: "être bien à son aise", sens: "avoir assez d’argent pour vivre tranquillement." },
      { mot: "une clairière", sens: "un endroit sans arbres au milieu d’une forêt." },
      { mot: "un ruisseau", sens: "un tout petit cours d’eau." },
      { mot: "au travers du bois", sens: "à travers la forêt, en la traversant." },
    ],
  },
  {
    id: "c2-070",
    classe: "CE2",
    titre: "Ce que disent les fleurs",
    oeuvre: "Contes d'une grand-mère - Ce que disent les fleurs",
    auteur: "George Sand",
    auteurDeces: "1876",
    url: "https://www.gutenberg.org/cache/epub/12338/pg12338.txt",
    librivoxUrl: "",
    theme: "nature, jardin",
    corps: [
      "Quand j'étais enfant, ma chère Aurore, j'étais très-tourmentée de ne pouvoir saisir ce que les fleurs se disaient entre elles. [...] Je les entendais babiller confusément, surtout à la rosée du soir; mais elles parlaient trop bas pour que je pusse distinguer leurs paroles; et puis elles étaient méfiantes, et, quand je passais près des plates-bandes du jardin ou sur le sentier du pré, elles s'avertissaient par une espèce de psitt, qui courait de l'une à l'autre. [...] Je m'exerçai à marcher si doucement, sans frôler le plus petit brin d'herbe, qu'elles ne m'entendirent plus. [...] Il fallait beaucoup d'attention; c'était de si petites voix, si douces, si fines, que la moindre brise les emportait.",
    ],
    glossaire: [
      { mot: "babiller", sens: "parler beaucoup à voix basse, bavarder gentiment." },
      { mot: "la rosée", sens: "les petites gouttes d'eau qui se posent sur les plantes le matin ou le soir." },
      { mot: "une plate-bande", sens: "une bande de terre du jardin où l'on fait pousser des fleurs." },
      { mot: "méfiant", sens: "qui se méfie, qui n'a pas confiance." },
    ],
  },
  {
    id: "c2-071",
    classe: "CE2",
    titre: "La petite Bichette",
    oeuvre: "Contes d'une grand-mère - Le Nuage rose",
    auteur: "George Sand",
    auteurDeces: "1876",
    url: "https://fr.wikisource.org/wiki/Contes_d%E2%80%99une_grand%E2%80%99m%C3%A8re/Le_Nuage_rose",
    librivoxUrl: "",
    theme: "tendresse, animaux",
    corps: [
      "Catherine avait trois brebis à garder. Elle ne savait encore ni lire ni écrire ; mais elle ne causait pas trop mal, et c’était une très-bonne fille, seulement un peu curieuse et changeant de caprice volontiers, ce qui prouve qu’au moins elle n’était pas têtue. Un peu après la Noël, ses trois brebis lui donnèrent trois agneaux, deux très-forts et le troisième si petit, si petit, qu’on eût dit un petit lapin. [...] Elle se promit d’en avoir grand soin, et lui donna le nom de Bichette, car c’était une agnèle. [...] elle la caressait sans cesse, elle la portait dans ses bras, elle la faisait dormir sur ses genoux.",
    ],
    glossaire: [
      { mot: "une brebis", sens: "la femelle du mouton." },
      { mot: "un agneau", sens: "le petit du mouton." },
      { mot: "une agnèle", sens: "une petite femelle agneau." },
      { mot: "un caprice", sens: "une envie soudaine qui change vite." },
    ],
  },
  {
    id: "c2-072",
    classe: "CE2",
    titre: "Clopinet rêve de la mer",
    oeuvre: "Contes d'une grand-mère - Les Ailes de courage",
    auteur: "George Sand",
    auteurDeces: "1876",
    url: "https://fr.wikisource.org/wiki/Contes_d%E2%80%99une_grand%E2%80%99m%C3%A8re/Les_Ailes_de_courage",
    librivoxUrl: "",
    theme: "campagne, rêve",
    corps: [
      "Il y avait dans les terres du pays d’Auge, du côté de Saint-Pierre-d’Azif, à trois lieues de la mer, un bon paysan et sa femme qui, à force de travail, étaient devenus assez riches. [...] C’étaient des herbages et puis des herbages, avec des pommiers et encore des pommiers ; un grand pays tout plat, à perte de vue, et de temps en temps un petit bois de noisetiers, avec un jardinet et une maison de bois et de torchis, la pierre étant rare. On élevait par là de bonnes vaches, on faisait d’excellent beurre et des fromages renommés [...]. Il y en avait un seul, qu’on appelait Clopinet [...] ; il était frais et fort, quoiqu’un peu boiteux, très-joli de visage et rose comme une pomme. [...] il avait une idée à lui, et cette idée, c’était d’être marin.",
    ],
    glossaire: [
      { mot: "un herbage", sens: "un pré où pousse l'herbe pour les animaux." },
      { mot: "une lieue", sens: "une ancienne mesure de distance (environ quatre kilomètres)." },
      { mot: "le torchis", sens: "un mélange de terre et de paille pour bâtir les murs." },
      { mot: "un marin", sens: "une personne qui travaille sur un bateau, en mer." },
    ],
  },
  {
    id: "c2-052",
    classe: "CE2",
    titre: "Que la campagne était belle !",
    oeuvre: "Le Vilain Petit Canard",
    auteur: "Hans Christian Andersen",
    auteurDeces: "1875",
    url: "https://fr.wikisource.org/wiki/Page:Andersen_-_Contes_d'Andersen,_traduit_par_Soldi,_Librairie_Hachette_et_Cie,_1876.djvu/295",
    librivoxUrl: "https://librivox.org/contes-et-histoires-preferes-des-enfants-001/",
    theme: "animaux, nature",
    corps: [
      "Que la campagne était belle ! On était au milieu de l’été ; les blés agitaient des épis d’un jaune magnifique, l’avoine était verte, et dans les prairies le foin s’élevait en monceaux odorants ; la cigogne se promenait sur ses longues jambes rouges, en bavardant de l’égyptien, langue qu’elle avait apprise de madame sa mère. Autour des champs et des prairies s’étendaient de grandes forêts coupées de lacs profonds.",
      "Oui vraiment, la campagne était bien belle. Les rayons du soleil éclairaient de tout leur éclat un vieux domaine entouré de larges fossés, et de grandes feuilles de bardane descendaient du mur jusques dans l’eau ; elles étaient si hautes que les petits enfants pouvaient se cacher dessous.",
    ],
    glossaire: [
      { mot: "un épi", sens: "le haut de la tige de blé, où se trouvent les grains." },
      { mot: "l’avoine", sens: "une plante des champs, comme le blé." },
      { mot: "un monceau", sens: "un gros tas." },
      { mot: "odorant", sens: "qui sent bon, qui a une bonne odeur." },
      { mot: "une cigogne", sens: "un grand oiseau blanc et noir, à longues pattes." },
      { mot: "la bardane", sens: "une plante à très grandes feuilles." },
    ],
  },
  {
    id: "c2-054",
    classe: "CE2",
    titre: "Le grain d'orge magique",
    oeuvre: "La Petite Poucette",
    auteur: "Hans Christian Andersen",
    auteurDeces: "1875",
    url: "https://fr.wikisource.org/wiki/Page:Andersen_-_Contes_d'Andersen,_traduit_par_Soldi,_Librairie_Hachette_et_Cie,_1876.djvu/242",
    librivoxUrl: "",
    theme: "merveilleux, nature",
    corps: [
      "Une femme désirait beaucoup avoir un petit enfant ; mais, ne sachant comment y parvenir, elle alla trouver une vieille sorcière et lui dit : « Je voudrais avoir un petit enfant ; dis-moi ce qu’il faut faire pour cela.",
      "— Ce n’est pas bien difficile, répondit la sorcière ; voici un grain d’orge qui n’est pas de la nature de celle qui croît dans les champs du paysan ou que mangent les poules. Mets-le dans un pot de fleurs, et tu verras.",
      "— Merci, » dit la femme, en donnant douze sous à la sorcière. Puis elle rentra chez elle et planta le grain d’orge.",
    ],
    glossaire: [
      { mot: "parvenir", sens: "réussir, arriver à faire quelque chose." },
      { mot: "une sorcière", sens: "une femme qui connaît des formules magiques." },
      { mot: "un grain d’orge", sens: "une petite graine d’orge, une céréale comme le blé." },
      { mot: "croître", sens: "pousser, grandir." },
      { mot: "des sous", sens: "des pièces de monnaie, de l’argent." },
      { mot: "planter", sens: "mettre une graine dans la terre pour qu’elle pousse." },
    ],
  },
  {
    id: "c2-011",
    classe: "CE1",
    titre: "Le Corbeau et le Renard",
    oeuvre: "Fables, Livre I, 2 - Le Corbeau et le Renard",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/Le_Corbeau_et_le_Renard",
    librivoxUrl: "https://archive.org/details/fables_de_la_fontaine_01_jl_0809_librivox",
    theme: "animaux",
    corps: [
      "Maître corbeau, sur un arbre perché,\nTenait en son bec un fromage.\nMaître renard, par l'odeur alléché,\nLui tint à peu près ce langage :\nHé ! bonjour, monsieur du corbeau.\nQue vous êtes joli ! que vous me semblez beau !\nSans mentir, si votre ramage\nSe rapporte à votre plumage,\nVous êtes le phénix des hôtes de ces bois.\nÀ ces mots le corbeau ne se sent pas de joie ;\nEt, pour montrer sa belle voix,\nIl ouvre un large bec, laisse tomber sa proie.\nLe renard s'en saisit, et dit : Mon bon monsieur,\nApprenez que tout flatteur\nVit aux dépens de celui qui l'écoute :\nCette leçon vaut bien un fromage, sans doute.\nLe corbeau, honteux et confus,\nJura, mais un peu tard, qu'on ne l'y prendrait plus.",
    ],
    glossaire: [
      { mot: "perché", sens: "posé en haut, tout en hauteur. L'oiseau est perché sur la branche." },
      { mot: "alléché", sens: "attiré par quelque chose de bon à manger." },
      { mot: "le ramage", sens: "le chant des oiseaux." },
      { mot: "le plumage", sens: "toutes les plumes d'un oiseau." },
      { mot: "un flatteur", sens: "une personne qui dit de belles choses pour tromper les autres." },
      { mot: "vivre aux dépens de", sens: "profiter de quelqu'un, vivre à ses frais." },
    ],
  },
  {
    id: "c2-012",
    classe: "CE1",
    titre: "Le Lièvre et la Tortue",
    oeuvre: "Fables, Livre VI, 10 - Le Lièvre et la Tortue",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/Le_Lièvre_et_la_Tortue",
    librivoxUrl: "https://archive.org/details/fables_de_la_fontaine_06_jl_librivox",
    theme: "animaux",
    corps: [
      "Rien ne sert de courir ; il faut partir à point :\nLe lièvre et la tortue en sont un témoignage.\nGageons, dit celle-ci, que vous n'atteindrez point\nSitôt que moi ce but. Sitôt ! êtes-vous sage ?\nRepartit l'animal léger :\nMa commère, il vous faut purger\nAvec quatre grains d'ellébore.\n- Sage ou non, je parie encore.\nAinsi fut fait ; et de tous deux\nOn mit près du but les enjeux.\nSavoir quoi, ce n'est pas l'affaire,\nNi de quel juge l'on convint.\nNotre lièvre n'avait que quatre pas à faire ;\nJ'entends de ceux qu'il fait lorsque, près d'être atteint,\nIl s'éloigne des chiens, les renvoie aux calendes,\nEt leur fait arpenter les landes.\nAyant, dis-je, du temps de reste pour brouter,\nPour dormir, et pour écouter\nD'où vient le vent, il laisse la tortue\nAller son train de sénateur.\nElle part, elle s'évertue ;\nElle se hâte avec lenteur.\nLui cependant méprise une telle victoire,\nTient la gageure à peu de gloire,\nCroit qu'il y va de son honneur\nDe partir tard. Il broute, il se repose ;\nIl s'amuse à toute autre chose\nQu'à la gageure. À la fin, quand il vit\nQue l'autre touchait presque au bout de la carrière,\nIl partit comme un trait ; mais les élans qu'il fit\nFurent vains : la tortue arriva la première.\nEh bien ! lui cria-t-elle, avais-je pas raison ?\nDe quoi vous sert votre vitesse ?\nMoi l'emporter ! et que serait-ce\nSi vous portiez une maison ?",
    ],
    glossaire: [
      { mot: "partir à point", sens: "partir au bon moment, ni trop tôt ni trop tard." },
      { mot: "gager / une gageure", sens: "faire un pari ; la gageure, c'est le pari." },
      { mot: "une commère", sens: "ici, une façon amicale et familière d'appeler quelqu'un." },
      { mot: "s'évertuer", sens: "faire de gros efforts." },
      { mot: "se hâter", sens: "se dépêcher, aller vite." },
      { mot: "la carrière", sens: "ici, le chemin de la course, la piste jusqu'au but." },
    ],
  },
  {
    id: "c2-013",
    classe: "CE1",
    titre: "Le Rat de ville et le Rat des champs",
    oeuvre: "Fables, Livre I, 9 - Le Rat de ville et le Rat des champs",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/Le_Rat_de_Ville,_et_le_Rat_des_Champs",
    librivoxUrl: "https://archive.org/details/fables_de_la_fontaine_01_jl_0809_librivox",
    theme: "animaux",
    corps: [
      "Autrefois le rat de ville\nInvita le rat des champs,\nD'une façon fort civile,\nÀ des reliefs d'ortolans.",
      "Sur un tapis de Turquie\nLe couvert se trouva mis.\nJe laisse à penser la vie\nQue firent ces deux amis.",
      "Le régal fut fort honnête ;\nRien ne manquait au festin :\nMais quelqu'un troubla la fête\nPendant qu'ils étaient en train.",
      "À la porte de la salle\nIls entendirent du bruit :\nLe rat de ville détale ;\nSon camarade le suit.",
      "Le bruit cesse, on se retire :\nRats en campagne aussitôt ;\nEt le citadin de dire :\nAchevons tout notre rôt.",
      "C'est assez, dit le rustique :\nDemain vous viendrez chez moi.\nCe n'est pas que je me pique\nDe tous vos festins de roi :",
      "Mais rien ne vient m'interrompre ;\nJe mange tout à loisir.\nAdieu donc. Fi du plaisir\nQue la crainte peut corrompre !",
    ],
    glossaire: [
      { mot: "civile", sens: "polie, aimable." },
      { mot: "des reliefs", sens: "les restes d'un repas." },
      { mot: "un ortolan", sens: "un petit oiseau que l'on mangeait autrefois dans les grands repas." },
      { mot: "le régal / le festin", sens: "un très bon repas de fête." },
      { mot: "détaler", sens: "se sauver très vite." },
      { mot: "le rôt", sens: "la viande rôtie ; ici, le repas." },
    ],
  },
  {
    id: "c2-014",
    classe: "CE1",
    titre: "Le Lion et le Rat",
    oeuvre: "Fables, Livre II, 11 - Le Lion et le Rat",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/Le_Lion_et_le_Rat",
    librivoxUrl: "",
    theme: "animaux",
    corps: [
      "Il faut, autant qu'on peut, obliger tout le monde :\nOn a souvent besoin d'un plus petit que soi.\nDe cette vérité deux fables feront foi ;\nTant la chose en preuves abonde.",
      "Entre les pattes d'un lion\nUn rat sortit de terre assez à l'étourdie.\nLe roi des animaux, en cette occasion,\nMontra ce qu'il était, et lui donna la vie.\nCe bienfait ne fut pas perdu.\nQuelqu'un aurait-il jamais cru\nQu'un lion d'un rat eût affaire ?\nCependant il advint qu'au sortir des forêts\nCe lion fut pris dans des rets,\nDont ses rugissements ne le purent défaire.\nSire rat accourut, et fit tant par ses dents\nQu'une maille rongée emporta tout l'ouvrage.",
      "Patience et longueur de temps\nFont plus que force ni que rage.",
    ],
    glossaire: [
      { mot: "obliger quelqu'un", sens: "lui rendre service, l'aider." },
      { mot: "à l'étourdie", sens: "sans faire attention, sans réfléchir." },
      { mot: "un bienfait", sens: "une bonne action que l'on fait pour aider quelqu'un." },
      { mot: "des rets", sens: "un filet pour attraper les animaux." },
      { mot: "une maille", sens: "chacun des petits trous ou nœuds qui forment un filet." },
      { mot: "ronger", sens: "user en grignotant avec ses dents." },
    ],
  },
  {
    id: "c2-022",
    classe: "CE2",
    titre: "Le Renard et la Cigogne",
    oeuvre: "Fables, Livre I",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Page:La_Fontaine_-_Fables,_Bernardin-Bechet,_1874.djvu/62",
    librivoxUrl: "https://archive.org/details/fables_de_la_fontaine_01_jl_0809_librivox",
    theme: "animaux",
    corps: [
      "Compère le renard se mit un jour en frais,\nEt retint à dîner commère la cigogne.\nLe régal fut petit et sans beaucoup d’apprêts :\nLe galant, pour toute besogne,\nAvait un brouet clair ; il vivait chichement.\nCe brouet fut par lui servi sur une assiette :\nLa cigogne au long bec n’en put attraper miette ;\nEt le drôle eut lapé le tout en un moment.\nPour se venger de cette tromperie,\nÀ quelque temps de là la cigogne le prie.\nVolontiers, lui dit-il ; car avec mes amis\nJe ne fais point cérémonie.\nÀ l’heure dite, il courut au logis\nDe la cigogne son hôtesse ;\nLoua très-fort sa politesse ;\nTrouva le dîner cuit à point :\nBon appétit surtout ; renards n’en manquent point.\nIl se réjouissait à l’odeur de la viande\nMise en menus morceaux, et qu’il croyait friande.\nOn servit, pour l’embarrasser,\nEn un vase à long col et d’étroite embouchure.\nLe bec de la cigogne y pouvait bien passer ;\nMais le museau du sire était d’autre mesure.\nIl lui fallut à jeun retourner au logis,\nHonteux comme un renard qu’une poule aurait pris,\nSerrant la queue, et portant bas l’oreille.\nTrompeurs, c’est pour vous que j’écris :\nAttendez-vous à la pareille.",
    ],
    glossaire: [
      { mot: "un compère / une commère", sens: "un ami, un camarade (c'est une façon amusante de parler des animaux)." },
      { mot: "un brouet", sens: "une soupe claire, pas bonne et sans grand-chose dedans." },
      { mot: "chichement", sens: "en donnant très peu, sans générosité." },
      { mot: "l'embouchure", sens: "l'ouverture, l'entrée étroite du vase par où l'on boit." },
      { mot: "à jeun", sens: "sans avoir mangé, le ventre vide." },
    ],
  },
  {
    id: "c2-027",
    classe: "CE2",
    titre: "Le Héron",
    oeuvre: "Fables, Livre VII",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Page:La_Fontaine_-_Fables,_Bernardin-Bechet,_1874.djvu/234",
    librivoxUrl: "https://archive.org/details/fables_de_la_fontaine_07_jl_librivox",
    theme: "animaux",
    corps: [
      "Un jour, sur ses longs pieds, allait je ne sais où\nLe héron au long bec emmanché d’un long cou :\nIl côtoyait une rivière.\nL’onde était transparente ainsi qu’aux plus beaux jours ;\nMa commère la carpe y faisait mille tours\nAvec le brochet son compère.\nLe héron en eût fait aisément son profit :\nTous approchaient du bord ; l’oiseau n’avait qu’à prendre.\nMais il crut mieux faire d’attendre\nQu’il eût un peu plus d’appétit :\nIl vivait de régime, et mangeait à ses heures.\nAprès quelques moments l’appétit vint : l’oiseau,\nS’approchant du bord, vit sur l’eau\nDes tanches qui sortaient du fond de ces demeures.\nLe mets ne lui plut pas, il s’attendait à mieux,\nEt montrait un goût dédaigneux\nComme le rat du bon Horace.\nMoi, des tanches ! dit-il ; moi, héron, que je fasse\nUne si pauvre chère ! Et pour qui me prend-on ?\nLa tanche rebutée, il trouva du goujon.\nDu goujon ! c’est bien là le dîner d’un héron !\nJ’ouvrirais pour si peu le bec ! aux dieux ne plaise !\nIl l’ouvrit pour bien moins : tout alla de façon\nQu’il ne vit plus aucun poisson.\nLa faim le prit : il fut tout heureux et tout aise\nDe rencontrer un limaçon.\nNe soyons pas si difficiles :\nLes plus accommodants, ce sont les plus habiles ;\nOn hasarde de perdre en voulant trop gagner.\nGardez-vous de rien dédaigner,\nSurtout quand vous avez à peu près votre compte.\nBien des gens y sont pris. Ce n’est pas aux hérons\nQue je parle : écoutez, humains, un autre conte :\nVous verrez que chez vous j’ai puisé ces leçons.",
    ],
    glossaire: [
      { mot: "un héron", sens: "un grand oiseau avec de longues pattes et un long bec, qui vit au bord de l'eau." },
      { mot: "côtoyer", sens: "marcher le long de quelque chose. Le héron longe la rivière." },
      { mot: "une tanche / un goujon", sens: "des petits poissons de rivière." },
      { mot: "dédaigneux", sens: "qui fait le difficile, qui trouve que ce n'est pas assez bien pour lui." },
      { mot: "un limaçon", sens: "un escargot." },
    ],
  },
  {
    id: "c2-028",
    classe: "CE2",
    titre: "Le Coche et la Mouche",
    oeuvre: "Fables, Livre VII",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Page:La_Fontaine_-_Fables,_Bernardin-Bechet,_1874.djvu/242",
    librivoxUrl: "https://archive.org/details/fables_de_la_fontaine_07_jl_librivox",
    theme: "animaux",
    corps: [
      "Dans un chemin montant, sablonneux, malaisé,\nEt de tous les côtés au soleil exposé,\nSix forts chevaux tiraient un coche.\nFemmes, moine, vieillards, tout était descendu :\nL’attelage suait, soufflait, était rendu.\nUne mouche survient, et des chevaux s’approche,\nPrétend les animer par son bourdonnement,\nPique l’un, pique l’autre, et pense à tout moment\nQu’elle fait aller la machine,\nS’assied sur le timon, sur le nez du cocher.\nAussitôt que le char chemine,\nEt qu’elle voit les gens marcher,\nElle s’en attribue uniquement la gloire,\nVa, vient, fait l’empressée : il semble que ce soit\nUn sergent de bataille allant en chaque endroit\nFaire avancer ses gens et hâter la victoire.\nLa mouche, en ce commun besoin,\nSe plaint qu’elle agit seule, et qu’elle a tout le soin ;\nQu’aucun n’aide aux chevaux à se tirer d’affaire.\nLe moine disait son bréviaire :\nIl prenait bien son temps ! une femme chantait :\nC’était bien de chansons qu’alors il s’agissait !\nDame mouche s’en va chanter à leurs oreilles,\nEt fait cent sottises pareilles.\nAprès bien du travail, le coche arrive au haut.\nRespirons maintenant ! dit la mouche aussitôt :\nJ’ai tant fait que nos gens sont enfin dans la plaine.\nÇà, messieurs les chevaux, payez-moi de ma peine.\nAinsi certaines gens, faisant les empressés,\nS’introduisent dans les affaires :\nIls font partout les nécessaires,\nEt, partout importuns, devraient être chassés.",
    ],
    glossaire: [
      { mot: "un coche", sens: "une grande voiture tirée par des chevaux, qui transportait les voyageurs autrefois." },
      { mot: "l'attelage", sens: "les chevaux attachés ensemble pour tirer la voiture." },
      { mot: "le timon", sens: "la longue barre de bois à laquelle on attache les chevaux." },
      { mot: "un bréviaire", sens: "le livre de prières que lit le moine." },
      { mot: "importun", sens: "qui gêne, qui dérange tout le monde." },
    ],
  },
  {
    id: "c2-074",
    classe: "CE2",
    titre: "Le Gland et la Citrouille (extrait)",
    oeuvre: "Fables, Livre IX, 4 - Le Gland et la Citrouille",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Page:La_Fontaine_-_Fables,_Bernardin-Bechet,_1874.djvu/321",
    librivoxUrl: "",
    theme: "humour, sagesse",
    corps: [
      "Dieu fait bien ce qu'il fait. Sans en chercher la preuve\nEn tout cet univers, et l'aller parcourant,\nDans les citrouilles je la treuve.",
      "Un villageois, considérant\nCombien ce fruit est gros et sa tige menue :\nÀ quoi songeait, dit-il, l'auteur de tout cela ?\nIl a bien mal placé cette citrouille-là !\nEh parbleu ! je l'aurais pendue\nÀ l'un des chênes que voilà ;\nC'eût été justement l'affaire :\nTel fruit, tel arbre, pour bien faire.",
      "[...]",
      "Sous un chêne aussitôt il va prendre son somme.\nUn gland tombe : le nez du dormeur en pâtit.\nIl s'éveille ; et, portant la main sur son visage,\nIl trouve encor le gland pris au poil du menton.",
      "[...]",
      "Dieu ne l'a pas voulu : sans doute il eut raison ;\nJ'en vois bien à présent la cause.\nEn louant Dieu de toute chose\nGaro retourne à la maison.",
    ],
    glossaire: [
      { mot: "je la treuve", sens: "je la trouve (ancienne façon de dire « trouve »)." },
      { mot: "la tige menue", sens: "la petite tige toute fine." },
      { mot: "Eh parbleu !", sens: "exclamation de surprise, comme « eh bien ! »." },
      { mot: "prendre son somme", sens: "faire un petit somme, dormir un moment." },
      { mot: "en pâtit", sens: "en souffre un peu, en reçoit l'ennui." },
      { mot: "louant Dieu", sens: "disant merci à Dieu, le remerciant." },
    ],
  },
  {
    id: "c2-018",
    classe: "CE1",
    titre: "Le Grillon (extrait)",
    oeuvre: "Fables de Florian - Le Grillon",
    auteur: "Jean-Pierre Claris de Florian",
    auteurDeces: "1794",
    url: "https://fr.wikisource.org/wiki/Fables_de_Florian_(1838)/2/Le_Grillon",
    librivoxUrl: "",
    theme: "animaux, nature",
    corps: [
      "Un pauvre petit grillon\nCaché dans l'herbe fleurie,\nRegardait un papillon\nVoltigeant dans la prairie.",
      "[...]",
      "Oh ! oh ! dit le grillon, je ne suis plus fâché ;\nIl en coûte trop cher pour briller dans le monde.\nCombien je vais aimer ma retraite profonde !\nPour vivre heureux vivons caché.",
    ],
    glossaire: [
      { mot: "un grillon", sens: "un petit insecte noir qui chante le soir dans l'herbe." },
      { mot: "voltiger", sens: "voler légèrement de-ci de-là, comme un papillon." },
      { mot: "briller dans le monde", sens: "se faire remarquer, être admiré de tous." },
      { mot: "une retraite", sens: "ici, un endroit tranquille où l'on se cache pour être en paix." },
    ],
  },
  {
    id: "c2-076",
    classe: "CE2",
    titre: "Le Chat et le Miroir (extrait)",
    oeuvre: "Fables de Florian, Livre I - Le Chat et le Miroir",
    auteur: "Jean-Pierre Claris de Florian",
    auteurDeces: "1794",
    url: "https://fr.wikisource.org/wiki/Page:Florian_-_Fables,_illustrations_Adam,_1838.djvu/62",
    librivoxUrl: "",
    theme: "humour, animaux",
    corps: [
      "[...]",
      "Sur une table de toilette\nCe chat aperçut un miroir ;\nIl y saute, regarde, et d'abord pense voir\nUn de ses frères qui le guette.\nNotre chat veut le joindre, il se trouve arrêté.\nSurpris, il juge alors la glace transparente,\nEt passe de l'autre côté,\nNe trouve rien, revient, et le chat se présente.",
      "[...]",
      "Sur le haut du miroir il se met à cheval,\nUne patte par-ci, l'autre par-là, de sorte\nQu'il puisse partout le saisir.\nAlors, croyant bien le tenir,\nDoucement vers la glace il incline la tête,\nAperçoit une oreille, et puis deux… À l'instant,\nÀ droite, à gauche, il va jetant\nSa griffe qu'il tient toute prête.\nMais il perd l'équilibre, il tombe et n'a rien pris.\nAlors, sans davantage attendre,\nSans chercher plus longtemps ce qu'il ne peut comprendre,\nIl laisse le miroir et retourne aux souris.\nQue m'importe, dit-il, de percer ce mystère ?\nUne chose que notre esprit,\nAprès un long travail, n'entend ni ne saisit,\nNe nous est jamais nécessaire.",
    ],
    glossaire: [
      { mot: "une table de toilette", sens: "un petit meuble avec un miroir pour se coiffer." },
      { mot: "le guette", sens: "le regarde en cachette, l'observe." },
      { mot: "la glace", sens: "ici, le miroir." },
      { mot: "se met à cheval", sens: "s'assoit dessus, une patte de chaque côté." },
      { mot: "percer ce mystère", sens: "comprendre quelque chose de caché." },
      { mot: "n'entend ni ne saisit", sens: "ne comprend pas du tout." },
    ],
  },
  {
    id: "c2-031",
    classe: "CE2",
    titre: "Le Ver luisant",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LE_VER_LUISANT",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "I",
      "Que se passe-t-il ? Neuf heures du soir et il y a encore de la lumière chez lui.",
      "II",
      "Cette goutte de lune dans l’herbe !",
    ],
    glossaire: [
      { mot: "un ver luisant", sens: "un petit insecte qui brille dans la nuit, comme une petite lumière." },
      { mot: "luisant", sens: "qui brille, qui fait de la lumière." },
      { mot: "une goutte de lune", sens: "image du poète ; la lumière du ver ressemble à un petit morceau de lune tombé dans l'herbe." },
    ],
  },
  {
    id: "c2-032",
    classe: "CE2",
    titre: "Les Fourmis",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LES_FOURMIS",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "I",
      "Chacune d’elles ressemble au chiffre 3.",
      "Et il y en a ! il y en a !",
      "Il y en a 3 3 3 3 3 3 3 3 3 3 3 3… jusqu’à l’infini.",
      "[...]",
    ],
    glossaire: [
      { mot: "une fourmi", sens: "un tout petit insecte noir qui vit en groupe et travaille beaucoup." },
      { mot: "ressembler à", sens: "être pareil, avoir le même air. La fourmi ressemble au chiffre 3." },
      { mot: "l'infini", sens: "ce qui n'a pas de fin, ce qui ne s'arrête jamais. Il y a tellement de fourmis qu'on ne peut pas les compter." },
    ],
  },
  {
    id: "c2-033",
    classe: "CE2",
    titre: "Le Papillon",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LE_PAPILLON",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Ce billet doux plié en deux cherche une adresse de fleur.",
    ],
    glossaire: [
      { mot: "un billet doux", sens: "une petite lettre d'amour. Le papillon, plié en deux, ressemble à une lettre." },
      { mot: "plié en deux", sens: "rabattu en deux, comme une feuille que l'on ferme." },
      { mot: "une adresse", sens: "l'endroit où l'on envoie une lettre ; ici, la fleur que le papillon va visiter." },
    ],
  },
  {
    id: "c2-034",
    classe: "CE2",
    titre: "L'Écureuil",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#L’ÉCUREUIL",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "I",
      "Du panache ! du panache ! oui, sans doute ; mais, mon petit ami, ce n’est pas là que ça se met.",
      "II",
      "Leste allumeur de l’automne, il passe et repasse sous les feuilles la petite torche de sa queue.",
    ],
    glossaire: [
      { mot: "le panache", sens: "une belle touffe de plumes ou de poils ; ici, la grande queue de l'écureuil." },
      { mot: "leste", sens: "rapide et agile, qui bouge avec légèreté." },
      { mot: "un allumeur", sens: "celui qui allume les lampes ; l'écureuil « allume » l'automne avec sa queue rousse." },
      { mot: "une torche", sens: "un bâton que l'on fait brûler pour éclairer ; la queue de l'écureuil ressemble à une petite flamme." },
    ],
  },
  {
    id: "c2-036",
    classe: "CE2",
    titre: "Le Hérisson",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LE_HÉRISSON",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Essuyez votre… S. V. P.",
      "— Il faut me prendre comme je suis et ne pas trop serrer.",
    ],
    glossaire: [
      { mot: "un hérisson", sens: "un petit animal couvert de piquants, qui se roule en boule quand il a peur." },
      { mot: "essuyer", sens: "nettoyer, frotter pour enlever ce qui gêne." },
      { mot: "S. V. P.", sens: "ce sont les lettres de « s'il vous plaît »." },
      { mot: "serrer", sens: "tenir fort en appuyant ; on ne peut pas serrer le hérisson, cela pique." },
    ],
  },
  {
    id: "c2-037",
    classe: "CE2",
    titre: "Le Serpent",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LE_SERPENT",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "I",
      "Trop long.",
      "II",
      "La dix millionième partie du quart du méridien terrestre.",
    ],
    glossaire: [
      { mot: "un serpent", sens: "un animal long et sans pattes, qui rampe sur le sol." },
      { mot: "trop long", sens: "image amusante ; le serpent est tellement long que c'est tout ce qu'on peut en dire." },
      { mot: "un méridien", sens: "une grande ligne imaginaire qui fait le tour de la Terre ; le poète joue avec l'idée que le serpent est très, très long." },
    ],
  },
  {
    id: "c2-039",
    classe: "CE2",
    titre: "Le Martin-pêcheur",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LE_MARTIN-PÊCHEUR",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Ça n’a pas mordu, ce soir, mais je rapporte une rare émotion.",
      "Comme je tenais ma perche de ligne tendue, un martin-pêcheur est venu s’y poser.",
      "Nous n’avons pas d’oiseau plus éclatant.",
      "Il semblait une grosse fleur bleue au bout d’une longue tige. La perche pliait sous le poids. Je ne respirais plus, tout fier d’être pris pour un arbre par un martin-pêcheur.",
      "Et je suis sûr qu’il ne s’est pas envolé de peur, mais qu’il a cru qu’il ne faisait que passer d’une branche à une autre.",
    ],
    glossaire: [
      { mot: "un martin-pêcheur", sens: "un petit oiseau au plumage bleu très vif, qui vit au bord de l'eau et attrape des poissons." },
      { mot: "mordre", sens: "ici, le poisson qui attrape l'hameçon. « Ça n'a pas mordu » veut dire qu'il n'a pris aucun poisson." },
      { mot: "une perche de ligne", sens: "la longue canne à pêche." },
      { mot: "éclatant", sens: "qui brille, aux couleurs très vives." },
    ],
  },
  {
    id: "c2-040",
    classe: "CE2",
    titre: "Le Lézard",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://fr.wikisource.org/wiki/Histoires_naturelles/ill._Rabier#LE_LÉZARD",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Fils spontané de la pierre fendue où je m’appuie, il me grimpe sur l’épaule. Il a cru que je continuais le mur parce que je reste immobile et que j’ai un paletot couleur de muraille. Ça flatte tout de même.",
      "Le Mur. — Je ne sais quel frisson me passe sur le dos.",
      "Le Lézard. — C’est moi.",
    ],
    glossaire: [
      { mot: "un lézard", sens: "un petit animal à quatre pattes et longue queue, qui aime se chauffer au soleil sur les murs." },
      { mot: "spontané", sens: "qui vient tout seul, naturellement, sans qu'on s'y attende." },
      { mot: "immobile", sens: "qui ne bouge pas du tout." },
      { mot: "un paletot", sens: "un manteau, une veste." },
      { mot: "un frisson", sens: "un petit tremblement qui parcourt le corps." },
    ],
  },
  {
    id: "c2-059",
    classe: "CE2",
    titre: "Le Paon",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://www.gutenberg.org/cache/epub/44255/pg44255.txt",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Il va sûrement se marier aujourd'hui.",
      "Ce devait être pour hier. En habit de gala, il était prêt. Il n'attendait que sa fiancée. Elle n'est pas venue. Elle ne peut tarder.",
      "Glorieux, il se promène avec une allure de prince indien et porte sur lui les riches présents d'usage. L'amour avive l'éclat de ses couleurs et son aigrette tremble comme une lyre.",
      "La fiancée n'arrive pas.",
      "Il monte au haut du toit et regarde du côté du soleil. Il jette son cri diabolique:",
      "Léon! Léon!",
      "C'est ainsi qu'il appelle sa fiancée. Il ne voit rien venir et personne ne répond. Les volailles habituées ne lèvent même point la tête. Elles sont lasses de l'admirer. Il redescend dans la cour, si sûr d'être beau qu'il est incapable de rancune.",
      "Son mariage sera pour demain.",
      "Et, ne sachant que faire du reste de la journée, il se dirige vers le perron. Il gravit les marches, comme des marches de temple, d'un pas officiel.",
      "Il relève sa robe à queue toute lourde des yeux qui n'ont pu se détacher d'elle.",
      "Il répète une dernière fois la cérémonie.",
    ],
    glossaire: [
      { mot: "une aigrette", sens: "le bouquet de plumes dressé sur la tête de l'oiseau." },
      { mot: "glorieux", sens: "ici, très fier de lui." },
      { mot: "les volailles", sens: "les oiseaux de la basse-cour (poules, canards, oies...)." },
      { mot: "lasses", sens: "fatiguées, ici de trop l'admirer." },
      { mot: "la rancune", sens: "l'envie de se venger quand on est vexé." },
    ],
  },
  {
    id: "c2-060",
    classe: "CE2",
    titre: "Les Pigeons",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://www.gutenberg.org/cache/epub/44255/pg44255.txt",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Qu'ils fassent sur la maison un bruit de tambour voilé;",
      "Qu'ils sortent de l'ombre, culbutent, éclatent au soleil et rentrent dans l'ombre;",
      "Que leur col fugitif vive et meure comme l'opale au doigt;",
      "Qu'ils s'endorment, le soir, dans la forêt, si pressés que la plus haute branche du chêne menace de rompre sous cette charge de fruits peints;",
      "Que ces deux-là échangent des saluts frénétiques et brusquement, l'un à l'autre, se convulsent;",
      "Que celui-ci revienne d'exil, avec une lettre, et vole comme la pensée de notre amie lointaine (Ah! un gage!);",
      "Tous ces pigeons, qui d'abord amusent, finissent par ennuyer.",
      "Ils ne sauraient tenir en place et les voyages ne les forment point.",
      "Ils restent toute la vie un peu niais.",
      "Ils s'obstinent à croire qu'on fait les enfants par le bec.",
      "Et c'est insupportable à la longue, cette manie héréditaire d'avoir toujours dans la gorge quelque chose qui ne passe pas.",
    ],
    glossaire: [
      { mot: "le col", sens: "ici, le cou du pigeon." },
      { mot: "une opale", sens: "une jolie pierre aux reflets qui changent de couleur." },
      { mot: "niais", sens: "un peu sot, naïf." },
      { mot: "une manie", sens: "une habitude bizarre qu'on répète sans cesse." },
      { mot: "héréditaire", sens: "qui se transmet des parents aux enfants." },
    ],
  },
  {
    id: "c2-061",
    classe: "CE2",
    titre: "Le Cheval",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://www.gutenberg.org/cache/epub/44255/pg44255.txt",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Il n'est pas beau, mon cheval. Il a trop de noeuds et de salières; il a les côtes plates, une queue de rat et des incisives d'Anglaise. Mais il m'attendrit. Je n'en reviens pas qu'il reste à mon service et se laisse, sans révolte, tourner et retourner.",
      "Chaque fois que je l'attelle, je m'attends à ce qu'il me dise: *non*, d'un signe brusque, et détale.",
      "Point. Il baisse et lève sa grosse tête comme pour remettre un chapeau d'aplomb, recule avec docilité entre les brancards.",
      "Aussi je ne lui ménage ni l'avoine ni le maïs. Je le brosse jusqu'à ce que le poil brille comme une cerise. Je peigne sa crinière, je tresse sa queue maigre. Je le flatte de la main et de la voix. J'éponge ses yeux, je cire ses pieds.",
      "Est-ce que ça le touche?",
      "On ne sait pas.",
      "Il pète.",
      "C'est surtout quand il me promène en voiture que je l'admire. Je le fouette et il accélère son allure. Je l'arrête et il m'arrête. Je tire la guide à gauche et il oblique à gauche, au lieu d'aller à droite et de me jeter dans le fossé avec des coups de sabots quelque part.",
      "Il me fait peur, il me fait honte et il me fait pitié.",
      "Est-ce qu'il ne va pas bientôt se réveiller de son demi-sommeil, et prenant d'autorité ma place, me réduire à la sienne?",
      "A quoi pense-t-il?",
      "Il pète, pète, pète.",
    ],
    glossaire: [
      { mot: "des salières", sens: "ici, les creux au-dessus des yeux d'un vieux cheval maigre." },
      { mot: "m'attendrit", sens: "me touche, me donne de la tendresse." },
      { mot: "atteler", sens: "attacher le cheval à la voiture pour qu'il la tire." },
      { mot: "les brancards", sens: "les deux longues barres entre lesquelles on place le cheval." },
      { mot: "la crinière", sens: "les longs poils sur le cou du cheval." },
      { mot: "la guide", sens: "la longue lanière de cuir qui sert à diriger le cheval." },
    ],
  },
  {
    id: "c2-062",
    classe: "CE2",
    titre: "L'Âne",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://www.gutenberg.org/cache/epub/44255/pg44255.txt",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Tout lui est égal. Chaque matin, il voiture, d'un petit pas sec et dru de fonctionnaire, le facteur Jacquot qui distribue aux villages les commissions faites en ville, les épices, le pain, la viande de boucherie, quelques journaux, une lettre.",
      "Cette tournée finie, Jacquot et l'âne travaillent pour leur compte. La voiture sert de charrette. Ils vont ensemble à la vigne, au bois, aux pommes de terre. Ils ramènent tantôt des légumes, tantôt des balais verts, ça ou autre chose, selon le jour.",
      "Jacquot ne cesse de dire: «Hue! hue!» sans motif, comme il ronflerait. Parfois l'âne, à cause d'un chardon qu'il flaire, ou d'une idée qui le prend, ne marche plus. Jacquot lui met un bras autour du cou et pousse. Si l'âne résiste, Jacquot lui mord l'oreille.",
      "Ils mangent dans les fossés, le maître une croûte et des oignons, la bête ce qu'elle veut.",
      "Ils ne rentrent qu'à la nuit. Leurs ombres passent avec lenteur d'un arbre à l'autre.",
      "Subitement, le lac de silence où les choses baignent et dorment déjà, se rompt, bouleversé.",
      "Quelle ménagère tire, à cette heure, par un treuil rouillé et criard, des pleins seaux d'eau de son puits?",
      "C'est l'âne qui remonte et jette toute sa voix dehors et brait, jusqu'à extinction, qu'il s'en fiche, qu'il s'en fiche.",
    ],
    glossaire: [
      { mot: "il voiture", sens: "il transporte, il promène dans sa voiture." },
      { mot: "un facteur", sens: "la personne qui apporte le courrier." },
      { mot: "une tournée", sens: "le trajet qu'on fait pour livrer ou distribuer." },
      { mot: "un chardon", sens: "une plante piquante que l'âne aime manger." },
      { mot: "braire", sens: "le cri de l'âne." },
      { mot: "un treuil", sens: "un appareil à manivelle pour remonter un seau du puits." },
    ],
  },
  {
    id: "c2-063",
    classe: "CE2",
    titre: "Les Moutons",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://www.gutenberg.org/cache/epub/44255/pg44255.txt",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Ils reviennent des chaumes où, depuis ce matin, ils paissaient, le nez à l'ombre de leur corps.",
      "Selon les signes d'un berger indolent, le chien nécessaire attaque la bande du côté qu'il faut.",
      "Elle tient toute la route, ondule d'un fossé à l'autre et déborde, ou, tassée, unie, moelleuse, piétine le sol, à petits pas de vieilles femmes. Quand elle se met à courir, les pattes font le bruit des roseaux et criblent la poussière du chemin de nids d'abeilles.",
      "Ce mouton frise et, bien garni, saute comme un ballot jeté en l'air, et du cornet de son oreille s'échappent des pastilles.",
      "Cet autre a le vertige et heurte du genou sa tête mal vissée.",
      "Ils envahissent le village. On dirait que c'est aujourd'hui leur fête et qu'avec pétulance, ils bêlent de joie par les rues.",
      "Mais ils ne s'arrêtent pas au village, et je les vois reparaître, là-bas. Ils gagnent l'horizon. Par le coteau, ils montent, légers, vers le soleil. Ils s'en approchent et se couchent à distance.",
      "Des traînards prennent, sur le ciel, une dernière forme imprévue, et rejoignent la troupe pelotonnée.",
      "Un flocon se détache encore et plane, mousse blanche, puis fumée, vapeur, puis rien.",
      "Il ne reste plus qu'une patte dehors.",
      "Elle s'allonge, elle s'effile comme une quenouille, à l'infini.",
      "Les moutons frileux s'endorment autour du soleil las qui défait sa couronne et pique, jusqu'à demain, ses rayons dans leur laine.",
    ],
    glossaire: [
      { mot: "les chaumes", sens: "les champs après la moisson, où restent les tiges coupées." },
      { mot: "paissaient", sens: "mangeaient l'herbe sur place." },
      { mot: "indolent", sens: "tranquille, qui ne se presse pas." },
      { mot: "la pétulance", sens: "une joie vive et remuante." },
      { mot: "un traînard", sens: "celui qui reste en arrière du groupe." },
      { mot: "pelotonnée", sens: "serrée en boule, comme une pelote de laine." },
    ],
  },
  {
    id: "c2-065",
    classe: "CE2",
    titre: "Les Grenouilles",
    oeuvre: "Histoires naturelles",
    auteur: "Jules Renard",
    auteurDeces: "1910",
    url: "https://www.gutenberg.org/cache/epub/44255/pg44255.txt",
    librivoxUrl: "",
    theme: "nature, animaux",
    corps: [
      "Par brusques détentes, elles exercent leurs ressorts.",
      "Elles sautent de l'herbe comme de lourdes gouttes d'huile frite.",
      "Elles se posent, presse-papiers de bronze, sur les larges feuilles du nénuphar.",
      "L'une se gorge d'air. On mettrait un sou, par sa bouche, dans la tirelire de son ventre.",
      "Elles montent, comme des soupirs, de la vase.",
      "Immobiles, elles semblent les gros yeux à fleur d'eau, les tumeurs de la mare plate.",
      "Assises en tailleur, stupéfiées, elles bâillent au soleil couchant.",
      "Puis, comme les camelots assourdissants des rues, elles crient les dernières nouvelles du soir.",
      "Parfois, elles happent un insecte.",
      "Et d'autres ne s'occupent que d'amour.",
      "Et toutes, elles tentent le pêcheur à la ligne.",
      "Je casse, sans difficulté, une gaule. J'ai, piquée à mon paletot, une épingle que je recourbe en hameçon.",
      "La ficelle ne me manque pas, Dieu merci!",
      "Mais il me faudrait encore un brin de laine, un bout de n'importe quoi rouge.",
      "Je cherche sur moi, par terre, au ciel.",
      "Je ne trouve rien et je regarde mélancoliquement ma boutonnière fendue, toute prête, que, sans reproche, on ne se hâte guère d'orner du ruban rouge.",
    ],
    glossaire: [
      { mot: "une détente", sens: "le mouvement d'un ressort qui se relâche d'un coup." },
      { mot: "un nénuphar", sens: "une grande fleur plate qui flotte sur l'eau des mares." },
      { mot: "la vase", sens: "la boue molle au fond de l'eau." },
      { mot: "un camelot", sens: "un marchand qui vend dans la rue en criant très fort." },
      { mot: "une gaule", sens: "une longue tige de bois (ici, pour pêcher)." },
      { mot: "un hameçon", sens: "le petit crochet au bout de la ligne de pêche." },
    ],
  },
  {
    id: "c2-042",
    classe: "CE2",
    titre: "La boîte à mouches",
    oeuvre: "Les Malheurs de Sophie, VI - L'abeille",
    auteur: "La Comtesse de Ségur",
    auteurDeces: "1874",
    url: "https://fr.wikisource.org/wiki/Page:Ségur_-_Les_Malheurs_de_Sophie.djvu/55",
    librivoxUrl: "",
    theme: "animaux, famille",
    corps: [
      "Sophie et son cousin Paul jouaient un jour dans leur chambre ; ils s’amusaient à attraper des mouches qui se promenaient sur les carreaux de la fenêtre ; à mesure qu’ils en attrapaient, ils les mettaient dans une petite boîte en papier que leur avait faite leur papa.",
      "Quand ils en eurent attrapé beaucoup, Paul voulut voir ce qu’elles faisaient dans la boîte.",
      "« Donne-moi la boîte, dit-il à Sophie qui la tenait ; nous allons regarder ce que font les mouches. »",
      "Sophie la lui donna ; ils entr’ouvrirent avec beaucoup de précaution la petite porte de la boîte.",
    ],
    glossaire: [
      { mot: "un cousin", sens: "le fils de l’oncle ou de la tante." },
      { mot: "les carreaux", sens: "les vitres de la fenêtre." },
      { mot: "à mesure que", sens: "au fur et à mesure, petit à petit." },
      { mot: "entr’ouvrir", sens: "ouvrir un tout petit peu, à moitié." },
      { mot: "avec précaution", sens: "doucement, en faisant très attention." },
    ],
  },
  {
    id: "c2-056",
    classe: "CE2",
    titre: "Camille et Madeleine",
    oeuvre: "Les Petites Filles modèles, I - Camille et Madeleine",
    auteur: "La Comtesse de Ségur",
    auteurDeces: "1874",
    url: "https://fr.wikisource.org/wiki/Page:Ségur_-_Les_petites_filles_modèles.djvu/10",
    librivoxUrl: "",
    theme: "famille, amitié",
    corps: [
      "Mme de Fleurville était la mère de deux petites filles, bonnes, gentilles, aimables, et qui avaient l’une pour l’autre le plus tendre attachement. On voit souvent des frères et des sœurs se quereller, se contredire et venir se plaindre à leurs parents après s’être disputés de manière qu’il soit impossible de démêler de quel côté vient le premier tort. Jamais on n’entendait une discussion entre Camille et Madeleine. Tantôt l’une, tantôt l’autre cédait au désir exprimé par sa sœur.",
      "Pourtant leurs goûts n’étaient pas exactement les mêmes. Camille, plus âgée d’un an que Madeleine, avait huit ans.",
    ],
    glossaire: [
      { mot: "un tendre attachement", sens: "un amour doux, le fait de beaucoup s’aimer." },
      { mot: "se quereller", sens: "se disputer, se fâcher." },
      { mot: "se contredire", sens: "dire le contraire de ce que dit l’autre." },
      { mot: "démêler", sens: "comprendre clairement, voir qui a raison." },
      { mot: "le tort", sens: "la faute, l’erreur." },
      { mot: "céder", sens: "laisser faire, accepter ce que l’autre veut." },
    ],
  },
  {
    id: "c2-066",
    classe: "CE2",
    titre: "La ronde de joie",
    oeuvre: "Les Petites Filles modèles, XIX - L'illumination",
    auteur: "La Comtesse de Ségur",
    auteurDeces: "1874",
    url: "https://www.gutenberg.org/cache/epub/35404/pg35404.txt",
    librivoxUrl: "",
    theme: "joie, amitié",
    corps: [
      "Après avoir embrassé encore Mme de Fleurville, Sophie courut chez ses amies pour leur annoncer ces grandes nouvelles. Ce fut une joie générale; elles se mirent à danser une ronde si bruyante, accompagnée de tels cris de joie, qu'Élisa accourut au bruit.",
      "[...]",
      "Et la ronde, les sauts, les cris recommencèrent de plus belle. Élisa s'était mise de la partie, et le tapage devint tel, que successivement toute la maison vint savoir la cause de ce bruit sans pareil.",
      "[...]",
      "Enfin les petites filles se lassèrent de danser; toutes quatre tombèrent sur des chaises; Élisa s'y laissa tomber comme elles.",
    ],
    glossaire: [
      { mot: "une ronde", sens: "une danse où l'on se tient par la main en formant un cercle." },
      { mot: "le tapage", sens: "un grand bruit, ici un bruit joyeux." },
      { mot: "sans pareil", sens: "que rien n'égale, extraordinaire." },
      { mot: "se lasser", sens: "commencer à être fatigué de quelque chose." },
    ],
  },
  {
    id: "c2-067",
    classe: "CE2",
    titre: "Le goûter à la ferme",
    oeuvre: "Les Vacances, II - Les cabanes",
    auteur: "La Comtesse de Ségur",
    auteurDeces: "1874",
    url: "https://www.gutenberg.org/cache/epub/15057/pg15057.txt",
    librivoxUrl: "",
    theme: "vacances, ferme",
    corps: [
      "Jacques avait eu, avant de se coucher, une conversation à voix basse avec son père et Marguerite; on les voyait causer avec animation; on les entendait rire; de temps en temps, Jacques sautait, battait des mains et embrassait son papa et Marguerite [...]. En attendant mes cousines et mes amies, allons faire un tour à la ferme; nous déjeunerons avec du bon lait tout chaud et du pain bis. Jean approuva vivement ce projet; ils arrivèrent au moment où l'on finissait de traire les vaches. La fermière, la mère Diart, les reçut avec empressement. [...] Léon et Jean remercièrent la fermière et se mirent à manger avec délices ce bon lait tout chaud et ce pain de ménage, à peine sorti du four et tiède encore.",
    ],
    glossaire: [
      { mot: "le pain bis", sens: "un pain de campagne un peu gris, fait de farine complète." },
      { mot: "traire", sens: "tirer le lait des vaches en pressant leurs mamelles." },
      { mot: "avec empressement", sens: "avec beaucoup d'envie de bien faire, très vite." },
      { mot: "avec délices", sens: "avec un très grand plaisir." },
    ],
  },
  {
    id: "c2-068",
    classe: "CE2",
    titre: "Cadichon et le petit Jacques",
    oeuvre: "Les Mémoires d'un âne, X - Les bons maîtres",
    auteur: "La Comtesse de Ségur",
    auteurDeces: "1874",
    url: "https://www.gutenberg.org/cache/epub/12783/pg12783.txt",
    librivoxUrl: "",
    theme: "tendresse, animaux",
    corps: [
      "Jacques s'approcha de mon oreille et me dit tout bas, en me caressant:",
      "--Marche, mon petit Cadichon; je t'en prie, marche.",
      "La confiance de ce bon petit garçon me toucha; je remarquai avec plaisir qu'au lieu de demander un bâton pour me faire avancer, il n'avait songé qu'aux moyens de douceur et d'amitié. Aussi, à peine avait-il achevé sa phrase et sa petite caresse, que je me mis en marche.",
      "--Vous voyez, ma bonne, il me comprend, il m'aime! s'écria Jacques, rouge de joie, les yeux brillants de bonheur, et courant en avant pour me montrer le chemin.",
    ],
    glossaire: [
      { mot: "tout bas", sens: "à voix très douce, en chuchotant." },
      { mot: "la confiance", sens: "le fait de croire en quelqu'un sans aucune crainte." },
      { mot: "la douceur", sens: "le fait d'être gentil et calme avec les autres." },
      { mot: "songer", sens: "penser à quelque chose." },
    ],
  },
  {
    id: "c2-069",
    classe: "CE2",
    titre: "La promenade au moulin",
    oeuvre: "Les Vacances, III - La visite au moulin",
    auteur: "La Comtesse de Ségur",
    auteurDeces: "1874",
    url: "https://www.gutenberg.org/cache/epub/15057/pg15057.txt",
    librivoxUrl: "",
    theme: "promenade, nature",
    corps: [
      "«Je propose une grande promenade au moulin, par les bois, dit M. de Rugès. [...] pendant que nous examinerons les machines, vous autres enfants vous jouerez sur l'herbe où l'on vous préparera un bon goûter de campagne: pain bis, crème fraîche, lait caillé, fromage, beurre et galette de ménage. Que ceux qui m'aiment me suivent!» Tous l'entourèrent au même instant. Les enfants, qui étaient partis au galop, revinrent sur leurs pas et se groupèrent autour de leurs parents. La promenade fut charmante, la fraîcheur du bois tempérait la chaleur du soleil; de temps en temps on s'asseyait, on causait, on cueillait des fleurs, on trouvait quelques fraises.",
    ],
    glossaire: [
      { mot: "un goûter de campagne", sens: "un petit repas pris dehors, à la campagne." },
      { mot: "le lait caillé", sens: "du lait devenu épais, un peu comme du fromage frais." },
      { mot: "tempérer", sens: "adoucir, rendre moins fort (ici, la chaleur)." },
      { mot: "cueillir", sens: "détacher des fleurs ou des fruits avec la main." },
    ],
  },
  {
    id: "c2-020",
    classe: "CE1",
    titre: "Les Roses de Saadi",
    oeuvre: "Poésies inédites - Les Roses de Saadi",
    auteur: "Marceline Desbordes-Valmore",
    auteurDeces: "1859",
    url: "https://fr.wikisource.org/wiki/Poésies_inédites_(Marceline_Desbordes-Valmore)/Les_Roses_de_Saadi",
    librivoxUrl: "",
    theme: "fleurs, nature",
    corps: [
      "J'ai voulu, ce matin, te rapporter des roses ;\nMais j'en avais tant pris dans mes ceintures closes\nQue les nœuds trop serrés n'ont pu les contenir.",
      "Les nœuds ont éclaté. Les roses envolées\nDans le vent, à la mer s'en sont toutes allées.\nElles ont suivi l'eau pour ne plus revenir.",
      "La vague en a paru rouge et comme enflammée :\nCe soir ma robe encore en est toute embaumée...\nRespires-en sur moi l'odorant souvenir.",
    ],
    glossaire: [
      { mot: "une ceinture close", sens: "une ceinture fermée, nouée bien serré autour de la taille." },
      { mot: "un nœud", sens: "l'endroit où l'on attache un fil ou un ruban." },
      { mot: "une vague", sens: "l'eau de la mer qui monte et se roule." },
      { mot: "embaumée", sens: "remplie d'un bon parfum." },
      { mot: "odorant", sens: "qui sent bon, qui a une bonne odeur." },
    ],
  },
  {
    id: "c2-044",
    classe: "CE2",
    titre: "La princesse Florine",
    oeuvre: "L'Oiseau bleu",
    auteur: "Marie-Catherine d'Aulnoy",
    auteurDeces: "1705",
    url: "https://fr.wikisource.org/wiki/Page:Aulnoy_-_Contes_de_Madame_d'Aulnoy,_1882.djvu/32",
    librivoxUrl: "",
    theme: "merveilleux, famille",
    corps: [
      "Le roi n’avait eu qu’une fille de son premier mariage, qui passait pour la huitième merveille du monde ; on la nommait Florine, parce qu’elle ressemblait à Flore, tant elle était fraîche, jeune et belle. On ne lui voyait guère d’habits magnifiques ; elle aimait les robes de taffetas volant, avec quelques agrafes de pierreries et force guirlandes de fleurs, qui faisaient un effet admirable quand elles étaient placées dans ses beaux cheveux. Elle n’avait que quinze ans lorsque le roi se remaria. La nouvelle reine envoya quérir sa fille, qui avait été nourrie chez sa marraine, la fée Soussio.",
    ],
    glossaire: [
      { mot: "la huitième merveille du monde", sens: "quelque chose de si beau qu’on l’ajoute aux sept merveilles célèbres." },
      { mot: "du taffetas", sens: "un tissu de soie léger et brillant." },
      { mot: "des pierreries", sens: "des pierres précieuses, comme les diamants." },
      { mot: "force guirlandes", sens: "beaucoup de guirlandes (ici, « force » veut dire « beaucoup »)." },
      { mot: "envoyer quérir", sens: "envoyer chercher quelqu’un." },
      { mot: "une marraine", sens: "la personne qui protège et accompagne un enfant." },
    ],
  },
  {
    id: "c2-016",
    classe: "CE1",
    titre: "Noël",
    oeuvre: "Émaux et Camées - Noël",
    auteur: "Théophile Gautier",
    auteurDeces: "1872",
    url: "https://fr.wikisource.org/wiki/Émaux_et_Camées/Noël",
    librivoxUrl: "",
    theme: "Noël, hiver",
    corps: [
      "Le ciel est noir, la terre est blanche ;\n- Cloches, carillonnez gaîment ! -\nJésus est né ; - la Vierge penche\nSur lui son visage charmant.",
      "Pas de courtines festonnées\nPour préserver l'enfant du froid ;\nRien que les toiles d'araignées\nQui pendent des poutres du toit.",
      "Il tremble sur la paille fraîche,\nCe cher petit enfant Jésus,\nEt pour l'échauffer dans sa crèche\nL'âne et le bœuf soufflent dessus.",
      "La neige au chaume coud ses franges,\nMais sur le toit s'ouvre le ciel,\nEt, tout en blanc, le chœur des anges\nChante aux bergers : « Noël ! Noël ! »",
    ],
    glossaire: [
      { mot: "carillonner", sens: "faire sonner joyeusement les cloches." },
      { mot: "une courtine", sens: "un petit rideau, par exemple autour d'un lit." },
      { mot: "festonnées", sens: "décorées de jolis bords découpés en vagues." },
      { mot: "une crèche", sens: "la mangeoire des animaux où l'on a couché l'enfant Jésus." },
      { mot: "le chaume", sens: "la paille qui sert de toit à certaines maisons." },
    ],
  },
  {
    // LOT 0 : texte récupéré (décision Manu). Extrait COUPÉ à la limite de phrase
    // AVANT le dernier vers (« …l'empire des morts ») pour la bienveillance :
    // on s'arrête sur « L'arbre tient bon ; le roseau plie. ». Le corps affiché
    // ne contient plus aucun mot interdit (garde-fou bienveillance).
    id: "c2-050",
    classe: "CE2",
    titre: "Le Chêne et le Roseau",
    oeuvre: "Fables, Livre I, 22 - Le Chêne et le Roseau",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/Le_Chêne_et_le_Roseau",
    librivoxUrl: "",
    theme: "nature, sagesse",
    corps: [
      "Le chêne un jour dit au roseau :\nVous avez bien sujet d'accuser la nature ;\nUn roitelet pour vous est un pesant fardeau :\nLe moindre vent qui d'aventure\nFait rider la face de l'eau,\nVous oblige à baisser la tête ;\nCependant que mon front, au Caucase pareil,\nNon content d'arrêter les rayons du soleil,\nBrave l'effort de la tempête.\nTout vous est aquilon, tout me semble zéphyr.\nEncor si vous naissiez à l'abri du feuillage\nDont je couvre le voisinage,\nVous n'auriez pas tant à souffrir,\nJe vous défendrais de l'orage :\nMais vous naissez le plus souvent\nSur les humides bords des royaumes du vent.\nLa nature envers vous me semble bien injuste.",
      "Votre compassion, lui répondit l'arbuste,\nPart d'un bon naturel ; mais quittez ce souci :\nLes vents me sont moins qu'à vous redoutables ;\nJe plie et ne romps pas. Vous avez jusqu'ici\nContre leurs coups épouvantables\nRésisté sans courber le dos ;\nMais attendons la fin. Comme il disait ces mots,\nDu bout de l'horizon accourt avec furie\nLe plus terrible des enfants\nQue le Nord eût portés jusque-là dans ses flancs.\nL'arbre tient bon ; le roseau plie.",
    ],
    glossaire: [
      { mot: "un roitelet", sens: "un tout petit oiseau ; ici, une bien petite charge." },
      { mot: "un fardeau", sens: "une charge lourde à porter." },
      { mot: "l'aquilon", sens: "un vent froid et fort qui vient du nord." },
      { mot: "le zéphyr", sens: "un vent doux et léger." },
      { mot: "la compassion", sens: "le fait de plaindre quelqu'un, d'avoir de la peine pour lui." },
      { mot: "plier et ne pas rompre", sens: "se courber sans se casser." },
    ],
  },
  {
    // LOT 0 : texte récupéré (décision Manu). Extrait ARRÊTÉ à la limite de phrase
    // AVANT les vers sur le mari (« En grand danger d'être battue »), donc aucune
    // allusion à de la violence. On s'arrête sur « Le lait tombe ; adieu veau,
    // vache, cochon, couvée. ». Corps affiché sans mot interdit.
    id: "c2-026",
    classe: "CE2",
    titre: "La Laitière et le Pot au lait",
    oeuvre: "Fables, Livre VII, 9 - La Laitière et le Pot au lait",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/La_Laitière_et_le_Pot_au_lait",
    librivoxUrl: "",
    theme: "rêve, nature",
    corps: [
      "Perrette, sur sa tête ayant un pot au lait\nBien posé sur un coussinet,\nPrétendait arriver sans encombre à la ville.\nLégère et court vêtue, elle allait à grands pas,\nAyant mis ce jour-là, pour être plus agile,\nCotillon simple et souliers plats.\nNotre laitière ainsi troussée\nComptait déjà dans sa pensée\nTout le prix de son lait ; en employait l'argent ;\nAchetait un cent d'œufs ; faisait triple couvée :\nLa chose allait à bien par son soin diligent.",
      "Il m'est, disait-elle, facile\nD'élever des poulets autour de ma maison ;\nLe renard sera bien habile\nS'il ne m'en laisse assez pour avoir un cochon.\nLe porc à s'engraisser coûtera peu de son ;\nIl était, quand je l'eus, de grosseur raisonnable :\nJ'aurai, le revendant, de l'argent bel et bon.\nEt qui m'empêchera de mettre en notre étable,\nVu le prix dont il est, une vache et son veau,\nQue je verrai sauter au milieu du troupeau ?\nPerrette là-dessus saute aussi, transportée :\nLe lait tombe ; adieu veau, vache, cochon, couvée.",
    ],
    glossaire: [
      { mot: "une laitière", sens: "une femme qui vend du lait." },
      { mot: "un coussinet", sens: "un petit coussin posé sur la tête pour porter le pot." },
      { mot: "un cotillon", sens: "un jupon, une jupe simple d'autrefois." },
      { mot: "troussée", sens: "habillée de façon légère et pratique pour marcher." },
      { mot: "une couvée", sens: "tous les poussins qui naissent en même temps des œufs d'une poule." },
    ],
  },
  {
    // LOT 0 : texte récupéré (décision Manu). Extrait ARRÊTÉ aux limites de phrase :
    // on garde la présentation (vendre la peau de l'ours avant de l'avoir) et la
    // morale, mais on coupe la scène du milieu (« fait le mort ») pour que le
    // corps affiché ne contienne aucun mot interdit (garde-fou bienveillance).
    id: "c2-075",
    classe: "CE2",
    titre: "L'Ours et les deux Compagnons",
    oeuvre: "Fables, Livre V, 20 - L'Ours et les deux Compagnons",
    auteur: "Jean de La Fontaine",
    auteurDeces: "1695",
    url: "https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(éd._1874)/L’Ours_et_les_deux_Compagnons",
    librivoxUrl: "",
    theme: "humour, sagesse",
    corps: [
      "Deux compagnons, pressés d'argent,\nÀ leur voisin fourreur vendirent\nLa peau d'un ours encor vivant,\nMais qu'ils tueraient bientôt, du moins à ce qu'ils dirent.\nC'était le roi des ours au compte de ces gens.",
      "Trouvent l'ours qui s'avance et vient vers eux au trot,\nVoilà mes gens frappés comme d'un coup de foudre.\nL'un des deux compagnons grimpe au faîte d'un arbre.",
      "Il m'a dit qu'il ne faut jamais\nVendre la peau de l'ours qu'on ne l'ait mis par terre.",
    ],
    glossaire: [
      { mot: "un fourreur", sens: "un marchand qui vend des peaux et des fourrures pour se tenir chaud." },
      { mot: "le faîte", sens: "le sommet, le point le plus haut (ici, le haut de l'arbre)." },
      { mot: "un compagnon", sens: "une personne avec qui on fait quelque chose, un camarade." },
    ],
  },
];

// Auteurs dans l'ordre d'affichage (regroupement de la page Bibliothèque).
export const BIBLIO_AUTEURS: string[] = [
  "Anatole France",
  "Charles Cros",
  "Charles Perrault",
  "Colette",
  "George Sand",
  "Hans Christian Andersen",
  "Jean de La Fontaine",
  "Jean-Pierre Claris de Florian",
  "Jules Renard",
  "La Comtesse de Ségur",
  "Marceline Desbordes-Valmore",
  "Marie-Catherine d'Aulnoy",
  "Théophile Gautier",
];
