// Banque d'exercices de VOCABULAIRE et MOTS A SAVOIR (francais, CE2, programme
// cycle 2 revise 2024). GENERE depuis une source unique (voir rapport) ; miroir
// EXACT de la table de reference public.lexique_item (migration 0042) et teste
// en croise (frontend/.../francais/lexique.test.ts + supabase/tests/lexique_test.sql).
//
// On REUTILISE l'architecture de la grammaire (phase 1) : meme type d'item
// (GramItem), meme comparaison (comparerGrammaire : qcm -> normaliser, accents
// gardes ; clic/texte -> normaliserMot, ponctuation de bord retiree), meme
// composant <Grammaire> (QCM / clic sur un mot / saisie libre), meme principe
// « le SERVEUR reste SEUL JUGE » via une cle d'item (op dediee 'lex').
//
// Deux sous-matieres, domaines dedies :
//   VOCABULAIRE (domaine `vocabulaire`) :
//     FR.VOC.ALPHABET         ordre alphabetique et usage du dictionnaire ;
//     FR.VOC.FAMILLES         familles de mots (intrus, meme famille) ;
//     FR.VOC.SYN_CONTRAIRES   synonymes et contraires (y compris par prefixe) ;
//     FR.VOC.PREFIXE_SUFFIXE  prefixes et suffixes simples (re-, de-, in-, -eur, -ette) ;
//     FR.VOC.CATEGORIES       categories / mot generique.
//   MOTS A SAVOIR (domaine `mots-invariables`) :
//     FR.MOTS.INVARIABLES     mots invariables CE2 ; N1 choisir la bonne
//                             orthographe, jusqu'au N4 ecrire le mot dans une
//                             phrase a trou. Les messages DECRIVENT la lettre
//                             (ex. « un p a la fin qu'on n'entend pas »).
//
// Progression des formats (identique a la grammaire) : N1 QCM, N2 clic/QCM,
// N3 clic/QCM, N4 reponse LIBRE (texte). Messages enfant de 8 ans, pour l'ORAL :
// phrases courtes, aucun symbole, jamais deux formes homophones opposees,
// toujours un exemple concret.

import type { GramItem } from "./grammaire";
import { comparerGrammaire } from "./grammaire";

// Un item de lexique a la MEME forme qu'un item de grammaire (cle, competence,
// niveau, format, consigne, phrase, options?, attendu, explication).
export type LexItem = GramItem;

// Comparaison miroir du serveur (reutilise celle de la grammaire).
export const comparerLexique = comparerGrammaire;

export const BANQUE_VOCABULAIRE: LexItem[] = [
  // FR.VOC.ALPHABET
  { cle: "voc-alpha-n1-1", competence: "FR.VOC.ALPHABET", niveau: 1, format: "qcm", consigne: "Quel mot vient en premier dans le dictionnaire ?", phrase: "", options: ["arbre", "chat", "pomme"], attendu: "arbre", explication: "Dans le dictionnaire, on range les mots par la première lettre. a vient avant c et avant p, donc arbre est le premier." },
  { cle: "voc-alpha-n1-2", competence: "FR.VOC.ALPHABET", niveau: 1, format: "qcm", consigne: "Quel mot vient en premier dans le dictionnaire ?", phrase: "", options: ["ballon", "souris", "table"], attendu: "ballon", explication: "b vient avant s et avant t, donc ballon est le premier." },
  { cle: "voc-alpha-n1-3", competence: "FR.VOC.ALPHABET", niveau: 1, format: "qcm", consigne: "Quel mot vient en premier dans le dictionnaire ?", phrase: "", options: ["lune", "moto", "nuage"], attendu: "lune", explication: "l vient avant m et avant n, donc lune est le premier." },
  { cle: "voc-alpha-n1-4", competence: "FR.VOC.ALPHABET", niveau: 1, format: "qcm", consigne: "Quel mot vient en premier dans le dictionnaire ?", phrase: "", options: ["dauphin", "girafe", "renard"], attendu: "dauphin", explication: "d vient avant g et avant r, donc dauphin est le premier." },
  { cle: "voc-alpha-n1-5", competence: "FR.VOC.ALPHABET", niveau: 1, format: "qcm", consigne: "Quel mot vient en premier dans le dictionnaire ?", phrase: "", options: ["cerise", "fraise", "orange"], attendu: "cerise", explication: "c vient avant f et avant o, donc cerise est le premier." },
  { cle: "voc-alpha-n2-1", competence: "FR.VOC.ALPHABET", niveau: 2, format: "clic", consigne: "Clique sur le mot qui vient en premier dans le dictionnaire.", phrase: "chat cheval chien", attendu: "chat", explication: "chat, cheval et chien commencent tous par ch. Ensuite on regarde la lettre d'après : a, e, i. a vient en premier, donc chat est le premier." },
  { cle: "voc-alpha-n2-2", competence: "FR.VOC.ALPHABET", niveau: 2, format: "clic", consigne: "Clique sur le mot qui vient en premier dans le dictionnaire.", phrase: "banane balle bateau", attendu: "balle", explication: "balle, banane et bateau commencent par ba. Ensuite on regarde : l, n, t. l vient avant n et t, donc balle est le premier." },
  { cle: "voc-alpha-n2-3", competence: "FR.VOC.ALPHABET", niveau: 2, format: "clic", consigne: "Clique sur le mot qui vient en premier dans le dictionnaire.", phrase: "poule poire pomme", attendu: "poire", explication: "poire, pomme et poule commencent par po. Ensuite : i, m, u. i vient en premier, donc poire est le premier." },
  { cle: "voc-alpha-n2-4", competence: "FR.VOC.ALPHABET", niveau: 2, format: "clic", consigne: "Clique sur le mot qui vient en premier dans le dictionnaire.", phrase: "marin maison manteau", attendu: "maison", explication: "maison, manteau et marin commencent par ma. Ensuite : i, n, r. i vient en premier, donc maison est le premier." },
  { cle: "voc-alpha-n2-5", competence: "FR.VOC.ALPHABET", niveau: 2, format: "clic", consigne: "Clique sur le mot qui vient en premier dans le dictionnaire.", phrase: "sucre souris sapin", attendu: "sapin", explication: "sapin, souris et sucre commencent par s. Ensuite on regarde la deuxième lettre : a, o, u. a vient en premier, donc sapin est le premier." },
  { cle: "voc-alpha-n3-1", competence: "FR.VOC.ALPHABET", niveau: 3, format: "qcm", consigne: "Entre quels mots du dictionnaire se range le mot lune ?", phrase: "lune", options: ["entre livre et mardi", "entre arbre et chat", "entre table et vélo"], attendu: "entre livre et mardi", explication: "lune commence par l. livre est un mot en l, mardi est un mot en m. l vient entre livre et mardi." },
  { cle: "voc-alpha-n3-2", competence: "FR.VOC.ALPHABET", niveau: 3, format: "qcm", consigne: "Entre quels mots du dictionnaire se range le mot chat ?", phrase: "chat", options: ["entre banane et dent", "entre pomme et table", "entre arbre et avion"], attendu: "entre banane et dent", explication: "chat commence par c. banane est un mot en b, dent est un mot en d. c vient entre b et d." },
  { cle: "voc-alpha-n3-3", competence: "FR.VOC.ALPHABET", niveau: 3, format: "qcm", consigne: "Entre quels mots du dictionnaire se range le mot fraise ?", phrase: "fraise", options: ["entre école et gare", "entre arbre et chat", "entre table et vélo"], attendu: "entre école et gare", explication: "fraise commence par f. école est un mot en e, gare est un mot en g. f vient entre e et g." },
  { cle: "voc-alpha-n3-4", competence: "FR.VOC.ALPHABET", niveau: 3, format: "qcm", consigne: "Entre quels mots du dictionnaire se range le mot souris ?", phrase: "souris", options: ["entre reine et table", "entre arbre et pomme", "entre livre et mardi"], attendu: "entre reine et table", explication: "souris commence par s. reine est un mot en r, table est un mot en t. s vient entre r et t." },
  { cle: "voc-alpha-n3-5", competence: "FR.VOC.ALPHABET", niveau: 3, format: "qcm", consigne: "Entre quels mots du dictionnaire se range le mot nuage ?", phrase: "nuage", options: ["entre moto et orange", "entre arbre et chat", "entre table et vélo"], attendu: "entre moto et orange", explication: "nuage commence par n. moto est un mot en m, orange est un mot en o. n vient entre m et o." },
  { cle: "voc-alpha-n4-1", competence: "FR.VOC.ALPHABET", niveau: 4, format: "texte", consigne: "Écris le mot qui vient en premier dans le dictionnaire.", phrase: "lampe lapin lavabo", attendu: "lampe", explication: "lampe, lapin et lavabo commencent par la. Ensuite : m, p, v. m vient en premier, donc le premier est lampe." },
  { cle: "voc-alpha-n4-2", competence: "FR.VOC.ALPHABET", niveau: 4, format: "texte", consigne: "Écris le mot qui vient en premier dans le dictionnaire.", phrase: "fromage fruit fraise", attendu: "fraise", explication: "fraise, fromage et fruit commencent par fr. Ensuite : a, o, u. a vient en premier, donc le premier est fraise." },
  { cle: "voc-alpha-n4-3", competence: "FR.VOC.ALPHABET", niveau: 4, format: "texte", consigne: "Écris le mot qui vient en premier dans le dictionnaire.", phrase: "blond blanc bleu", attendu: "blanc", explication: "blanc, bleu et blond commencent par bl. Ensuite : a, e, o. a vient en premier, donc le premier est blanc." },
  { cle: "voc-alpha-n4-4", competence: "FR.VOC.ALPHABET", niveau: 4, format: "texte", consigne: "Écris le mot qui vient en premier dans le dictionnaire.", phrase: "craie citron cerise", attendu: "cerise", explication: "cerise, citron et craie commencent par c. Ensuite la deuxième lettre : e, i, r. e vient en premier, donc le premier est cerise." },
  { cle: "voc-alpha-n4-5", competence: "FR.VOC.ALPHABET", niveau: 4, format: "texte", consigne: "Écris le mot qui vient en premier dans le dictionnaire.", phrase: "voler ville vague", attendu: "vague", explication: "vague, ville et voler commencent par v. Ensuite la deuxième lettre : a, i, o. a vient en premier, donc le premier est vague." },
  // FR.VOC.FAMILLES
  { cle: "voc-fam-n1-1", competence: "FR.VOC.FAMILLES", niveau: 1, format: "qcm", consigne: "Quel mot est de la même famille que dent ?", phrase: "", options: ["dentiste", "maison", "bleu"], attendu: "dentiste", explication: "La famille de dent parle des dents. dentiste est de la même famille, c'est la personne qui soigne les dents." },
  { cle: "voc-fam-n1-2", competence: "FR.VOC.FAMILLES", niveau: 1, format: "qcm", consigne: "Quel mot est de la même famille que terre ?", phrase: "", options: ["terrain", "voiture", "chanter"], attendu: "terrain", explication: "La famille de terre parle de la terre. terrain est de la même famille." },
  { cle: "voc-fam-n1-3", competence: "FR.VOC.FAMILLES", niveau: 1, format: "qcm", consigne: "Quel mot est de la même famille que fleur ?", phrase: "", options: ["fleuriste", "tableau", "rapide"], attendu: "fleuriste", explication: "La famille de fleur parle des fleurs. fleuriste est de la même famille, c'est la personne qui vend des fleurs." },
  { cle: "voc-fam-n1-4", competence: "FR.VOC.FAMILLES", niveau: 1, format: "qcm", consigne: "Quel mot est de la même famille que lait ?", phrase: "", options: ["laitier", "montagne", "sauter"], attendu: "laitier", explication: "La famille de lait parle du lait. laitier est de la même famille." },
  { cle: "voc-fam-n1-5", competence: "FR.VOC.FAMILLES", niveau: 1, format: "qcm", consigne: "Quel mot est de la même famille que jardin ?", phrase: "", options: ["jardinier", "cuisine", "rouge"], attendu: "jardinier", explication: "La famille de jardin parle du jardin. jardinier est de la même famille, c'est la personne qui s'occupe du jardin." },
  { cle: "voc-fam-n2-1", competence: "FR.VOC.FAMILLES", niveau: 2, format: "clic", consigne: "Clique sur le mot de la même famille que chant.", phrase: "chanteur table rapide", attendu: "chanteur", explication: "La famille de chant parle de chanter. chanteur est de la même famille." },
  { cle: "voc-fam-n2-2", competence: "FR.VOC.FAMILLES", niveau: 2, format: "clic", consigne: "Clique sur le mot de la même famille que glace.", phrase: "voiture glacier soleil", attendu: "glacier", explication: "La famille de glace parle de la glace. glacier est de la même famille." },
  { cle: "voc-fam-n2-3", competence: "FR.VOC.FAMILLES", niveau: 2, format: "clic", consigne: "Clique sur le mot de la même famille que mer.", phrase: "montagne marin cahier", attendu: "marin", explication: "La famille de mer parle de la mer. marin est de la même famille, c'est celui qui travaille sur la mer." },
  { cle: "voc-fam-n2-4", competence: "FR.VOC.FAMILLES", niveau: 2, format: "clic", consigne: "Clique sur le mot de la même famille que fort.", phrase: "fortement nuage pomme", attendu: "fortement", explication: "La famille de fort parle de la force. fortement est de la même famille." },
  { cle: "voc-fam-n2-5", competence: "FR.VOC.FAMILLES", niveau: 2, format: "clic", consigne: "Clique sur le mot de la même famille que lent.", phrase: "lentement arbre maison", attendu: "lentement", explication: "La famille de lent parle d'aller doucement. lentement est de la même famille." },
  { cle: "voc-fam-n3-1", competence: "FR.VOC.FAMILLES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas de la même famille que les autres.", phrase: "fleur fleuriste fleurir voiture", attendu: "voiture", explication: "fleur, fleuriste et fleurir parlent tous des fleurs. voiture n'a rien à voir, c'est l'intrus." },
  { cle: "voc-fam-n3-2", competence: "FR.VOC.FAMILLES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas de la même famille que les autres.", phrase: "dent dentiste dentaire soleil", attendu: "soleil", explication: "dent, dentiste et dentaire parlent des dents. soleil est l'intrus." },
  { cle: "voc-fam-n3-3", competence: "FR.VOC.FAMILLES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas de la même famille que les autres.", phrase: "terre terrain atterrir banane", attendu: "banane", explication: "terre, terrain et atterrir parlent de la terre. banane est l'intrus." },
  { cle: "voc-fam-n3-4", competence: "FR.VOC.FAMILLES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas de la même famille que les autres.", phrase: "lait laitier laitage montagne", attendu: "montagne", explication: "lait, laitier et laitage parlent du lait. montagne est l'intrus." },
  { cle: "voc-fam-n3-5", competence: "FR.VOC.FAMILLES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas de la même famille que les autres.", phrase: "jardin jardinier jardinage tigre", attendu: "tigre", explication: "jardin, jardinier et jardinage parlent du jardin. tigre est l'intrus." },
  { cle: "voc-fam-n4-1", competence: "FR.VOC.FAMILLES", niveau: 4, format: "texte", consigne: "La personne qui soigne les dents est le... Écris le mot de la famille de dent.", phrase: "La personne qui soigne les dents est le ___.", attendu: "dentiste", explication: "La famille de dent donne dentiste." },
  { cle: "voc-fam-n4-2", competence: "FR.VOC.FAMILLES", niveau: 4, format: "texte", consigne: "La personne qui vend des fleurs est le... Écris le mot de la famille de fleur.", phrase: "La personne qui vend des fleurs est le ___.", attendu: "fleuriste", explication: "La famille de fleur donne fleuriste." },
  { cle: "voc-fam-n4-3", competence: "FR.VOC.FAMILLES", niveau: 4, format: "texte", consigne: "La personne qui s'occupe du jardin est le... Écris le mot de la famille de jardin.", phrase: "La personne qui s'occupe du jardin est le ___.", attendu: "jardinier", explication: "La famille de jardin donne jardinier." },
  { cle: "voc-fam-n4-4", competence: "FR.VOC.FAMILLES", niveau: 4, format: "texte", consigne: "La personne qui fait la cuisine est le... Écris le mot de la famille de cuisine.", phrase: "La personne qui fait la cuisine est le ___.", attendu: "cuisinier", explication: "La famille de cuisine donne cuisinier." },
  { cle: "voc-fam-n4-5", competence: "FR.VOC.FAMILLES", niveau: 4, format: "texte", consigne: "La personne qui travaille sur la mer est le... Écris le mot de la famille de mer.", phrase: "La personne qui travaille sur la mer est le ___.", attendu: "marin", explication: "La famille de mer donne marin." },
  // FR.VOC.SYN_CONTRAIRES
  { cle: "voc-syn-n1-1", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 1, format: "qcm", consigne: "Quel mot veut dire presque la même chose que content ?", phrase: "", options: ["heureux", "triste", "grand"], attendu: "heureux", explication: "content et heureux veulent dire la même chose. Quand on est content, on est heureux." },
  { cle: "voc-syn-n1-2", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 1, format: "qcm", consigne: "Quel mot veut dire presque la même chose que joli ?", phrase: "", options: ["beau", "laid", "petit"], attendu: "beau", explication: "joli et beau veulent dire la même chose." },
  { cle: "voc-syn-n1-3", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 1, format: "qcm", consigne: "Quel mot veut dire presque la même chose que voiture ?", phrase: "", options: ["auto", "vélo", "route"], attendu: "auto", explication: "voiture et auto veulent dire la même chose." },
  { cle: "voc-syn-n1-4", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 1, format: "qcm", consigne: "Quel mot veut dire presque la même chose que gentil ?", phrase: "", options: ["aimable", "méchant", "grand"], attendu: "aimable", explication: "gentil et aimable veulent dire la même chose." },
  { cle: "voc-syn-n1-5", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 1, format: "qcm", consigne: "Quel mot veut dire presque la même chose que drôle ?", phrase: "", options: ["amusant", "sérieux", "lent"], attendu: "amusant", explication: "drôle et amusant veulent dire la même chose. Ce qui est drôle nous fait rire." },
  { cle: "voc-syn-n2-1", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 2, format: "qcm", consigne: "Quel mot veut dire le contraire de grand ?", phrase: "", options: ["petit", "gros", "haut"], attendu: "petit", explication: "Le contraire de grand est petit." },
  { cle: "voc-syn-n2-2", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 2, format: "qcm", consigne: "Quel mot veut dire le contraire de chaud ?", phrase: "", options: ["froid", "tiède", "doux"], attendu: "froid", explication: "Le contraire de chaud est froid." },
  { cle: "voc-syn-n2-3", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 2, format: "qcm", consigne: "Quel mot veut dire le contraire de jour ?", phrase: "", options: ["nuit", "matin", "soir"], attendu: "nuit", explication: "Le contraire de jour est nuit." },
  { cle: "voc-syn-n2-4", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 2, format: "qcm", consigne: "Quel mot veut dire le contraire de content ?", phrase: "", options: ["triste", "heureux", "joyeux"], attendu: "triste", explication: "Le contraire de content est triste." },
  { cle: "voc-syn-n2-5", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 2, format: "qcm", consigne: "Quel mot veut dire le contraire de monter ?", phrase: "", options: ["descendre", "sauter", "courir"], attendu: "descendre", explication: "Le contraire de monter est descendre." },
  { cle: "voc-syn-n3-1", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 3, format: "qcm", consigne: "Quel mot veut dire le contraire de heureux ?", phrase: "", options: ["malheureux", "joyeux", "content"], attendu: "malheureux", explication: "On ajoute mal devant heureux pour dire le contraire: malheureux." },
  { cle: "voc-syn-n3-2", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 3, format: "qcm", consigne: "Quel mot veut dire le contraire de faire ?", phrase: "", options: ["défaire", "refaire", "fabriquer"], attendu: "défaire", explication: "On ajoute dé devant faire pour dire le contraire: défaire." },
  { cle: "voc-syn-n3-3", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 3, format: "qcm", consigne: "Quel mot veut dire le contraire de plier ?", phrase: "", options: ["déplier", "plisser", "ranger"], attendu: "déplier", explication: "On ajoute dé devant plier pour dire le contraire: déplier." },
  { cle: "voc-syn-n3-4", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 3, format: "qcm", consigne: "Quel mot veut dire le contraire de possible ?", phrase: "", options: ["impossible", "facile", "permis"], attendu: "impossible", explication: "On ajoute im devant possible pour dire le contraire: impossible." },
  { cle: "voc-syn-n3-5", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 3, format: "qcm", consigne: "Quel mot veut dire le contraire de ranger ?", phrase: "", options: ["déranger", "classer", "poser"], attendu: "déranger", explication: "On ajoute dé devant ranger pour dire le contraire: déranger." },
  { cle: "voc-syn-n4-1", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 4, format: "texte", consigne: "Écris le contraire de grand.", phrase: "Le contraire de grand est ___.", attendu: "petit", explication: "Le contraire de grand est petit." },
  { cle: "voc-syn-n4-2", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 4, format: "texte", consigne: "Écris le contraire de chaud.", phrase: "Le contraire de chaud est ___.", attendu: "froid", explication: "Le contraire de chaud est froid." },
  { cle: "voc-syn-n4-3", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 4, format: "texte", consigne: "Écris le contraire de jour.", phrase: "Le contraire de jour est ___.", attendu: "nuit", explication: "Le contraire de jour est nuit." },
  { cle: "voc-syn-n4-4", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 4, format: "texte", consigne: "Écris le contraire de rapide.", phrase: "Le contraire de rapide est ___.", attendu: "lent", explication: "Le contraire de rapide est lent." },
  { cle: "voc-syn-n4-5", competence: "FR.VOC.SYN_CONTRAIRES", niveau: 4, format: "texte", consigne: "Écris le contraire de ouvrir.", phrase: "Le contraire de ouvrir est ___.", attendu: "fermer", explication: "Le contraire de ouvrir est fermer." },
  // FR.VOC.PREFIXE_SUFFIXE
  { cle: "voc-ps-n1-1", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 1, format: "qcm", consigne: "Quel mot veut dire faire encore, recommencer ?", phrase: "", options: ["refaire", "défaire", "faire"], attendu: "refaire", explication: "Le petit mot re devant faire veut dire encore. refaire, c'est faire une deuxième fois." },
  { cle: "voc-ps-n1-2", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 1, format: "qcm", consigne: "Quel mot veut dire lire encore ?", phrase: "", options: ["relire", "élire", "lire"], attendu: "relire", explication: "Le petit mot re devant lire veut dire encore. relire, c'est lire une deuxième fois." },
  { cle: "voc-ps-n1-3", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 1, format: "qcm", consigne: "Quel mot veut dire une petite maison ?", phrase: "", options: ["maisonnette", "maison", "grande"], attendu: "maisonnette", explication: "Le petit bout ette à la fin veut dire petit. une maisonnette est une petite maison." },
  { cle: "voc-ps-n1-4", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 1, format: "qcm", consigne: "Quel mot veut dire une petite tarte ?", phrase: "", options: ["tartelette", "tarte", "gâteau"], attendu: "tartelette", explication: "Le petit bout ette à la fin veut dire petit. une tartelette est une petite tarte." },
  { cle: "voc-ps-n1-5", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 1, format: "qcm", consigne: "Quel mot désigne la personne qui chante ?", phrase: "", options: ["chanteur", "chanson", "chanter"], attendu: "chanteur", explication: "Le petit bout eur à la fin montre la personne qui fait l'action. un chanteur, c'est celui qui chante." },
  { cle: "voc-ps-n2-1", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 2, format: "qcm", consigne: "Quel mot désigne la personne qui joue ?", phrase: "", options: ["joueur", "jouet", "jouer"], attendu: "joueur", explication: "Le petit bout eur montre la personne qui fait l'action. un joueur, c'est celui qui joue." },
  { cle: "voc-ps-n2-2", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 2, format: "qcm", consigne: "Quel mot désigne la personne qui danse ?", phrase: "", options: ["danseur", "danse", "danser"], attendu: "danseur", explication: "Le petit bout eur montre la personne qui fait l'action. un danseur, c'est celui qui danse." },
  { cle: "voc-ps-n2-3", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 2, format: "qcm", consigne: "Quel mot veut dire une petite cloche ?", phrase: "", options: ["clochette", "cloche", "sonnette"], attendu: "clochette", explication: "Le petit bout ette veut dire petit. une clochette est une petite cloche." },
  { cle: "voc-ps-n2-4", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 2, format: "qcm", consigne: "Quel mot commence par le préfixe dé et dit le contraire de faire ?", phrase: "", options: ["défaire", "refaire", "faire"], attendu: "défaire", explication: "Le préfixe dé est au début de défaire. Il dit le contraire de faire." },
  { cle: "voc-ps-n2-5", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 2, format: "qcm", consigne: "Quel mot veut dire colorier encore ?", phrase: "", options: ["recolorier", "colorier", "décolorier"], attendu: "recolorier", explication: "Le préfixe re veut dire encore. recolorier, c'est colorier une deuxième fois." },
  { cle: "voc-ps-n3-1", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 3, format: "clic", consigne: "Clique sur le mot qui commence par le préfixe re.", phrase: "refaire chanteur petite", attendu: "refaire", explication: "Le préfixe re est au début de refaire. Il veut dire encore." },
  { cle: "voc-ps-n3-2", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 3, format: "clic", consigne: "Clique sur le mot qui commence par le préfixe dé.", phrase: "maison défaire joueur", attendu: "défaire", explication: "Le préfixe dé est au début de défaire. Il dit le contraire." },
  { cle: "voc-ps-n3-3", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 3, format: "clic", consigne: "Clique sur le mot qui se termine par eur, la personne qui fait l'action.", phrase: "chanson chanteur refaire", attendu: "chanteur", explication: "Le petit bout eur est à la fin de chanteur. C'est celui qui chante." },
  { cle: "voc-ps-n3-4", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 3, format: "clic", consigne: "Clique sur le mot qui se termine par ette et veut dire petit.", phrase: "maison maisonnette jardin", attendu: "maisonnette", explication: "Le petit bout ette est à la fin de maisonnette. une maisonnette est une petite maison." },
  { cle: "voc-ps-n3-5", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 3, format: "clic", consigne: "Clique sur le mot qui dit le contraire de possible.", phrase: "possible impossible facile", attendu: "impossible", explication: "Le préfixe im est au début de impossible. Il dit le contraire de possible." },
  { cle: "voc-ps-n4-1", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 4, format: "texte", consigne: "Ajoute le préfixe re devant le mot lire pour dire lire encore. Écris le mot.", phrase: "lire une deuxième fois, c'est ___", attendu: "relire", explication: "On met re devant lire: relire." },
  { cle: "voc-ps-n4-2", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 4, format: "texte", consigne: "Ajoute le préfixe dé devant le mot faire pour dire le contraire. Écris le mot.", phrase: "le contraire de faire, c'est ___", attendu: "défaire", explication: "On met dé devant faire: défaire." },
  { cle: "voc-ps-n4-3", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 4, format: "texte", consigne: "Écris la personne qui chante, avec le petit bout eur à la fin.", phrase: "celui qui chante est un ___", attendu: "chanteur", explication: "On ajoute eur à chant: chanteur." },
  { cle: "voc-ps-n4-4", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 4, format: "texte", consigne: "Écris une petite maison, avec le petit bout ette à la fin.", phrase: "une petite maison est une ___", attendu: "maisonnette", explication: "On ajoute ette à maison: maisonnette." },
  { cle: "voc-ps-n4-5", competence: "FR.VOC.PREFIXE_SUFFIXE", niveau: 4, format: "texte", consigne: "Ajoute le préfixe re devant le mot faire pour dire faire encore. Écris le mot.", phrase: "faire une deuxième fois, c'est ___", attendu: "refaire", explication: "On met re devant faire: refaire." },
  // FR.VOC.CATEGORIES
  { cle: "voc-cat-n1-1", competence: "FR.VOC.CATEGORIES", niveau: 1, format: "qcm", consigne: "Le chien, le chat et le lapin sont des...", phrase: "le chien, le chat et le lapin", options: ["animaux", "fruits", "couleurs"], attendu: "animaux", explication: "Le chien, le chat et le lapin sont tous des animaux. Animaux est le mot général." },
  { cle: "voc-cat-n1-2", competence: "FR.VOC.CATEGORIES", niveau: 1, format: "qcm", consigne: "La pomme, la banane et la cerise sont des...", phrase: "la pomme, la banane et la cerise", options: ["fruits", "légumes", "jouets"], attendu: "fruits", explication: "La pomme, la banane et la cerise sont des fruits." },
  { cle: "voc-cat-n1-3", competence: "FR.VOC.CATEGORIES", niveau: 1, format: "qcm", consigne: "Le rouge, le bleu et le vert sont des...", phrase: "le rouge, le bleu et le vert", options: ["couleurs", "animaux", "nombres"], attendu: "couleurs", explication: "Le rouge, le bleu et le vert sont des couleurs." },
  { cle: "voc-cat-n1-4", competence: "FR.VOC.CATEGORIES", niveau: 1, format: "qcm", consigne: "La carotte, le poireau et la tomate sont des...", phrase: "la carotte, le poireau et la tomate", options: ["légumes", "fruits", "fleurs"], attendu: "légumes", explication: "La carotte, le poireau et la tomate sont des légumes." },
  { cle: "voc-cat-n1-5", competence: "FR.VOC.CATEGORIES", niveau: 1, format: "qcm", consigne: "Le train, le vélo et la voiture sont des...", phrase: "le train, le vélo et la voiture", options: ["véhicules", "animaux", "vêtements"], attendu: "véhicules", explication: "Le train, le vélo et la voiture servent à se déplacer: ce sont des véhicules." },
  { cle: "voc-cat-n2-1", competence: "FR.VOC.CATEGORIES", niveau: 2, format: "qcm", consigne: "Quel mot est un fruit ?", phrase: "", options: ["poire", "carotte", "chaise"], attendu: "poire", explication: "La poire est un fruit. La carotte est un légume." },
  { cle: "voc-cat-n2-2", competence: "FR.VOC.CATEGORIES", niveau: 2, format: "qcm", consigne: "Quel mot est un animal ?", phrase: "", options: ["renard", "table", "rouge"], attendu: "renard", explication: "Le renard est un animal." },
  { cle: "voc-cat-n2-3", competence: "FR.VOC.CATEGORIES", niveau: 2, format: "qcm", consigne: "Quel mot est un légume ?", phrase: "", options: ["poireau", "pomme", "vélo"], attendu: "poireau", explication: "Le poireau est un légume." },
  { cle: "voc-cat-n2-4", competence: "FR.VOC.CATEGORIES", niveau: 2, format: "qcm", consigne: "Quel mot est un vêtement ?", phrase: "", options: ["manteau", "banane", "chien"], attendu: "manteau", explication: "Le manteau est un vêtement, on le met pour avoir chaud." },
  { cle: "voc-cat-n2-5", competence: "FR.VOC.CATEGORIES", niveau: 2, format: "qcm", consigne: "Quel mot est un meuble ?", phrase: "", options: ["armoire", "pomme", "nuage"], attendu: "armoire", explication: "L'armoire est un meuble, on range les habits dedans." },
  { cle: "voc-cat-n3-1", competence: "FR.VOC.CATEGORIES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas un fruit.", phrase: "pomme banane carotte poire", attendu: "carotte", explication: "La pomme, la banane et la poire sont des fruits. La carotte est un légume, c'est l'intrus." },
  { cle: "voc-cat-n3-2", competence: "FR.VOC.CATEGORIES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas un animal.", phrase: "chien chat table lapin", attendu: "table", explication: "Le chien, le chat et le lapin sont des animaux. La table est l'intrus." },
  { cle: "voc-cat-n3-3", competence: "FR.VOC.CATEGORIES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas une couleur.", phrase: "rouge bleu banane vert", attendu: "banane", explication: "Rouge, bleu et vert sont des couleurs. Banane est l'intrus." },
  { cle: "voc-cat-n3-4", competence: "FR.VOC.CATEGORIES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas un légume.", phrase: "carotte tomate poire poireau", attendu: "poire", explication: "La carotte, la tomate et le poireau sont des légumes. La poire est un fruit, c'est l'intrus." },
  { cle: "voc-cat-n3-5", competence: "FR.VOC.CATEGORIES", niveau: 3, format: "clic", consigne: "Clique sur le mot qui n'est pas un vêtement.", phrase: "manteau pantalon armoire pull", attendu: "armoire", explication: "Le manteau, le pantalon et le pull sont des vêtements. L'armoire est un meuble, c'est l'intrus." },
  { cle: "voc-cat-n4-1", competence: "FR.VOC.CATEGORIES", niveau: 4, format: "texte", consigne: "La rose, la tulipe et le lilas sont des... Écris le mot général.", phrase: "La rose, la tulipe et le lilas sont des ___.", attendu: "fleurs", explication: "La rose, la tulipe et le lilas sont des fleurs." },
  { cle: "voc-cat-n4-2", competence: "FR.VOC.CATEGORIES", niveau: 4, format: "texte", consigne: "Le lion, le tigre et l'ours sont des... Écris le mot général.", phrase: "Le lion, le tigre et l'ours sont des ___.", attendu: "animaux", explication: "Le lion, le tigre et l'ours sont des animaux." },
  { cle: "voc-cat-n4-3", competence: "FR.VOC.CATEGORIES", niveau: 4, format: "texte", consigne: "La pomme, la poire et la fraise sont des... Écris le mot général.", phrase: "La pomme, la poire et la fraise sont des ___.", attendu: "fruits", explication: "La pomme, la poire et la fraise sont des fruits." },
  { cle: "voc-cat-n4-4", competence: "FR.VOC.CATEGORIES", niveau: 4, format: "texte", consigne: "Le rouge, le jaune et le bleu sont des... Écris le mot général.", phrase: "Le rouge, le jaune et le bleu sont des ___.", attendu: "couleurs", explication: "Le rouge, le jaune et le bleu sont des couleurs." },
  { cle: "voc-cat-n4-5", competence: "FR.VOC.CATEGORIES", niveau: 4, format: "texte", consigne: "Le bus, le train et l'avion sont des... Écris le mot général.", phrase: "Le bus, le train et l'avion sont des ___.", attendu: "véhicules", explication: "Le bus, le train et l'avion sont des véhicules." },
  // FR.VOC.SENS — le sens d'un mot selon le contexte (polysemie), ajout 0049
  { cle: "voc-sens-n1-1", competence: "FR.VOC.SENS", niveau: 1, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot souris ?", phrase: "Une petite souris grise court dans le jardin.", options: ["un petit animal", "la partie de l'ordinateur", "un gâteau"], attendu: "un petit animal", explication: "Le mot souris a deux sens. Ici, elle court dans le jardin : c'est le petit animal. Devant l'ordinateur, la souris est l'objet qu'on bouge avec la main." },
  { cle: "voc-sens-n1-2", competence: "FR.VOC.SENS", niveau: 1, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot glace ?", phrase: "En été, je mange une glace à la fraise.", options: ["un dessert froid et sucré", "l'eau gelée du lac", "un miroir"], attendu: "un dessert froid et sucré", explication: "Le mot glace a plusieurs sens. Ici, on la mange à la fraise : c'est le dessert froid. Sur le lac en hiver, la glace est l'eau qui a gelé." },
  { cle: "voc-sens-n1-3", competence: "FR.VOC.SENS", niveau: 1, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot feuille ?", phrase: "L'arbre perd ses feuilles quand il fait froid.", options: ["la partie verte de l'arbre", "une feuille de papier", "un fruit"], attendu: "la partie verte de l'arbre", explication: "feuille a deux sens. Ici, elle tombe de l'arbre : c'est la feuille verte. Pour écrire, une feuille est un papier." },
  { cle: "voc-sens-n1-4", competence: "FR.VOC.SENS", niveau: 1, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot orange ?", phrase: "Je presse une orange pour faire du jus.", options: ["un fruit", "une couleur", "un légume"], attendu: "un fruit", explication: "orange a deux sens. Ici, on en fait du jus : c'est le fruit. orange est aussi une couleur, comme la carotte." },
  { cle: "voc-sens-n1-5", competence: "FR.VOC.SENS", niveau: 1, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot carte ?", phrase: "Au restaurant, le serveur apporte la carte.", options: ["la liste des plats", "une carte de France", "une carte à jouer"], attendu: "la liste des plats", explication: "carte a plusieurs sens. Au restaurant, la carte montre les plats qu'on peut choisir. En géographie, une carte montre le pays." },
  { cle: "voc-sens-n2-1", competence: "FR.VOC.SENS", niveau: 2, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot pièce ?", phrase: "Dans ma maison, ma chambre est la plus belle pièce.", options: ["une salle de la maison", "une pièce de monnaie", "un morceau"], attendu: "une salle de la maison", explication: "pièce a deux sens. Ici, c'est une salle de la maison, comme la cuisine. Dans le porte-monnaie, une pièce sert à payer." },
  { cle: "voc-sens-n2-2", competence: "FR.VOC.SENS", niveau: 2, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot bouton ?", phrase: "Il manque un bouton à ma chemise.", options: ["ce qui ferme un vêtement", "un bouton sur la peau", "un bouton de fleur"], attendu: "ce qui ferme un vêtement", explication: "bouton a plusieurs sens. Sur la chemise, le bouton sert à la fermer. Sur la peau, un bouton est un petit point rouge." },
  { cle: "voc-sens-n2-3", competence: "FR.VOC.SENS", niveau: 2, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot règle ?", phrase: "Je trace un trait avec ma règle.", options: ["un objet plat pour tracer", "la règle d'un jeu", "une loi"], attendu: "un objet plat pour tracer", explication: "règle a deux sens. Pour tracer un trait, la règle est l'objet plat. Dans un jeu, la règle dit ce qu'on a le droit de faire." },
  { cle: "voc-sens-n2-4", competence: "FR.VOC.SENS", niveau: 2, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot tour ?", phrase: "Du haut de la tour, on voit toute la ville.", options: ["un grand bâtiment haut", "un tour de magie", "un petit voyage"], attendu: "un grand bâtiment haut", explication: "tour a deux sens. Ici, c'est le grand bâtiment très haut d'où on voit loin. Un tour de magie, c'est quelque chose de différent." },
  { cle: "voc-sens-n2-5", competence: "FR.VOC.SENS", niveau: 2, format: "qcm", consigne: "Dans cette phrase, que veut dire le mot carte ?", phrase: "Pour trouver la ville, je regarde la carte.", options: ["un dessin du pays", "la liste des plats", "une carte à jouer"], attendu: "un dessin du pays", explication: "carte a plusieurs sens. Ici, on cherche une ville : c'est la carte qui dessine le pays et les routes." },
  { cle: "voc-sens-n3-1", competence: "FR.VOC.SENS", niveau: 3, format: "qcm", consigne: "Dans quelle phrase le mot glace veut dire un dessert ?", phrase: "Phrase A : Le lac est couvert de glace. Phrase B : Je mange une glace au chocolat.", options: ["la phrase B", "la phrase A", "les deux"], attendu: "la phrase B", explication: "Dans la phrase B, on la mange au chocolat : c'est le dessert. Dans la phrase A, la glace est l'eau gelée du lac." },
  { cle: "voc-sens-n3-2", competence: "FR.VOC.SENS", niveau: 3, format: "qcm", consigne: "Dans quelle phrase le mot souris est un animal ?", phrase: "Phrase A : La souris mange le fromage. Phrase B : Je clique avec la souris.", options: ["la phrase A", "la phrase B", "les deux"], attendu: "la phrase A", explication: "Dans la phrase A, elle mange du fromage : c'est l'animal. Dans la phrase B, c'est l'objet de l'ordinateur." },
  { cle: "voc-sens-n3-3", competence: "FR.VOC.SENS", niveau: 3, format: "qcm", consigne: "Dans quelle phrase le mot feuille est une feuille de papier ?", phrase: "Phrase A : J'écris sur une feuille. Phrase B : La feuille tombe de l'arbre.", options: ["la phrase A", "la phrase B", "les deux"], attendu: "la phrase A", explication: "Dans la phrase A, on écrit dessus : c'est le papier. Dans la phrase B, elle tombe de l'arbre : c'est la feuille verte." },
  { cle: "voc-sens-n3-4", competence: "FR.VOC.SENS", niveau: 3, format: "qcm", consigne: "Dans quelle phrase le mot bouton sert à fermer un vêtement ?", phrase: "Phrase A : J'appuie sur le bouton de la télé. Phrase B : Je recouds le bouton de mon manteau.", options: ["la phrase B", "la phrase A", "les deux"], attendu: "la phrase B", explication: "Dans la phrase B, on le recoud sur le manteau : il ferme le vêtement. Dans la phrase A, c'est le bouton sur lequel on appuie." },
  { cle: "voc-sens-n3-5", competence: "FR.VOC.SENS", niveau: 3, format: "qcm", consigne: "Dans quelle phrase le mot carte sert à jouer ?", phrase: "Phrase A : Je pose une carte sur la table pour jouer. Phrase B : Je regarde la carte pour trouver la route.", options: ["la phrase A", "la phrase B", "les deux"], attendu: "la phrase A", explication: "Dans la phrase A, on la pose pour jouer : c'est la carte à jouer. Dans la phrase B, elle montre les routes." },
  { cle: "voc-sens-n4-1", competence: "FR.VOC.SENS", niveau: 4, format: "texte", consigne: "Écris le mot qui va dans les deux phrases. C'est le même mot, mais il a deux sens.", phrase: "Je mange une ___ à la vanille. Le lac se couvre de ___ quand il gèle.", attendu: "glace", explication: "C'est le mot glace. On mange une glace, le dessert. Et sur le lac, la glace est l'eau gelée. Le même mot a deux sens." },
  { cle: "voc-sens-n4-2", competence: "FR.VOC.SENS", niveau: 4, format: "texte", consigne: "Écris le mot qui va dans les deux phrases. C'est le même mot, mais il a deux sens.", phrase: "Le chat court après la ___. Je bouge la ___ de l'ordinateur.", attendu: "souris", explication: "C'est le mot souris. C'est l'animal, et aussi l'objet de l'ordinateur." },
  { cle: "voc-sens-n4-3", competence: "FR.VOC.SENS", niveau: 4, format: "texte", consigne: "Écris le mot qui va dans les deux phrases. C'est le même mot, mais il a deux sens.", phrase: "J'écris sur une ___ de papier. La ___ verte tombe de l'arbre.", attendu: "feuille", explication: "C'est le mot feuille. C'est le papier, et aussi la feuille verte de l'arbre." },
  { cle: "voc-sens-n4-4", competence: "FR.VOC.SENS", niveau: 4, format: "texte", consigne: "Écris le mot qui va dans les deux phrases. C'est le même mot, mais il a deux sens.", phrase: "Je presse une ___ pour le jus. J'ai colorié le soleil en ___.", attendu: "orange", explication: "C'est le mot orange. C'est le fruit, et aussi la couleur." },
  { cle: "voc-sens-n4-5", competence: "FR.VOC.SENS", niveau: 4, format: "texte", consigne: "Écris le mot qui va dans les deux phrases. C'est le même mot, mais il a deux sens.", phrase: "Je pose une ___ pour jouer. Je cherche la ville sur la ___.", attendu: "carte", explication: "C'est le mot carte. C'est la carte à jouer, et aussi la carte qui montre le pays." },

  // FR.VOC.SENS_FIGURE (CM1) — sens propre et sens figuré (eduscol doc 13984).
  // N1 QCM reconnaitre propre/figure ; N2/N3 QCM sens d'une expression imagee ;
  // N4 reponse libre (ecrire « propre » ou « figuré »).
  { cle: "voc-fig-n1-1", competence: "FR.VOC.SENS_FIGURE", niveau: 1, format: "qcm", consigne: "Le mot « mange » est-il employé au sens propre (le vrai sens) ou au sens figuré (une image) ?", phrase: "Le chien mange ses croquettes.", options: ["sens propre", "sens figuré"], attendu: "sens propre", explication: "Le chien mange vraiment ses croquettes : c'est le sens propre, le vrai sens." },
  { cle: "voc-fig-n1-2", competence: "FR.VOC.SENS_FIGURE", niveau: 1, format: "qcm", consigne: "L'expression « avoir la pêche » est-elle au sens propre ou au sens figuré ?", phrase: "Ce matin, Paul a la pêche.", options: ["sens figuré", "sens propre"], attendu: "sens figuré", explication: "Paul n'a pas un vrai fruit ! Avoir la pêche veut dire être plein d'énergie, en forme : c'est le sens figuré, une image." },
  { cle: "voc-fig-n1-3", competence: "FR.VOC.SENS_FIGURE", niveau: 1, format: "qcm", consigne: "Le mot « brille » est-il employé au sens propre ou au sens figuré ?", phrase: "Le soleil brille dans le ciel.", options: ["sens propre", "sens figuré"], attendu: "sens propre", explication: "Le soleil brille vraiment, il envoie de la lumière : c'est le sens propre." },
  { cle: "voc-fig-n2-1", competence: "FR.VOC.SENS_FIGURE", niveau: 2, format: "qcm", consigne: "Que veut dire « avoir un cœur d'or » ?", phrase: "Ma grand-mère a un cœur d'or.", options: ["être très gentil", "avoir un cœur en métal", "être riche"], attendu: "être très gentil", explication: "Un cœur d'or n'est pas un vrai cœur en or. C'est une image : la personne est très gentille et généreuse." },
  { cle: "voc-fig-n2-2", competence: "FR.VOC.SENS_FIGURE", niveau: 2, format: "qcm", consigne: "Que veut dire « tomber dans les pommes » ?", phrase: "Il a eu si chaud qu'il est tombé dans les pommes.", options: ["s'évanouir", "tomber sur des pommes", "avoir faim"], attendu: "s'évanouir", explication: "Tomber dans les pommes est une expression imagée. Cela veut dire s'évanouir, perdre connaissance un petit moment." },
  { cle: "voc-fig-n2-3", competence: "FR.VOC.SENS_FIGURE", niveau: 2, format: "qcm", consigne: "Que veut dire « avoir la tête dans les nuages » ?", phrase: "En classe, Tom a souvent la tête dans les nuages.", options: ["être distrait, rêver", "être dans le ciel", "être très grand"], attendu: "être distrait, rêver", explication: "Avoir la tête dans les nuages est une image. Cela veut dire être distrait, penser à autre chose, rêver." },
  { cle: "voc-fig-n3-1", competence: "FR.VOC.SENS_FIGURE", niveau: 3, format: "qcm", consigne: "Dans quelle phrase le mot « briller » est-il au sens figuré ?", phrase: "A : Le soleil brille. B : Léa brille en classe.", options: ["la phrase B", "la phrase A"], attendu: "la phrase B", explication: "Dans la phrase A, le soleil brille vraiment (sens propre). Dans la phrase B, Léa brille veut dire qu'elle réussit très bien : c'est le sens figuré." },
  { cle: "voc-fig-n3-2", competence: "FR.VOC.SENS_FIGURE", niveau: 3, format: "qcm", consigne: "Que veut dire « se creuser la tête » ?", phrase: "Pour ce problème, j'ai dû me creuser la tête.", options: ["réfléchir très fort", "se faire mal à la tête", "se laver la tête"], attendu: "réfléchir très fort", explication: "Se creuser la tête est une image. Cela veut dire réfléchir beaucoup, chercher fort une solution." },
  { cle: "voc-fig-n3-3", competence: "FR.VOC.SENS_FIGURE", niveau: 3, format: "qcm", consigne: "Que veut dire « couper la poire en deux » ?", phrase: "Pour être justes, ils ont coupé la poire en deux.", options: ["trouver un accord, partager", "couper un vrai fruit", "bouder chacun de son côté"], attendu: "trouver un accord, partager", explication: "Couper la poire en deux est une image. Cela veut dire trouver un accord, faire chacun un petit effort pour être d'accord." },
  { cle: "voc-fig-n4-1", competence: "FR.VOC.SENS_FIGURE", niveau: 4, format: "texte", consigne: "Cette phrase est-elle au sens propre ou au sens figuré ? Écris ta réponse en un mot : propre ou figuré.", phrase: "Dehors, il pleut des cordes.", attendu: "figuré", explication: "Il ne tombe pas de vraies cordes ! Il pleut des cordes veut dire qu'il pleut très fort : c'est le sens figuré." },
  { cle: "voc-fig-n4-2", competence: "FR.VOC.SENS_FIGURE", niveau: 4, format: "texte", consigne: "Cette phrase est-elle au sens propre ou au sens figuré ? Écris ta réponse en un mot : propre ou figuré.", phrase: "Le jardinier arrose les fleurs.", attendu: "propre", explication: "Le jardinier arrose vraiment les fleurs avec de l'eau : c'est le sens propre, le vrai sens." },
  { cle: "voc-fig-n4-3", competence: "FR.VOC.SENS_FIGURE", niveau: 4, format: "texte", consigne: "Cette phrase est-elle au sens propre ou au sens figuré ? Écris ta réponse en un mot : propre ou figuré.", phrase: "Après la bonne nouvelle, il était aux anges.", attendu: "figuré", explication: "Il n'est pas vraiment avec des anges ! Être aux anges veut dire être très heureux : c'est le sens figuré." },

  // FR.VOC.REGISTRES (CM1) — registres de langue : familier / courant / soutenu
  // (eduscol doc 13984). N1 QCM reconnaitre le registre d'un mot ; N2/N3 QCM
  // (trouver un synonyme / classer) ; N4 reponse libre (ecrire le registre).
  { cle: "voc-reg-n1-1", competence: "FR.VOC.REGISTRES", niveau: 1, format: "qcm", consigne: "Le mot « bouffer » appartient à quel registre de langue ?", phrase: "", options: ["familier", "soutenu"], attendu: "familier", explication: "bouffer est un mot familier, qu'on dit entre copains. Le mot courant, poli, est manger." },
  { cle: "voc-reg-n1-2", competence: "FR.VOC.REGISTRES", niveau: 1, format: "qcm", consigne: "Le mot « bagnole » appartient à quel registre de langue ?", phrase: "", options: ["familier", "courant"], attendu: "familier", explication: "bagnole est un mot familier pour voiture. Le mot courant est voiture." },
  { cle: "voc-reg-n1-3", competence: "FR.VOC.REGISTRES", niveau: 1, format: "qcm", consigne: "Le mot « demeure » (une belle maison) appartient à quel registre ?", phrase: "", options: ["soutenu", "familier"], attendu: "soutenu", explication: "demeure est un mot soutenu, élégant, pour une belle maison. Le mot courant est maison." },
  { cle: "voc-reg-n2-1", competence: "FR.VOC.REGISTRES", niveau: 2, format: "qcm", consigne: "Quel mot est le plus courant pour dire « bouquin » ?", phrase: "", options: ["livre", "roman", "cahier"], attendu: "livre", explication: "bouquin est familier. Le mot courant, celui de tous les jours, est livre." },
  { cle: "voc-reg-n2-2", competence: "FR.VOC.REGISTRES", niveau: 2, format: "qcm", consigne: "Quel mot veut dire « content » en langage soutenu ?", phrase: "", options: ["ravi", "chouette", "sympa"], attendu: "ravi", explication: "ravi est un mot soutenu pour très content. chouette et sympa sont familiers." },
  { cle: "voc-reg-n2-3", competence: "FR.VOC.REGISTRES", niveau: 2, format: "qcm", consigne: "Quel mot est familier pour dire « parler » ?", phrase: "", options: ["causer", "s'exprimer", "discuter"], attendu: "causer", explication: "causer est familier pour parler. s'exprimer est soutenu, discuter est courant." },
  { cle: "voc-reg-n3-1", competence: "FR.VOC.REGISTRES", niveau: 3, format: "qcm", consigne: "À l'école, pour parler poliment à la maîtresse, quel registre utilises-tu ?", phrase: "", options: ["courant", "familier"], attendu: "courant", explication: "À l'école, on parle en langage courant, correct et poli. En familier, entre copains, on parle autrement." },
  { cle: "voc-reg-n3-2", competence: "FR.VOC.REGISTRES", niveau: 3, format: "qcm", consigne: "Classe le mot « rigoler » : familier, courant ou soutenu ?", phrase: "", options: ["familier", "courant", "soutenu"], attendu: "familier", explication: "rigoler est familier. Le mot courant est rire." },
  { cle: "voc-reg-n3-3", competence: "FR.VOC.REGISTRES", niveau: 3, format: "qcm", consigne: "Le mot « s'exprimer » (pour parler) est de quel registre ?", phrase: "", options: ["soutenu", "familier", "courant"], attendu: "soutenu", explication: "s'exprimer est un mot soutenu, élégant. Le mot courant est parler." },
  { cle: "voc-reg-n4-1", competence: "FR.VOC.REGISTRES", niveau: 4, format: "texte", consigne: "Le mot « flotte » (pour l'eau) est familier, courant ou soutenu ? Écris ta réponse en un mot.", phrase: "Passe-moi la flotte, j'ai soif.", attendu: "familier", explication: "flotte est un mot familier pour l'eau. Le mot courant est eau." },
  { cle: "voc-reg-n4-2", competence: "FR.VOC.REGISTRES", niveau: 4, format: "texte", consigne: "Le mot « demeure » est familier, courant ou soutenu ? Écris ta réponse en un mot.", phrase: "Nous emménageons dans une belle demeure.", attendu: "soutenu", explication: "demeure est un mot soutenu pour une belle maison." },
  { cle: "voc-reg-n4-3", competence: "FR.VOC.REGISTRES", niveau: 4, format: "texte", consigne: "Le mot « voiture » est familier, courant ou soutenu ? Écris ta réponse en un mot.", phrase: "La voiture rouge roule sur la route.", attendu: "courant", explication: "voiture est le mot courant, celui qu'on utilise tous les jours. Le mot familier est bagnole." },
];

export const BANQUE_MOTS: LexItem[] = [
  // FR.MOTS.INVARIABLES
  { cle: "mots-n1-beaucoup", competence: "FR.MOTS.INVARIABLES", niveau: 1, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["beaucoup", "bocoup", "beaucou"], attendu: "beaucoup", explication: "Dans beaucoup, on écrit b, e, a, u, puis coup avec un p à la fin qu'on n'entend pas." },
  { cle: "mots-n1-toujours", competence: "FR.MOTS.INVARIABLES", niveau: 1, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["toujours", "toujour", "toulours"], attendu: "toujours", explication: "À la fin de toujours, il y a un s qu'on n'entend pas." },
  { cle: "mots-n1-avec", competence: "FR.MOTS.INVARIABLES", niveau: 1, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["avec", "avek", "avc"], attendu: "avec", explication: "avec se termine par un c. On écrit a, v, e, c." },
  { cle: "mots-n1-dans", competence: "FR.MOTS.INVARIABLES", niveau: 1, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["dans", "dan", "dens"], attendu: "dans", explication: "À la fin de dans, il y a un s qu'on n'entend pas. On écrit d, a, n, s." },
  { cle: "mots-n1-aussi", competence: "FR.MOTS.INVARIABLES", niveau: 1, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["aussi", "ausi", "osi"], attendu: "aussi", explication: "Dans aussi, il y a deux s au milieu." },
  { cle: "mots-n2-maintenant", competence: "FR.MOTS.INVARIABLES", niveau: 2, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["maintenant", "maintenan", "mintenant"], attendu: "maintenant", explication: "À la fin de maintenant, il y a un t qu'on n'entend pas. Au milieu, on écrit a, i, n." },
  { cle: "mots-n2-souvent", competence: "FR.MOTS.INVARIABLES", niveau: 2, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["souvent", "souvant", "souven"], attendu: "souvent", explication: "À la fin de souvent, il y a un t qu'on n'entend pas." },
  { cle: "mots-n2-jamais", competence: "FR.MOTS.INVARIABLES", niveau: 2, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["jamais", "jamai", "jamès"], attendu: "jamais", explication: "À la fin de jamais, il y a un s qu'on n'entend pas." },
  { cle: "mots-n2-encore", competence: "FR.MOTS.INVARIABLES", niveau: 2, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["encore", "ancore", "encor"], attendu: "encore", explication: "encore commence par e, n, et se termine par un e." },
  { cle: "mots-n2-assez", competence: "FR.MOTS.INVARIABLES", niveau: 2, format: "qcm", consigne: "Quel mot est bien écrit ?", phrase: "", options: ["assez", "asez", "assé"], attendu: "assez", explication: "Dans assez, il y a deux s. À la fin, il y a un z qu'on n'entend pas." },
  { cle: "mots-n3-pendant", competence: "FR.MOTS.INVARIABLES", niveau: 3, format: "qcm", consigne: "Choisis le mot bien écrit pour compléter la phrase.", phrase: "Il a plu ___ la nuit.", options: ["pendant", "pandant", "pendan"], attendu: "pendant", explication: "À la fin de pendant, il y a un t qu'on n'entend pas." },
  { cle: "mots-n3-depuis", competence: "FR.MOTS.INVARIABLES", niveau: 3, format: "qcm", consigne: "Choisis le mot bien écrit pour compléter la phrase.", phrase: "Je t'attends ___ ce matin.", options: ["depuis", "depui", "depuit"], attendu: "depuis", explication: "À la fin de depuis, il y a un s qu'on n'entend pas." },
  { cle: "mots-n3-trop", competence: "FR.MOTS.INVARIABLES", niveau: 3, format: "qcm", consigne: "Choisis le mot bien écrit pour compléter la phrase.", phrase: "Ce sac est ___ lourd.", options: ["trop", "tro", "trops"], attendu: "trop", explication: "À la fin de trop, il y a un p qu'on n'entend pas." },
  { cle: "mots-n3-deja", competence: "FR.MOTS.INVARIABLES", niveau: 3, format: "qcm", consigne: "Choisis le mot bien écrit pour compléter la phrase.", phrase: "As-tu ___ fini ton travail ?", options: ["déjà", "deja", "déja"], attendu: "déjà", explication: "déjà a deux accents: un sur le e et un sur le a à la fin." },
  { cle: "mots-n3-bientot", competence: "FR.MOTS.INVARIABLES", niveau: 3, format: "qcm", consigne: "Choisis le mot bien écrit pour compléter la phrase.", phrase: "Les vacances arrivent ___.", options: ["bientôt", "bientot", "biento"], attendu: "bientôt", explication: "bientôt a un accent sur le o, et un t à la fin qu'on n'entend pas." },
  { cle: "mots-n4-aujourdhui", competence: "FR.MOTS.INVARIABLES", niveau: 4, format: "texte", consigne: "Écris le petit mot qui veut dire le jour où on est.", phrase: "___, nous allons à l'école.", attendu: "aujourd'hui", explication: "aujourd'hui s'écrit en deux morceaux reliés par une apostrophe: aujourd, puis hui. Il y a un d et un h qu'on n'entend pas." },
  { cle: "mots-n4-ensuite", competence: "FR.MOTS.INVARIABLES", niveau: 4, format: "texte", consigne: "Écris le petit mot qui veut dire après, pour continuer.", phrase: "D'abord je me lève, ___ je m'habille.", attendu: "ensuite", explication: "ensuite commence par e, n, et se termine par un e." },
  { cle: "mots-n4-beaucoup", competence: "FR.MOTS.INVARIABLES", niveau: 4, format: "texte", consigne: "Écris le petit mot qui veut dire une grande quantité.", phrase: "Il y a ___ de fleurs dans le jardin.", attendu: "beaucoup", explication: "Dans beaucoup, on écrit b, e, a, u, puis coup avec un p à la fin qu'on n'entend pas." },
  { cle: "mots-n4-toujours", competence: "FR.MOTS.INVARIABLES", niveau: 4, format: "texte", consigne: "Écris le petit mot qui veut dire tout le temps.", phrase: "Le soleil se lève ___ du même côté.", attendu: "toujours", explication: "À la fin de toujours, il y a un s qu'on n'entend pas." },
  { cle: "mots-n4-souvent", competence: "FR.MOTS.INVARIABLES", niveau: 4, format: "texte", consigne: "Écris le petit mot qui veut dire de nombreuses fois.", phrase: "Je vais ___ à la piscine.", attendu: "souvent", explication: "À la fin de souvent, il y a un t qu'on n'entend pas." },
];

// Banque complete (lookup par cle, juge local).
export const BANQUE_LEXIQUE: LexItem[] = [...BANQUE_VOCABULAIRE, ...BANQUE_MOTS];

export const COMPETENCES_VOCABULAIRE = [
  "FR.VOC.ALPHABET",
  "FR.VOC.FAMILLES",
  "FR.VOC.SYN_CONTRAIRES",
  "FR.VOC.PREFIXE_SUFFIXE",
  "FR.VOC.CATEGORIES",
  "FR.VOC.SENS",
  "FR.VOC.SENS_FIGURE",
  "FR.VOC.REGISTRES",
] as const;

export const COMPETENCES_MOTS = [
  "FR.MOTS.INVARIABLES",
] as const;

// Items jouables pour une competence et un niveau donnes.
export function itemsLexiqueDe(competence: string, niveau: number): LexItem[] {
  return BANQUE_LEXIQUE.filter((i) => i.competence === competence && i.niveau === niveau);
}

// Juge local (mode demo + feedback immediat) : miroir exact du serveur.
export function estJusteLexique(cle: string, saisie: string): boolean {
  const item = BANQUE_LEXIQUE.find((i) => i.cle === cle);
  if (!item) return false;
  return comparerLexique(item.format, saisie, item.attendu);
}

// Recupere un item par sa cle (utilise par le composant d'exercice).
export function itemLexiqueParCle(cle: string): LexItem | undefined {
  return BANQUE_LEXIQUE.find((i) => i.cle === cle);
}
